import "jsr:@supabase/functions-js/edge-runtime.d.ts";
import { createClient } from "npm:@supabase/supabase-js@2";

const cors = { "Access-Control-Allow-Origin": "*", "Access-Control-Allow-Headers": "authorization, x-client-info, apikey, content-type", "Access-Control-Allow-Methods": "POST, OPTIONS" };
const json = (body: unknown, status = 200) => new Response(JSON.stringify(body), { status, headers: { ...cors, "Content-Type": "application/json" } });
function secretKey() { const raw = Deno.env.get("SUPABASE_SECRET_KEYS"); if (raw) return JSON.parse(raw).default; return Deno.env.get("SUPABASE_SERVICE_ROLE_KEY")!; }
const adminClient = () => createClient(Deno.env.get("SUPABASE_URL")!, secretKey(), { auth: { autoRefreshToken: false, persistSession: false } });
async function requireAdmin(req: Request, db: ReturnType<typeof adminClient>) { const header = req.headers.get("Authorization") || ""; const token = header.startsWith("Bearer ") ? header.slice(7) : ""; if (!token) return null; const { data, error } = await db.auth.getUser(token); if (error || !data.user) return null; const { data: role } = await db.from("admin_roles").select("role").eq("user_id", data.user.id).eq("role", "admin").maybeSingle(); return role ? data.user : null; }
Deno.serve(async (req) => { if (req.method === "OPTIONS") return new Response("ok", { headers: cors }); if (req.method !== "POST") return json({ ok: false, message: "Method not allowed" }, 405); const db = adminClient(); let body: any; try { body = await req.json(); } catch { return json({ ok: false, message: "Invalid request" }, 400); } const action = String(body?.action || "reset");
 if (action === "issue") { const admin = await requireAdmin(req, db); if (!admin) return json({ ok: false, message: "Admin authorization required" }, 403); const email = String(body?.email || "").trim().toLowerCase(); if (!email || !email.includes("@")) return json({ ok: false, message: "Invalid account email" }, 400); const { data: userId, error: lookupError } = await db.rpc("direct_recovery_lookup_user", { p_email: email }); if (lookupError || !userId) return json({ ok: false, message: "This account is not eligible for direct recovery" }, 400); const code = String(Math.floor(Math.random() * 1000000)).padStart(6, "0"); await db.from("direct_account_recovery_codes").delete().eq("user_id", userId).is("used_at", null); const digest = await crypto.subtle.digest("SHA-256", new TextEncoder().encode(code)); const codeHash = Array.from(new Uint8Array(digest)).map(x => x.toString(16).padStart(2, "0")).join(""); const { error } = await db.from("direct_account_recovery_codes").insert({ user_id: userId, code_hash: codeHash, expires_at: new Date(Date.now() + 30 * 60 * 1000).toISOString(), created_by: admin.id, ip_address: req.headers.get("x-forwarded-for")?.split(",")[0]?.trim() || null }); if (error) return json({ ok: false, message: "Could not issue recovery code" }, 500); await db.rpc("log_direct_recovery_event", { p_user_id: userId, p_action: "issued", p_metadata: { issued_by: admin.id } }); return json({ ok: true, recovery_code: code, expires_in_minutes: 30 }); }
 if (action !== "reset") return json({ ok: false, message: "Unsupported recovery action" }, 400); const email = String(body?.email || "").trim().toLowerCase(); const recoveryCode = String(body?.recovery_code || "").trim(); const newPassword = String(body?.new_password || ""); if (!email || !email.includes("@") || !/^\d{6}$/.test(recoveryCode) || newPassword.length < 10) return json({ ok: false, message: "Invalid recovery details" }, 400); const { data: userId, error: lookupError } = await db.rpc("direct_recovery_lookup_user", { p_email: email }); if (lookupError || !userId) return json({ ok: false, message: "We could not complete direct account recovery" }, 400); const { data: consumed, error: consumeError } = await db.rpc("direct_recovery_consume_code", { p_user_id: userId, p_code: recoveryCode }); if (consumeError || !consumed) { await db.rpc("log_direct_recovery_event", { p_user_id: userId, p_action: "reset_failed", p_metadata: { reason: "invalid_or_expired_code" } }); return json({ ok: false, message: "Invalid or expired recovery code" }, 400); } const { error: passwordError } = await db.auth.admin.updateUserById(userId, { password: newPassword }); if (passwordError) { await db.rpc("log_direct_recovery_event", { p_user_id: userId, p_action: "reset_failed", p_metadata: { reason: "password_update_failed" } }); return json({ ok: false, message: "Could not update the password" }, 500); } await db.rpc("log_direct_recovery_event", { p_user_id: userId, p_action: "reset_succeeded", p_metadata: {} }); return json({ ok: true }); });
