import { useEffect, useMemo, useState } from 'react'
import { Menu, X, Search, RefreshCw, ArrowLeft, ChevronRight } from 'lucide-react'
import { useLocation, useNavigate } from 'react-router-dom'
import { supabase } from './supabaseClient'
import AdminSupportChatPage from './AdminSupportChatPage'
import './admin.css'

type Customer={id:string;email:string|null;created_at:string;full_name:string|null;preferred_name:string|null;tier:string|null;country:string|null;customer_since:string|null;account_id:string|null;account_name:string|null;account_number_last4:string|null;account_status:string|null;available_balance:number|null;posted_balance:number|null;pending_balance:number|null}
type Account={id:string;user_id:string;account_name:string;account_number_last4:string|null;available_balance:number;posted_balance:number;pending_balance:number;status:string}
type Transaction={id:string;user_id:string;reference:string;transaction_type:string;direction:string;amount:number;currency:string;status:string;counterparty:string|null;description:string|null;effective_date:string;fee:number}
type SupportCase={id:string;user_id:string;case_number:string;subject:string;status:string;priority:string;created_at:string}
type AuditLog={id:string;user_id:string;action:string;resource_type:string;resource_id:string;metadata:any;created_at:string}
const money=(v:number|null|undefined,c='USD')=>new Intl.NumberFormat('en-US',{style:'currency',currency:c,maximumFractionDigits:2}).format(Number(v||0))
const shortId=(id:string)=>id?`${id.slice(0,8)}…${id.slice(-4)}`:'—'
const statuses=[['pending','Pending'],['processing','Processing'],['completed','Successful'],['failed','Failed'],['reversed','Reversed'],['cancelled','Cancelled']] as const

type Tab='overview'|'customers'|'transactions'|'support'|'audit'
export default function AdminPage(){
 const navigate=useNavigate(),location=useLocation()
 if(new URLSearchParams(location.search).get('view')==='support-chat')return <AdminSupportChatPage/>
 const[checking,setChecking]=useState(true),[allowed,setAllowed]=useState(false),[tab,setTab]=useState<Tab>('overview'),[mobileOpen,setMobileOpen]=useState(false)
 const[customers,setCustomers]=useState<Customer[]>([]),[accounts,setAccounts]=useState<Account[]>([]),[transactions,setTransactions]=useState<Transaction[]>([]),[cases,setCases]=useState<SupportCase[]>([]),[audits,setAudits]=useState<AuditLog[]>([])
 const[query,setQuery]=useState(''),[loading,setLoading]=useState(false),[error,setError]=useState(''),[selectedCustomer,setSelectedCustomer]=useState<Customer|null>(null),[selectedTransaction,setSelectedTransaction]=useState<Transaction|null>(null),[passwordCustomerId,setPasswordCustomerId]=useState<string|null>(null)
 const load=async()=>{setLoading(true);setError('');const admin=await supabase.rpc('is_admin');if(admin.error||!admin.data){setAllowed(false);setError(admin.error?.message||'Admin access required');setLoading(false);return}setAllowed(true);const[c,a,t,s,al]=await Promise.all([supabase.rpc('admin_list_customers'),supabase.from('accounts').select('id,user_id,account_name,account_number_last4,available_balance,posted_balance,pending_balance,status').order('created_at',{ascending:false}),supabase.from('transactions').select('id,user_id,reference,transaction_type,direction,amount,currency,status,counterparty,description,effective_date,fee').order('effective_date',{ascending:false}).order('created_at',{ascending:false}).limit(1000),supabase.from('support_cases').select('id,user_id,case_number,subject,status,priority,created_at').order('created_at',{ascending:false}).limit(500),supabase.rpc('admin_get_audit_logs',{p_limit:500})]);const first=[c,a,t,s,al].find(r=>r.error)?.error;if(first)setError(first.message);setCustomers((c.data||[])as Customer[]);setAccounts((a.data||[])as Account[]);setTransactions((t.data||[])as Transaction[]);setCases((s.data||[])as SupportCase[]);setAudits((al.data||[])as AuditLog[]);setLoading(false)}
 useEffect(()=>{let live=true;(async()=>{const session=await supabase.auth.getSession();if(!live)return;if(!session.data.session){navigate('/admin',{replace:true});return}setChecking(false);await load()})();return()=>{live=false}},[])
 const filteredCustomers=useMemo(()=>{const q=query.trim().toLowerCase();return q?customers.filter(c=>`${c.full_name||''} ${c.preferred_name||''} ${c.email||''} ${c.country||''} ${c.id}`.toLowerCase().includes(q)):customers},[customers,query])
 const filteredTransactions=useMemo(()=>{const q=query.trim().toLowerCase();return q?transactions.filter(t=>`${t.reference} ${t.counterparty||''} ${t.description||''} ${t.transaction_type} ${t.user_id}`.toLowerCase().includes(q)):transactions},[transactions,query])
 const totals=useMemo(()=>({customers:customers.length,accounts:accounts.length,balance:accounts.reduce((n,a)=>n+Number(a.available_balance||0),0),pending:accounts.reduce((n,a)=>n+Number(a.pending_balance||0),0),transactions:transactions.length,open:cases.filter(c=>c.status==='open').length}),[customers,accounts,transactions,cases])
 const updateTransactionStatus=async(id:string,status:string)=>{const r=await supabase.rpc('admin_set_transaction_status',{p_transaction_id:id,p_status:status});if(r.error)setError(r.error.message);else await load()}
 const updateAccountStatus=async(id:string,status:string)=>{const r=await supabase.rpc('admin_set_account_status',{p_account_id:id,p_status:status});if(r.error)setError(r.error.message);else await load()}
 const updateCase=async(id:string,status:string,priority?:string)=>{const r=await supabase.rpc('admin_update_support_case',{p_case_id:id,p_status:status,p_priority:priority||null});if(r.error)setError(r.error.message);else await load()}
 const switchTab=(next:Tab)=>{setTab(next);setQuery('');setSelectedCustomer(null);setSelectedTransaction(null);setMobileOpen(false)}
 if(checking)return <main className="admin-loading">Loading admin console…</main>
 if(!allowed)return <main className="admin-denied"><div><div className="admin-lock">FNCU</div><h1>Admin access required</h1><p>This area is restricted to authorized administrators.</p><button onClick={()=>navigate('/')}>Return to banking</button></div></main>
 const nav=<><div className="nav-label">WORKSPACE</div>{(['overview','customers','transactions','support','audit'] as Tab[]).map(item=><button key={item} className={tab===item?'active':''} onClick={()=>switchTab(item)}>{item==='overview'?'Overview':item==='customers'?'Customers':item==='transactions'?'Transactions':item==='support'?'Support':'Audit log'}</button>)}<div className="nav-label nav-label-spaced">ACCESS</div><button onClick={()=>{navigate('/admin/recovery');setMobileOpen(false)}}>Account recovery</button><button onClick={()=>{navigate('/admin?view=support-chat');setMobileOpen(false)}}>Customer service chat</button></>
 return <main className="admin-shell">
  {mobileOpen&&<button className="admin-mobile-scrim" aria-label="Close menu" onClick={()=>setMobileOpen(false)}/>}<aside className={`admin-sidebar ${mobileOpen?'mobile-open':''}`}><div className="admin-brand"><span>F</span><div><strong>FNCU</strong><small>ADMINISTRATION</small></div><button className="admin-mobile-close" onClick={()=>setMobileOpen(false)} aria-label="Close menu"><X size={20}/></button></div><nav className="admin-nav">{nav}</nav><button className="back-bank" onClick={()=>navigate('/')}>← Banking interface</button></aside>
  <section className="admin-main"><header className="admin-header"><div className="admin-header-left"><button className="admin-menu-button" onClick={()=>setMobileOpen(true)} aria-label="Open admin menu"><Menu size={22}/></button><div><div className="eyebrow">FNCU ADMINISTRATION</div><h1>{tab==='overview'?'Operations overview':tab==='customers'?'Customer directory':tab==='transactions'?'Transaction monitor':tab==='support'?'Support queue':'Audit log'}</h1><p className="admin-header-subtitle">Customer operations, account servicing, transaction review and support.</p></div></div><button className="refresh" onClick={load} disabled={loading}><RefreshCw size={14}/>{loading?'Refreshing…':'Refresh data'}</button></header>{error&&<div className="admin-error" role="alert">{error}</div>}
   {tab==='overview'&&<><div className="metric-grid"><Metric label="Customers" value={String(totals.customers)}/><Metric label="Accounts" value={String(totals.accounts)}/><Metric label="Available balance" value={money(totals.balance)}/><Metric label="Pending" value={money(totals.pending)}/><Metric label="Transactions loaded" value={String(totals.transactions)}/><Metric label="Open support cases" value={String(totals.open)}/></div><div className="admin-grid"><Panel title="Recent customers"><div className="table-wrap"><table><thead><tr><th>Customer</th><th>Email</th><th>Status</th><th>Since</th></tr></thead><tbody>{customers.slice(0,8).map(c=><tr key={c.id} className="click-row" onClick={()=>setSelectedCustomer(c)}><td><strong>{c.preferred_name||c.full_name||'Customer account'}</strong><small>{shortId(c.id)}</small></td><td>{c.email||'—'}</td><td>{c.account_status||'No account'}</td><td>{c.customer_since||new Date(c.created_at).toLocaleDateString()}</td></tr>)}</tbody></table></div></Panel><Panel title="Latest activity"><div className="activity-list">{transactions.slice(0,8).map(t=><button className="activity activity-button" key={t.id} onClick={()=>setSelectedTransaction(t)}><span className={t.direction==='credit'?'credit':'debit'}>{t.direction==='credit'?'+':'−'}</span><div><strong>{t.description||t.transaction_type}</strong><small>{t.reference} · {t.effective_date}</small></div><b>{money(t.amount,t.currency)}</b></button>)}</div></Panel></div></>}
   {tab==='customers'&&<><Toolbar value={query} onChange={setQuery} placeholder="Search by name, email, country or customer ID…"/><Panel title={`${filteredCustomers.length} customer accounts`}><div className="customer-card-grid">{filteredCustomers.map(c=><button className="customer-card" key={c.id} onClick={()=>setSelectedCustomer(c)}><div className="customer-card-top"><span className="customer-avatar">{(c.preferred_name||c.full_name||c.email||'C').charAt(0).toUpperCase()}</span><span className="customer-card-arrow"><ChevronRight size={16}/></span></div><strong>{c.preferred_name||c.full_name||'Customer account'}</strong><small>{c.email||'Email not available'}</small><div className="customer-card-meta"><span>{c.account_name||'No account linked'}</span><b>{c.account_status||'Profile only'}</b></div></button>)}</div></Panel>{selectedCustomer&&<CustomerDrawer customer={selectedCustomer} transactions={transactions.filter(t=>t.user_id===selectedCustomer.id)} cases={cases.filter(c=>c.user_id===selectedCustomer.id)} onClose={()=>setSelectedCustomer(null)} onStatus={updateAccountStatus} onTransaction={setSelectedTransaction} onRecovery={()=>setPasswordCustomerId(selectedCustomer.id)}/>}</>}
   {tab==='transactions'&&<><Toolbar value={query} onChange={setQuery} placeholder="Search reference, merchant, description or customer ID…"/><Panel title={`${filteredTransactions.length} transactions`}><div className="table-wrap"><table><thead><tr><th>Date</th><th>Reference</th><th>Description</th><th>Customer</th><th>Direction</th><th>Amount</th><th>Status</th></tr></thead><tbody>{filteredTransactions.map(t=><tr key={t.id} className="click-row" onClick={()=>setSelectedTransaction(t)}><td>{t.effective_date}</td><td><code>{t.reference}</code></td><td><strong>{t.description||t.transaction_type}</strong><small>{t.counterparty||'—'}</small></td><td><code>{shortId(t.user_id)}</code></td><td className={t.direction==='credit'?'text-credit':'text-debit'}>{t.direction}</td><td>{money(t.amount,t.currency)}</td><td><select className="admin-select status-select" value={t.status} onClick={e=>e.stopPropagation()} onChange={e=>void updateTransactionStatus(t.id,e.target.value)}>{statuses.map(([v,l])=><option key={v} value={v}>{l}</option>)}</select></td></tr>)}</tbody></table></div></Panel></>}
   {tab==='support'&&<Panel title={`${cases.length} support cases`}><div className="table-wrap"><table><thead><tr><th>Case</th><th>Subject</th><th>Priority</th><th>Status</th><th>Created</th><th>Action</th></tr></thead><tbody>{cases.map(c=><tr key={c.id}><td><code>{c.case_number}</code></td><td><strong>{c.subject}</strong><small>{shortId(c.user_id)}</small></td><td><select className="admin-select" value={c.priority} onChange={e=>void updateCase(c.id,c.status,e.target.value)}><option value="low">low</option><option value="normal">normal</option><option value="priority">priority</option><option value="urgent">urgent</option></select></td><td><select className="admin-select" value={c.status} onChange={e=>void updateCase(c.id,e.target.value)}><option value="open">open</option><option value="in_progress">in progress</option><option value="resolved">resolved</option><option value="closed">closed</option></select></td><td>{new Date(c.created_at).toLocaleDateString()}</td><td><button className="mini-action" onClick={()=>{const customer=customers.find(x=>x.id===c.user_id);if(customer)setSelectedCustomer(customer)}}>View customer</button></td></tr>)}</tbody></table></div></Panel>}
   {tab==='audit'&&<Panel title={`${audits.length} audit entries`}><div className="table-wrap"><table><thead><tr><th>Time</th><th>Action</th><th>Resource</th><th>Resource ID</th><th>Actor</th><th>Metadata</th></tr></thead><tbody>{audits.map(a=><tr key={a.id}><td>{new Date(a.created_at).toLocaleString()}</td><td><strong>{a.action}</strong></td><td>{a.resource_type}</td><td><code>{shortId(a.resource_id)}</code></td><td><code>{shortId(a.user_id)}</code></td><td><code>{JSON.stringify(a.metadata||{})}</code></td></tr>)}</tbody></table></div></Panel>}
   {selectedTransaction&&<TransactionDrawer transaction={selectedTransaction} customer={customers.find(c=>c.id===selectedTransaction.user_id)||null} onClose={()=>setSelectedTransaction(null)} onCustomer={()=>{const c=customers.find(x=>x.id===selectedTransaction.user_id);if(c)setSelectedCustomer(c);setTab('customers');setSelectedTransaction(null)}} onStatus={updateTransactionStatus}/>} {passwordCustomerId&&<PasswordRotateDialog userId={passwordCustomerId} onClose={()=>setPasswordCustomerId(null)}/>} 
  </section>
 </main>
}
function Metric({label,value}:{label:string;value:string}){return <div className="metric-card"><span>{label}</span><strong>{value}</strong></div>}
function Panel({title,children}:{title:string;children:any}){return <section className="admin-panel"><div className="panel-head"><h2>{title}</h2></div>{children}</section>}
function Toolbar({value,onChange,placeholder}:{value:string;onChange:(v:string)=>void;placeholder:string}){return <div className="admin-toolbar"><label><Search size={16}/><input value={value} onChange={e=>onChange(e.target.value)} placeholder={placeholder}/></label></div>}
function CustomerDrawer({customer,transactions,cases,onClose,onStatus,onTransaction,onRecovery}:{customer:Customer;transactions:Transaction[];cases:SupportCase[];onClose:()=>void;onStatus:(id:string,status:string)=>Promise<void>;onTransaction:(t:Transaction)=>void;onRecovery:()=>void}){return <div className="drawer-backdrop" onClick={onClose}><aside className="admin-drawer" onClick={e=>e.stopPropagation()}><div className="drawer-head"><div><div className="eyebrow">CUSTOMER RECORD</div><h2>{customer.preferred_name||customer.full_name||'Customer account'}</h2><small>{customer.email||'No email'} · {shortId(customer.id)}</small></div><button onClick={onClose} aria-label="Close">×</button></div><div className="customer-detail-grid"><div><span>Account</span><strong>{customer.account_name||'Not linked'}</strong></div><div><span>Status</span><strong>{customer.account_status||'Profile only'}</strong></div><div><span>Available</span><strong>{money(customer.available_balance)}</strong></div><div><span>Posted</span><strong>{money(customer.posted_balance)}</strong></div></div>{customer.account_id&&<div className="account-actions"><span>Account status</span><select className="admin-select" value={customer.account_status||'active'} onChange={e=>void onStatus(customer.account_id!,e.target.value)}><option value="active">active</option><option value="frozen">frozen</option><option value="pending">pending</option><option value="closed">closed</option></select></div>}<section className="access-card"><div><span className="access-kicker">ACCOUNT ACCESS</span><strong>Password & recovery</strong><small>Rotate the customer password directly from this record. The new password is shown once and never stored in the admin UI.</small></div><button className="drawer-primary compact-button" onClick={onRecovery}>Rotate password</button></section><Panel title={`Recent transactions · ${transactions.length}`}>{transactions.length?transactions.slice(0,12).map(t=><button className="drawer-row" key={t.id} onClick={()=>onTransaction(t)}><span className={t.direction==='credit'?'text-credit':'text-debit'}>{t.direction==='credit'?'+':'−'} {money(t.amount,t.currency)}</span><span><strong>{t.description||t.transaction_type}</strong><small>{t.reference} · {t.status}</small></span></button>):<div className="empty-state">No transactions recorded for this customer.</div>}</Panel><Panel title={`Support cases · ${cases.length}`}>{cases.length?cases.slice(0,8).map(c=><div className="case-row" key={c.id}><strong>{c.case_number}</strong><span>{c.subject}</span><small>{c.status} · {c.priority}</small></div>):<div className="empty-state">No support cases.</div>}</Panel></aside></div>}
function TransactionDrawer({transaction,customer,onClose,onCustomer,onStatus}:{transaction:Transaction;customer:Customer|null;onClose:()=>void;onCustomer:()=>void;onStatus:(id:string,status:string)=>Promise<void>}){return <div className="drawer-backdrop" onClick={onClose}><aside className="admin-drawer narrow" onClick={e=>e.stopPropagation()}><div className="drawer-head"><div><div className="eyebrow">TRANSACTION</div><h2>{transaction.description||transaction.transaction_type}</h2><small>{transaction.reference}</small></div><button onClick={onClose} aria-label="Close">×</button></div><div className="transaction-detail"><div><span>Customer</span><strong>{customer?.preferred_name||customer?.full_name||shortId(transaction.user_id)}</strong></div><div><span>Amount</span><strong>{money(transaction.amount,transaction.currency)}</strong></div><div><span>Direction</span><strong>{transaction.direction}</strong></div><div><span>Date</span><strong>{transaction.effective_date}</strong></div></div><label className="drawer-field">Status<select className="admin-select" value={transaction.status} onChange={e=>void onStatus(transaction.id,e.target.value)}>{statuses.map(([v,l])=><option key={v} value={v}>{l}</option>)}</select></label>{customer&&<button className="drawer-secondary" onClick={onCustomer}>Open customer record</button>}</aside></div>}
function PasswordRotateDialog({userId,onClose}:{userId:string;onClose:()=>void}){const[password,setPassword]=useState(''),[confirm,setConfirm]=useState(''),[busy,setBusy]=useState(false),[done,setDone]=useState(false),[error,setError]=useState('');const generate=()=>setPassword(Array.from(crypto.getRandomValues(new Uint32Array(18)),n=>'ABCDEFGHJKLMNPQRSTUVWXYZabcdefghijkmnopqrstuvwxyz23456789'[n%56]).join(''));const rotate=async()=>{if(password.length<10||password!==confirm){setError('Use at least 10 characters and make both passwords match.');return}setBusy(true);setError('');const r=await supabase.functions.invoke('admin-rotate-customer-password',{body:{user_id:userId,new_password:password}});if(r.error||r.data?.ok!==true)setError(r.error?.message||r.data?.message||'Password rotation failed');else setDone(true);setBusy(false)};return <div className="dialog-backdrop"><div className="admin-dialog"><div className="drawer-head"><div><div className="eyebrow">ACCOUNT ACCESS</div><h2>Rotate customer password</h2></div><button onClick={onClose}>×</button></div>{done?<><div className="success-state"><strong>Password rotated</strong><p>The new password was applied successfully. It is not stored in the admin interface.</p><code>{password}</code></div><button className="drawer-primary" onClick={onClose}>Done</button></>:<><p className="dialog-copy">Set a new temporary password for this customer. Do not share passwords through ordinary messages.</p><label className="drawer-field">New password<input type="password" value={password} onChange={e=>setPassword(e.target.value)} autoComplete="new-password"/></label><label className="drawer-field">Confirm password<input type="password" value={confirm} onChange={e=>setConfirm(e.target.value)} autoComplete="new-password"/></label><button className="drawer-secondary" onClick={generate}>Generate secure password</button>{error&&<div className="admin-error">{error}</div>}<button className="drawer-primary" onClick={()=>void rotate()} disabled={busy}>{busy?'Rotating…':'Rotate password'}</button></>}</div></div>}
