import { useEffect, useMemo, useState } from 'react'
import { Activity, ArrowDownToLine, ArrowUpRight, CheckCircle2, CreditCard, FileText, LockKeyhole, MessageSquare, RefreshCw, Search, ShieldCheck, UserRound, Users } from 'lucide-react'
import { useNavigate } from 'react-router-dom'
import { supabase } from './supabaseClient'
import './admin.css'

type Customer={id:string;email:string|null;full_name:string|null;preferred_name:string|null;account_id:string|null;account_name:string|null;available_balance:number|null;posted_balance:number|null;pending_balance:number|null;account_status:string|null}
type Transaction={id:string;user_id:string;reference:string;amount:number;currency:string;direction:string;status:string;description:string|null;effective_date:string}
type Audit={id:string;action:string;resource_type:string;resource_id:string;created_at:string}
const money=(v:number|null|undefined)=>new Intl.NumberFormat('en-US',{style:'currency',currency:'USD'}).format(Number(v||0))
const nameOf=(c:Customer)=>c.preferred_name||c.full_name||c.email||'Customer account'
const idShort=(v:string)=>v?`${v.slice(0,8)}…${v.slice(-4)}`:'—'

export default function AdminOperationsPage(){
 const navigate=useNavigate();
 const[customers,setCustomers]=useState<Customer[]>([]);const[transactions,setTransactions]=useState<Transaction[]>([]);const[audits,setAudits]=useState<Audit[]>([]);const[query,setQuery]=useState('');const[loading,setLoading]=useState(true);const[error,setError]=useState('');const[busyId,setBusyId]=useState<string|null>(null)
 const load=async()=>{setLoading(true);setError('');const admin=await supabase.rpc('is_admin');if(admin.error||!admin.data){setError(admin.error?.message||'Admin access required');setLoading(false);return}const[c,t,a]=await Promise.all([supabase.rpc('admin_list_customers'),supabase.from('transactions').select('id,user_id,reference,amount,currency,direction,status,description,effective_date').order('effective_date',{ascending:false}).limit(20),supabase.rpc('admin_get_audit_logs',{p_limit:10})]);const first=[c,t,a].find(x=>x.error)?.error;if(first)setError(first.message);setCustomers((c.data||[]) as Customer[]);setTransactions((t.data||[]) as Transaction[]);setAudits((a.data||[]) as Audit[]);setLoading(false)}
 useEffect(()=>{void load()},[])
 const filtered=useMemo(()=>{const q=query.trim().toLowerCase();if(!q)return customers;return customers.filter(c=>`${nameOf(c)} ${c.email||''} ${c.id} ${c.account_name||''} ${c.account_id||''}`.toLowerCase().includes(q))},[customers,query])
 const total=customers.reduce((n,c)=>n+Number(c.available_balance||0),0);const pending=customers.reduce((n,c)=>n+Number(c.pending_balance||0),0);const active=customers.filter(c=>c.account_status==='active').length
 const setStatus=async(id:string,status:string)=>{setBusyId(id);setError('');const r=await supabase.rpc('admin_set_account_status',{p_account_id:id,p_status:status});if(r.error)setError(r.error.message);else await load();setBusyId(null)}
 return <main className="admin-shell"><aside className="admin-sidebar"><div className="admin-brand"><span>F</span><div><strong>FNCU</strong><small>OPERATIONS</small></div></div><nav className="admin-nav"><div className="nav-label">OPERATIONS</div><button className="active"><Activity size={16}/> Operations</button><button onClick={()=>navigate('/admin/credits')}><ArrowUpRight size={16}/> Credit account</button><button onClick={()=>navigate('/admin/deposits')}><ArrowDownToLine size={16}/> Check deposits</button><button onClick={()=>navigate('/admin/transfer-notifications')}><ShieldCheck size={16}/> Transfer review</button><div className="nav-label nav-label-spaced">CUSTOMER SERVICE</div><button onClick={()=>navigate('/admin/recovery')}><LockKeyhole size={16}/> Account recovery</button><button onClick={()=>navigate('/admin?view=support-chat')}><MessageSquare size={16}/> Service chat</button></nav><button className="back-bank" onClick={()=>navigate('/')}>← Banking interface</button></aside><section className="admin-main"><header className="admin-header"><div><div className="eyebrow">OPERATIONS CONSOLE</div><h1>Customer & account operations</h1><p className="admin-header-subtitle">Work directly against customer records, account status, transaction activity and servicing workflows.</p></div><button className="refresh" onClick={()=>void load()} disabled={loading}><RefreshCw size={15}/>{loading?'Refreshing…':'Refresh'}</button></header>{error&&<div className="admin-error" role="alert">{error}</div>}
 <div className="metric-grid"><div className="metric-card"><span>Customer accounts</span><strong>{customers.length}</strong></div><div className="metric-card"><span>Active accounts</span><strong>{active}</strong></div><div className="metric-card"><span>Available funds</span><strong>{money(total)}</strong></div><div className="metric-card"><span>Pending funds</span><strong>{money(pending)}</strong></div></div>
 <section className="admin-panel"><div className="panel-head"><div><h2>Account servicing</h2><p className="admin-header-subtitle">These actions invoke the connected account operations; they are not display-only controls.</p></div></div><div className="admin-action-grid"><button className="admin-operation-card" onClick={()=>navigate('/admin/credits')}><CreditCard size={20}/><strong>Credit an account</strong><span>Post a controlled USD credit through the persistent ledger.</span></button><button className="admin-operation-card" onClick={()=>navigate('/admin/deposits')}><ArrowDownToLine size={20}/><strong>Review check deposits</strong><span>Inspect submitted deposits before funds are made available.</span></button><button className="admin-operation-card" onClick={()=>navigate('/admin/transfer-notifications')}><ShieldCheck size={20}/><strong>Review transfers</strong><span>Open the existing transfer authorization and notification workflow.</span></button><button className="admin-operation-card" onClick={()=>navigate('/admin/recovery')}><LockKeyhole size={20}/><strong>Account recovery</strong><span>Use the existing controlled customer-access recovery flow.</span></button><button className="admin-operation-card" onClick={()=>navigate('/admin?view=support-chat')}><MessageSquare size={20}/><strong>Customer service</strong><span>Open the operational customer-service conversation interface.</span></button></div></section>
 <div className="admin-grid"><section className="admin-panel"><div className="panel-head"><div><h2>Customer accounts</h2><p className="admin-header-subtitle">Search and service a real customer record.</p></div></div><div className="admin-toolbar"><label><Search size={16}/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search name, email, account or customer ID…"/></label></div><div className="table-wrap"><table><thead><tr><th>Customer</th><th>Account</th><th>Available</th><th>Status</th><th>Actions</th></tr></thead><tbody>{filtered.map(c=><tr key={c.id}><td><strong>{nameOf(c)}</strong><small>{c.email||idShort(c.id)}</small></td><td>{c.account_name||'—'}<small>{c.account_id?idShort(c.account_id):'No linked account'}</small></td><td><strong>{money(c.available_balance)}</strong><small>Posted {money(c.posted_balance)}</small></td><td><select className="admin-select" disabled={!c.account_id||busyId===c.account_id} value={c.account_status||'active'} onChange={e=>void setStatus(c.account_id!,e.target.value)}><option value="active">Active</option><option value="restricted">Restricted</option><option value="frozen">Frozen</option><option value="closed">Closed</option></select></td><td><div className="admin-row-actions"><button className="mini-action" onClick={()=>navigate('/admin/credits')}>Credit</button><button className="mini-action" disabled={!c.account_id} onClick={()=>c.account_id&&void setStatus(c.account_id,c.account_status==='frozen'?'active':'frozen')}>{c.account_status==='frozen'?'Unfreeze':'Freeze'}</button></div></td></tr>)}</tbody></table>{!loading&&!filtered.length&&<div className="empty-state">No customer accounts match this search.</div>}</div></section>
 <section className="admin-panel"><div className="panel-head"><div><h2>Recent activity</h2><p className="admin-header-subtitle">Latest persisted transaction records.</p></div></div><div className="activity-list">{transactions.map(t=><div className="activity" key={t.id}><span className={t.direction==='credit'?'credit':'debit'}>{t.direction==='credit'?'+':'−'}</span><div><strong>{t.description||'Account transaction'}</strong><small>{t.reference} · {t.status} · {t.effective_date}</small></div><b>{money(t.amount,t.currency)}</b></div>)}{!transactions.length&&<div className="empty-state">No recent transactions.</div>}</div><div className="panel-head" style={{marginTop:24}}><div><h2>Audit trail</h2><p className="admin-header-subtitle">Recent recorded administrative actions.</p></div></div><div className="activity-list">{audits.map(a=><div className="activity" key={a.id}><FileText size={17}/><div><strong>{a.action}</strong><small>{a.resource_type} · {idShort(a.resource_id)}</small></div><b>{new Date(a.created_at).toLocaleDateString()}</b></div>)}</div></section></div>
 </section></main>
}
