import { useEffect, useState } from 'react'
import { RefreshCw, X } from 'lucide-react'
import { supabase } from './supabaseClient'
import AdminNavigation from './AdminNavigation'
import './admin.css'

type Deposit={id:string;user_id:string;account_id:string;amount:number;front_document_path:string|null;back_document_path:string|null;status:string;funds_available_at:string|null;reference:string|null;created_at:string}
const money=(n:number)=>new Intl.NumberFormat('en-US',{style:'currency',currency:'USD'}).format(Number(n||0))
export default function AdminDepositQueuePage(){
 const[rows,setRows]=useState<Deposit[]>([]);const[busy,setBusy]=useState(false);const[error,setError]=useState('');const[selected,setSelected]=useState<Deposit|null>(null)
 const load=async()=>{setBusy(true);setError('');const{data,error:e}=await supabase.from('check_deposits').select('id,user_id,account_id,amount,front_document_path,back_document_path,status,funds_available_at,reference,created_at').order('created_at',{ascending:false});if(e)setError(e.message);setRows((data||[]) as Deposit[]);setBusy(false)}
 useEffect(()=>{void load()},[])
 return <main className="admin-shell"><AdminNavigation/><section className="admin-main"><header className="admin-header"><div><div className="eyebrow">DEPOSIT OPERATIONS</div><h1>Check deposits</h1><p>Review customer-submitted deposit requests before funds become available.</p></div><button className="refresh" onClick={()=>void load()} disabled={busy}><RefreshCw size={15}/> {busy?'Refreshing…':'Refresh'}</button></header>{error&&<div className="admin-error">{error}</div>}<div className="admin-notice"><strong>REMOTE CHECK DEPOSIT</strong><span>Each submission includes a front image and a back image stored in the protected customer-documents bucket.</span></div><section className="admin-panel"><div className="table-wrap"><table><thead><tr><th>Submitted</th><th>Amount</th><th>Reference</th><th>Status</th><th>Customer</th></tr></thead><tbody>{rows.map(row=><tr key={row.id} className="click-row" onClick={()=>setSelected(row)}><td>{new Date(row.created_at).toLocaleString()}</td><td><strong>{money(row.amount)}</strong></td><td><code>{row.reference||'—'}</code></td><td><span className={`status ${row.status}`}>{row.status}</span></td><td><code>{row.user_id.slice(0,8)}…</code></td></tr>)}</tbody></table>{!rows.length&&<div className="empty-state">No check deposits have been submitted.</div>}</div></section>{selected&&<div className="drawer-backdrop" onClick={()=>setSelected(null)}><aside className="admin-drawer compact" onClick={e=>e.stopPropagation()}><div className="drawer-head"><div><div className="eyebrow">CHECK DEPOSIT REVIEW</div><h2>{money(selected.amount)}</h2><small>{selected.reference||'No reference'} · {selected.status}</small></div><button onClick={()=>setSelected(null)}><X size={18}/></button></div><div className="transaction-detail"><Row label="Customer" value={selected.user_id}/><Row label="Account" value={selected.account_id}/><Row label="Submitted" value={new Date(selected.created_at).toLocaleString()}/><Row label="Status" value={selected.status}/><Row label="Front image" value={selected.front_document_path?'Uploaded':'Missing'}/><Row label="Back image" value={selected.back_document_path?'Uploaded':'Missing'}/><Row label="Funds available" value={selected.funds_available_at||'Pending review'}/></div><div className="demo-lock"><strong>REVIEW REQUIRED</strong><span>The deposit request is visible here for operations review. It is not automatically credited from the customer upload.</span></div></aside></div>}</section></main>
}
function Row({label,value}:{label:string;value:string}){return <div className="detail-row"><span>{label}</span><b>{value}</b></div>}
