import { useCallback, useEffect, useMemo, useState } from 'react'
import { Bell, RefreshCw, ShieldCheck } from 'lucide-react'
import { supabase } from './supabaseClient'
import AdminNavigation from './AdminNavigation'
import './admin.css'
import './admin-polish.css'

type Row={id:string;user_id:string;movement_id:string;token_value:string;status:string;expires_at:string;verified_at:string|null;attempts:number;delivery_status:string;created_at:string;customer_name:string;reference:string;rail:string;amount:number;fee:number;currency:string;destination:string|null;destination_account:string|null}
const money=(n:number,c='USD')=>new Intl.NumberFormat('en-US',{style:'currency',currency:c,maximumFractionDigits:2}).format(Number(n||0))
const remaining=(iso:string)=>Math.max(0,Math.floor((new Date(iso).getTime()-Date.now())/1000))
const clock=(s:number)=>`${Math.floor(s/60).toString().padStart(2,'0')}:${(s%60).toString().padStart(2,'0')}`
export default function AdminTransferNotificationsPage(){
 const[rows,setRows]=useState<Row[]>([]);const[loading,setLoading]=useState(true);const[error,setError]=useState('');const[now,setNow]=useState(Date.now())
 const load=useCallback(async()=>{setLoading(true);setError('');const{data,error:e}=await supabase.functions.invoke('transfer-security',{body:{action:'admin_list'}});if(e)setError(e.message||'Unable to load transfer authorization messages.');else setRows((data?.rows||[])as Row[]);setLoading(false)},[])
 useEffect(()=>{void load();const poll=setInterval(()=>void load(),5000);const tick=setInterval(()=>setNow(Date.now()),1000);return()=>{clearInterval(poll);clearInterval(tick)}},[load])
 const active=useMemo(()=>rows.filter(r=>r.status==='pending'&&new Date(r.expires_at).getTime()>now),[rows,now])
 return <main className="admin-shell"><AdminNavigation/><section className="admin-main"><header className="admin-header"><div><div className="eyebrow">TRANSFER OPERATIONS</div><h1>Transfer authorization inbox</h1><p className="admin-header-subtitle">Secure administrator message box for transfer authorization tokens. Customer email delivery is not used.</p></div><button className="refresh" onClick={()=>void load()} disabled={loading}><RefreshCw size={14}/>{loading?'Refreshing…':'Refresh inbox'}</button></header>{error&&<div className="admin-error">{error}</div>}<section className="admin-panel" style={{marginBottom:16}}><div className="panel-head"><div><h2><Bell size={17} style={{verticalAlign:'-3px',marginRight:8}}/>Live transfer token messages</h2><p style={{margin:'6px 0 0',color:'var(--admin-muted,#667085)'}}>{active.length} active token{active.length===1?'':'s'} · refreshes automatically</p></div></div><div className="table-wrap"><table><thead><tr><th>Customer</th><th>Transaction</th><th>Amount</th><th>Authorization token</th><th>Expires</th><th>Status</th></tr></thead><tbody>{rows.map(r=>{const secs=remaining(r.expires_at);const live=r.status==='pending'&&secs>0;return <tr key={r.id} style={{opacity:live?1:.55}}><td><strong>{r.customer_name}</strong><small>{r.user_id.slice(0,8)}…</small></td><td><strong>{r.reference}</strong><small>{r.rail.toUpperCase()} · {r.destination||'—'}</small></td><td>{money(Number(r.amount||0),r.currency)}</td><td><code style={{fontSize:18,letterSpacing:4,fontWeight:800}}>{live?r.token_value:'••••••••'}</code></td><td><strong>{live?clock(secs):'Expired'}</strong><small>{new Date(r.expires_at).toLocaleTimeString()}</small></td><td>{r.status}</td></tr>})}</tbody></table></div>{!rows.length&&!loading&&<div style={{padding:32,textAlign:'center',color:'var(--admin-muted,#667085)'}}>No transfer authorization messages yet.</div>}</section><div className="admin-grid"><section className="admin-panel"><div className="panel-head"><h2>Authorization controls</h2></div><div style={{padding:20,display:'flex',gap:12,alignItems:'flex-start'}}><ShieldCheck size={22}/><div><strong>5-minute token window</strong><p style={{margin:'6px 0',color:'var(--admin-muted,#667085)'}}>Each new token replaces the previous pending token for the same transaction. Expired tokens are rejected server-side.</p></div></div></section><section className="admin-panel"><div className="panel-head"><h2>Inbox behavior</h2></div><div style={{padding:20,color:'var(--admin-muted,#667085)'}}>The administrator inbox polls every 5 seconds. Transfer authorization tokens are read from the protected transfer authorization store; they are not sent to the customer's email.</div></section></div></section></main>
}
