import { useEffect, useMemo, useState, type ReactNode } from 'react'
import { useLocation, useNavigate } from 'react-router-dom'
import { supabase } from './supabaseClient'
import AdminSupportChatPage from './AdminSupportChatPage'
import './admin.css'

type Profile={id:string;full_name:string|null;preferred_name?:string|null;tier:string|null;country:string|null;customer_since:string|null;created_at:string}
type Account={id:string;user_id:string;account_name:string;account_number_last4:string|null;available_balance:number;posted_balance:number;pending_balance:number;status:string}
type Transaction={id:string;user_id:string;reference:string;transaction_type:string;direction:string;amount:number;currency:string;status:string;counterparty:string|null;description:string|null;effective_date:string;fee:number}
type SupportCase={id:string;user_id:string;case_number:string;subject:string;status:string;priority:string;created_at:string}
type AuditLog={id:string;user_id:string;action:string;resource_type:string;resource_id:string;metadata:any;created_at:string}

const money=(v:number,c='USD')=>new Intl.NumberFormat('en-US',{style:'currency',currency:c,maximumFractionDigits:2}).format(Number(v||0))
const shortId=(id:string)=>id?`${id.slice(0,8)}…${id.slice(-4)}`:'—'
const transactionStatuses=[['pending','Pending'],['processing','Processing'],['completed','Successful'],['failed','Failed'],['reversed','Reversed'],['cancelled','Cancelled']] as const

export default function AdminPage(){
 const navigate=useNavigate();const location=useLocation()
 if(new URLSearchParams(location.search).get('view')==='support-chat')return <AdminSupportChatPage/>
 const[checking,setChecking]=useState(true);const[allowed,setAllowed]=useState(false);const[tab,setTab]=useState<'overview'|'customers'|'transactions'|'support'|'audit'>('overview')
 const[profiles,setProfiles]=useState<Profile[]>([]);const[accounts,setAccounts]=useState<Account[]>([]);const[transactions,setTransactions]=useState<Transaction[]>([]);const[cases,setCases]=useState<SupportCase[]>([]);const[audits,setAudits]=useState<AuditLog[]>([])
 const[query,setQuery]=useState('');const[loading,setLoading]=useState(false);const[error,setError]=useState('');const[selectedCustomer,setSelectedCustomer]=useState<string|null>(null);const[selectedTransaction,setSelectedTransaction]=useState<Transaction|null>(null)
 const load=async()=>{setLoading(true);setError('');const admin=await supabase.rpc('is_admin');if(admin.error){setError(admin.error.message);setLoading(false);return}if(!admin.data){setAllowed(false);setLoading(false);return}setAllowed(true);const[p,a,t,s,al]=await Promise.all([supabase.from('profiles').select('id,full_name,preferred_name,tier,country,customer_since,created_at').order('created_at',{ascending:false}),supabase.from('accounts').select('id,user_id,account_name,account_number_last4,available_balance,posted_balance,pending_balance,status').order('created_at',{ascending:false}),supabase.from('transactions').select('id,user_id,reference,transaction_type,direction,amount,currency,status,counterparty,description,effective_date,fee').order('effective_date',{ascending:false}).order('created_at',{ascending:false}).limit(500),supabase.from('support_cases').select('id,user_id,case_number,subject,status,priority,created_at').order('created_at',{ascending:false}).limit(200),supabase.rpc('admin_get_audit_logs',{p_limit:200})]);const first=[p,a,t,s,al].find(r=>r.error)?.error;if(first)setError(first.message);setProfiles((p.data||[])as Profile[]);setAccounts((a.data||[])as Account[]);setTransactions((t.data||[])as Transaction[]);setCases((s.data||[])as SupportCase[]);setAudits((al.data||[])as AuditLog[]);setLoading(false)}
 useEffect(()=>{let active=true;(async()=>{const session=await supabase.auth.getSession();if(!active)return;if(!session.data.session){navigate('/admin',{replace:true});return}setChecking(false);await load()})();return()=>{active=false}},[])
 const filteredProfiles=useMemo(()=>{const q=query.trim().toLowerCase();return q?profiles.filter(p=>`${p.full_name||''} ${p.preferred_name||''} ${p.country||''} ${p.id}`.toLowerCase().includes(q)):profiles},[profiles,query])
 const filteredTransactions=useMemo(()=>{const q=query.trim().toLowerCase();return q?transactions.filter(t=>`${t.reference} ${t.counterparty||''} ${t.description||''} ${t.transaction_type} ${t.user_id}`.toLowerCase().includes(q)):transactions},[transactions,query])
 const totals=useMemo(()=>({customers:profiles.length,accounts:accounts.length,balances:accounts.reduce((n,a)=>n+Number(a.available_balance||0),0),pending:accounts.reduce((n,a)=>n+Number(a.pending_balance||0),0),transactions:transactions.length,openCases:cases.filter(c=>c.status==='open').length}),[profiles,accounts,transactions,cases])
 const customer=selectedCustomer?profiles.find(p=>p.id===selectedCustomer)||null:null;const customerAccount=selectedCustomer?accounts.find(a=>a.user_id===selectedCustomer)||null:null;const customerTx=selectedCustomer?transactions.filter(t=>t.user_id===selectedCustomer):[];const customerCases=selectedCustomer?cases.filter(c=>c.user_id===selectedCustomer):[]
 const updateCase=async(id:string,status:string,priority?:string)=>{const result=await supabase.rpc('admin_update_support_case',{p_case_id:id,p_status:status,p_priority:priority||null});if(result.error){setError(result.error.message);return}await load()}
 const updateAccountStatus=async(accountId:string,status:string)=>{const result=await supabase.rpc('admin_set_account_status',{p_account_id:accountId,p_status:status});if(result.error){setError(result.error.message);return}await load()}
 const updateTransactionStatus=async(id:string,status:string)=>{const result=await supabase.rpc('admin_set_transaction_status',{p_transaction_id:id,p_status:status});if(result.error){setError(result.error.message);return}await load()}
 if(checking)return <main className="admin-loading">Loading admin console…</main>
 if(!allowed)return <main className="admin-denied"><div><div className="admin-lock">FNCU</div><h1>Admin access required</h1><p>This area is restricted to authorized administrators.</p><button onClick={()=>navigate('/')}>Return to banking</button></div></main>
 const switchTab=(next:'overview'|'customers'|'transactions'|'support'|'audit')=>{setTab(next);setQuery('');setSelectedCustomer(null);setSelectedTransaction(null)}
 return <main className="admin-shell">
  <aside className="admin-sidebar"><div className="admin-brand"><span>F</span><div><strong>FNCU</strong><small>ADMINISTRATION</small></div></div><nav className="admin-nav"><div className="nav-label">WORKSPACE</div>{(['overview','customers','transactions','support','audit'] as const).map(item=><button key={item} className={tab===item?'active':''} onClick={()=>switchTab(item)}>{item==='overview'?'Overview':item==='customers'?'Customers':item==='transactions'?'Transactions':item==='support'?'Support':'Audit log'}</button>)}<div className="nav-label nav-label-spaced">ACCESS</div><button onClick={()=>navigate('/admin/recovery')}>Account recovery</button><button onClick={()=>window.location.assign('/admin?view=support-chat')}>Customer service chat</button></nav><button className="back-bank" onClick={()=>navigate('/')}>← Banking interface</button></aside>
  <section className="admin-main"><header className="admin-header"><div><div className="eyebrow">FNCU ADMINISTRATION</div><h1>{tab==='overview'?'Operations overview':tab==='customers'?'Customer directory':tab==='transactions'?'Transaction monitor':tab==='support'?'Support queue':'Audit log'}</h1><p className="admin-header-subtitle">Customer operations, account servicing, transaction review and support.</p></div><div className="header-actions"><button className="refresh" onClick={load} disabled={loading}>{loading?'Refreshing…':'Refresh data'}</button></div></header>{error&&<div className="admin-error" role="alert">{error}</div>}
   {tab==='overview'&&<><div className="metric-grid"><Metric label="Customers" value={String(totals.customers)}/><Metric label="Accounts" value={String(totals.accounts)}/><Metric label="Available balance" value={money(totals.balances)}/><Metric label="Pending" value={money(totals.pending)}/><Metric label="Transactions loaded" value={String(totals.transactions)}/><Metric label="Open support cases" value={String(totals.openCases)}/></div><div className="admin-grid"><Panel title="Recent customers"><div className="table-wrap"><table><thead><tr><th>Customer</th><th>Tier</th><th>Country</th><th>Since</th></tr></thead><tbody>{profiles.slice(0,8).map(p=><tr key={p.id} className="click-row" onClick={()=>{setTab('customers');setSelectedCustomer(p.id)}}><td><strong>{p.preferred_name||p.full_name||'Unnamed customer'}</strong><small>{shortId(p.id)}</small></td><td>{p.tier||'—'}</td><td>{p.country||'—'}</td><td>{p.customer_since||'—'}</td></tr>)}</tbody></table></div></Panel><Panel title="Latest activity"><div className="activity-list">{transactions.slice(0,8).map(t=><button className="activity activity-button" key={t.id} onClick={()=>setSelectedTransaction(t)}><span className={t.direction==='credit'?'credit':'debit'}>{t.direction==='credit'?'+':'−'}</span><div><strong>{t.description||t.transaction_type}</strong><small>{t.reference} · {t.effective_date}</small></div><b>{money(t.amount,t.currency)}</b></button>)}</div></Panel></div></>}
   {tab==='customers'&&<><Toolbar value={query} onChange={setQuery} placeholder="Search customers by name, country or ID…"/><Panel title={`${filteredProfiles.length} customers`}><div className="table-wrap"><table><thead><tr><th>Customer</th><th>Tier</th><th>Country</th><th>Customer since</th><th>ID</th></tr></thead><tbody>{filteredProfiles.map(p=><tr key={p.id} className="click-row" onClick={()=>setSelectedCustomer(p.id)}><td><strong>{p.preferred_name||p.full_name||'Unnamed'}</strong></td><td>{p.tier||'—'}</td><td>{p.country||'—'}</td><td>{p.customer_since||'—'}</td><td><code>{shortId(p.id)}</code></td></tr>)}</tbody></table></div></Panel>{customer&&<CustomerDrawer profile={customer} account={customerAccount} transactions={customerTx} cases={customerCases} onClose={()=>setSelectedCustomer(null)} onTransaction={setSelectedTransaction} onStatus={updateAccountStatus} onTransactionStatus={updateTransactionStatus} onRecovery={()=>navigate(`/admin/recovery?user_id=${encodeURIComponent(customer.id)}`)}/>}</>}
   {tab==='transactions'&&<><Toolbar value={query} onChange={setQuery} placeholder="Search reference, merchant, description or customer ID…"/><Panel title={`${filteredTransactions.length} transactions`}><div className="table-wrap"><table><thead><tr><th>Date</th><th>Reference</th><th>Description</th><th>Customer</th><th>Direction</th><th>Amount</th><th>Status</th></tr></thead><tbody>{filteredTransactions.map(t=><tr key={t.id} className="click-row" onClick={()=>setSelectedTransaction(t)}><td>{t.effective_date}</td><td><code>{t.reference}</code></td><td><strong>{t.description||t.transaction_type}</strong><small>{t.counterparty||'—'}</small></td><td><code>{shortId(t.user_id)}</code></td><td className={t.direction==='credit'?'text-credit':'text-debit'}>{t.direction}</td><td>{money(t.amount,t.currency)}</td><td><select className="admin-select status-select" value={t.status} onClick={e=>e.stopPropagation()} onChange={e=>void updateTransactionStatus(t.id,e.target.value)}>{transactionStatuses.map(([value,label])=><option key={value} value={value}>{label}</option>)}</select></td></tr>)}</tbody></table></div></Panel></>}
   {tab==='support'&&<Panel title={`${cases.length} support cases`}><div className="table-wrap"><table><thead><tr><th>Case</th><th>Subject</th><th>Priority</th><th>Status</th><th>Created</th><th>Action</th></tr></thead><tbody>{cases.map(c=><tr key={c.id}><td><code>{c.case_number}</code></td><td><strong>{c.subject}</strong><small>{shortId(c.user_id)}</small></td><td><select className="admin-select" value={c.priority} onChange={e=>void updateCase(c.id,c.status,e.target.value)}><option value="low">low</option><option value="normal">normal</option><option value="priority">priority</option><option value="urgent">urgent</option></select></td><td><select className="admin-select" value={c.status} onChange={e=>void updateCase(c.id,e.target.value)}><option value="open">open</option><option value="in_progress">in progress</option><option value="resolved">resolved</option><option value="closed">closed</option></select></td><td>{new Date(c.created_at).toLocaleDateString()}</td><td><button className="mini-action" onClick={()=>{setTab('customers');setSelectedCustomer(c.user_id)}}>View customer</button></td></tr>)}</tbody></table></div></Panel>}
   {tab==='audit'&&<Panel title={`${audits.length} audit entries`}><div className="table-wrap"><table><thead><tr><th>Time</th><th>Action</th><th>Resource</th><th>Resource ID</th><th>Actor</th><th>Metadata</th></tr></thead><tbody>{audits.map(a=><tr key={a.id}><td>{new Date(a.created_at).toLocaleString()}</td><td><strong>{a.action}</strong></td><td>{a.resource_type}</td><td><code>{shortId(a.resource_id)}</code></td><td><code>{shortId(a.user_id)}</code></td><td><code>{JSON.stringify(a.metadata||{})}</code></td></tr>)}</tbody></table></div></Panel>}
   {selectedTransaction&&<TransactionDrawer transaction={selectedTransaction} profile={profiles.find(p=>p.id===selectedTransaction.user_id)||null} onClose={()=>setSelectedTransaction(null)} onCustomer={()=>{setSelectedCustomer(selectedTransaction.user_id);setTab('customers');setSelectedTransaction(null)}} onStatus={updateTransactionStatus}/>} 
  </section>
 </main>
}

function CustomerDrawer({profile,account,transactions,cases,onClose,onTransaction,onStatus,onTransactionStatus,onRecovery}:{profile:Profile;account:Account|null;transactions:Transaction[];cases:SupportCase[];onClose:()=>void;onTransaction:(t:Transaction)=>void;onStatus:(accountId:string,status:string)=>Promise<void>;onTransactionStatus:(id:string,status:string)=>Promise<void>;onRecovery:()=>void}){
 return <div className="drawer-backdrop" onClick={onClose}><aside className="admin-drawer" onClick={e=>e.stopPropagation()}><div className="drawer-head"><div><div className="eyebrow">CUSTOMER RECORD</div><h2>{profile.preferred_name||profile.full_name||'Unnamed customer'}</h2><small>{profile.country||'—'} · {profile.tier||'—'} · {shortId(profile.id)}</small></div><button onClick={onClose} aria-label="Close customer record">×</button></div>
  {account&&<><div className="account-summary"><div><span>Available</span><strong>{money(account.available_balance)}</strong></div><div><span>Posted</span><strong>{money(account.posted_balance)}</strong></div><div><span>Pending</span><strong>{money(account.pending_balance)}</strong></div><small>{account.account_name} · •••• {account.account_number_last4||'—'} · {account.status}</small></div><div className="account-actions"><span>Account status</span><select className="admin-select" value={account.status} onChange={e=>void onStatus(account.id,e.target.value)}><option value="active">active</option><option value="frozen">frozen</option><option value="pending">pending</option><option value="closed">closed</option></select></div></>}
  <section className="access-card"><div><span className="access-kicker">ACCOUNT ACCESS</span><strong>Password & recovery</strong><small>Rotate the customer password directly from this record. The new password is shown once.</small></div><button className="drawer-primary compact-button" onClick={onRecovery}>Manage access</button></section>
  <Panel title={`Recent transactions · ${transactions.length}`}>{transactions.length?transactions.slice(0,10).map(t=><button className="drawer-row" key={t.id} onClick={()=>onTransaction(t)}><span className={t.direction==='credit'?'text-credit':'text-debit'}>{t.direction==='credit'?'+':'−'}</span><div><strong>{t.description||t.transaction_type}</strong><small>{t.reference} · {t.effective_date}</small></div><div className="drawer-row-end"><span className={`status ${t.status}`}>{statusLabel(t.status)}</span><b>{money(t.amount,t.currency)}</b></div></button>):<div className="empty-state">No transactions for this customer.</div>}</Panel>
  <Panel title={`Support cases · ${cases.length}`}>{cases.length?cases.map(c=><div className="drawer-case" key={c.id}><code>{c.case_number}</code><strong>{c.subject}</strong><small>{c.status} · {c.priority}</small></div>):<div className="empty-state">No support cases.</div>}</Panel>
  {transactions.slice(0,10).map(t=>null)}
 </aside></div>
}

function TransactionDrawer({transaction,profile,onClose,onCustomer,onStatus}:{transaction:Transaction;profile:Profile|null;onClose:()=>void;onCustomer:()=>void;onStatus:(id:string,status:string)=>Promise<void>}){
 const[busy,setBusy]=useState(false)
 const change=async(status:string)=>{setBusy(true);await onStatus(transaction.id,status);setBusy(false)}
 return <div className="drawer-backdrop" onClick={onClose}><aside className="admin-drawer compact" onClick={e=>e.stopPropagation()}><div className="drawer-head"><div><div className="eyebrow">TRANSACTION DETAILS</div><h2>{transaction.description||transaction.transaction_type}</h2><small>{transaction.reference}</small></div><button onClick={onClose} aria-label="Close transaction">×</button></div><div className="transaction-detail"><Row label="Amount" value={money(transaction.amount,transaction.currency)}/><Row label="Direction" value={transaction.direction}/><Row label="Effective date" value={transaction.effective_date}/><Row label="Counterparty" value={transaction.counterparty||'—'}/><Row label="Fee" value={money(transaction.fee,transaction.currency)}/><Row label="Customer" value={profile?(profile.preferred_name||profile.full_name||shortId(profile.id)):shortId(transaction.user_id)}/></div><div className="transaction-control"><div><span>Transaction status</span><small>Change the operational state of this individual transaction.</small></div><select className="admin-select" disabled={busy} value={transaction.status} onChange={e=>void change(e.target.value)}>{transactionStatuses.map(([value,label])=><option key={value} value={value}>{label}</option>)}</select></div><button className="drawer-primary" onClick={onCustomer}>Open customer record</button></aside></div>
}

function PasswordRotateDialog({userId,onClose}:{userId:string;onClose:()=>void}){
 const[password,setPassword]=useState(generatePassword());const[show,setShow]=useState(false);const[busy,setBusy]=useState(false);const[done,setDone]=useState(false);const[error,setError]=useState('');
 const rotate=async()=>{if(password.length<10){setError('Use at least 10 characters.');return}setBusy(true);setError('');const{error}=await supabase.functions.invoke('admin-rotate-customer-password',{body:{user_id:userId,new_password:password}});if(error){setError(error.message||'Password rotation failed.');setBusy(false);return}setDone(true);setBusy(false)}
 return <div className="modal-backdrop" onClick={onClose}><section className="password-modal" onClick={e=>e.stopPropagation()}><div className="modal-head"><div><div className="eyebrow">ACCOUNT ACCESS</div><h2>{done?'Password rotated':'Rotate customer password'}</h2></div><button onClick={onClose} aria-label="Close">×</button></div>{done?<><div className="success-box"><strong>Password updated successfully.</strong><span>This temporary password is shown once. Copy it before closing.</span></div><div className="credential-box"><code>{password}</code><button onClick={()=>void navigator.clipboard?.writeText(password)}>Copy password</button></div><p className="security-note">Do not place the password in audit notes or customer-facing messages. Share it through your approved secure channel.</p><button className="drawer-primary" onClick={onClose}>Done</button></>:<><label className="field-label">New temporary password<input className="password-input" type={show?'text':'password'} value={password} onChange={e=>setPassword(e.target.value)} autoComplete="new-password"/></label><div className="password-actions"><button className="mini-action" onClick={()=>setPassword(generatePassword())}>Generate secure password</button><button className="mini-action" onClick={()=>setShow(v=>!v)}>{show?'Hide':'Show'} password</button></div><p className="security-note">Minimum 10 characters. Rotating the password changes the customer's authentication credential; it does not change account balances or transaction data.</p>{error&&<div className="admin-error">{error}</div>}<div className="modal-actions"><button className="mini-action" onClick={onClose} disabled={busy}>Cancel</button><button className="drawer-primary modal-primary" onClick={()=>void rotate()} disabled={busy}>{busy?'Updating…':'Rotate password'}</button></div></>}</section></div>
}

function generatePassword(){const chars='ABCDEFGHJKLMNPQRSTUVWXYZabcdefghijkmnopqrstuvwxyz23456789!@#$%';const values=new Uint32Array(18);crypto.getRandomValues(values);return Array.from(values,v=>chars[v%chars.length]).join('')}
function statusLabel(status:string){return transactionStatuses.find(([value])=>value===status)?.[1]||status}
function Row({label,value}:{label:string;value:string}){return <div className="detail-row"><span>{label}</span><strong>{value}</strong></div>}
function Metric({label,value}:{label:string;value:string}){return <div className="metric"><span>{label}</span><strong>{value}</strong></div>}
function Panel({title,children}:{title:string;children:ReactNode}){return <section className="admin-panel"><div className="panel-title"><h2>{title}</h2></div>{children}</section>}
function Toolbar({value,onChange,placeholder}:{value:string;onChange:(v:string)=>void;placeholder:string}){return <div className="toolbar"><input value={value} onChange={e=>onChange(e.target.value)} placeholder={placeholder}/></div>}
