import { CheckCircle2, Clock3, RefreshCw, XCircle } from 'lucide-react'
import { useEffect, useState } from 'react'
import { supabase } from './supabaseClient'
import AdminNavigation from './AdminNavigation'
import './admin.css'
import './admin-applications.css'

type Application={id:string;email:string|null;full_name:string|null;preferred_name:string|null;phone:string|null;date_of_birth:string|null;address_line1:string|null;city:string|null;state_region:string|null;postal_code:string|null;country:string|null;occupation:string|null;employment_status:string|null;created_at:string;approval_status:string;approval_note:string|null}

const date=(v:string)=>new Date(v).toLocaleString('en-US',{dateStyle:'medium',timeStyle:'short'})

export default function AdminApplicationsPage(){
 const[applications,setApplications]=useState<Application[]>([]);const[loading,setLoading]=useState(true);const[busy,setBusy]=useState<string|null>(null);const[error,setError]=useState('')
 const load=async()=>{setLoading(true);setError('');const r=await supabase.rpc('admin_list_pending_applications');if(r.error)setError(r.error.message);setApplications((r.data||[]) as Application[]);setLoading(false)}
 useEffect(()=>{void load()},[])
 const review=async(id:string,status:'approved'|'rejected')=>{const note=status==='approved'?'Application reviewed and approved for customer access.':'Application reviewed and not approved for customer access.';setBusy(id);setError('');const r=await supabase.rpc('admin_set_application_status',{p_user_id:id,p_status:status,p_note:note});if(r.error)setError(r.error.message);else await load();setBusy(null)}
 return <main className="admin-shell"><AdminNavigation/><section className="admin-main"><header className="admin-header"><div><div className="eyebrow">CUSTOMER ONBOARDING</div><h1>Account applications</h1><p className="admin-header-subtitle">Every new customer remains pending until an authorized administrator reviews and approves the application.</p></div><button className="refresh" onClick={()=>void load()} disabled={loading}><RefreshCw size={15}/>{loading?'Refreshing…':'Refresh'}</button></header>{error&&<div className="admin-error" role="alert">{error}</div>}<section className="admin-panel"><div className="panel-head"><div><h2><Clock3 size={18}/> Waiting for authorization</h2><p className="admin-header-subtitle">{applications.length?`${applications.length} application${applications.length===1?'':'s'} require your review.`:'There are no pending applications.'}</p></div></div>{loading?<div className="empty-state">Loading applications…</div>:!applications.length?<div className="empty-state">No customer application is waiting for authorization.</div>:<div className="admin-application-list">{applications.map(a=><article className="admin-application-card" key={a.id}><div className="application-head"><div><strong>{a.full_name||a.preferred_name||'Applicant'}</strong><span>{a.email||'No email'} · Submitted {date(a.created_at)}</span></div><span className="application-pending">PENDING</span></div><div className="application-details"><div><small>Phone</small><b>{a.phone||'—'}</b></div><div><small>Date of birth</small><b>{a.date_of_birth||'—'}</b></div><div><small>Address</small><b>{[a.address_line1,a.city,a.state_region,a.postal_code,a.country].filter(Boolean).join(', ')||'—'}</b></div><div><small>Occupation</small><b>{a.occupation||'—'}</b></div><div><small>Employment status</small><b>{a.employment_status||'—'}</b></div></div><div className="application-actions"><button className="application-reject" disabled={busy===a.id} onClick={()=>void review(a.id,'rejected')}><XCircle size={16}/> Do not approve</button><button className="application-approve" disabled={busy===a.id} onClick={()=>void review(a.id,'approved')}><CheckCircle2 size={16}/>{busy===a.id?'Processing…':'Authorize customer'}</button></div></article>)}</div>}</section></section></main>
}
