import { useEffect, useMemo, useState } from 'react'
import { ArrowLeft, CalendarDays, Check, ChevronRight, Plus, Receipt, Search, X } from 'lucide-react'
import { useNavigate } from 'react-router-dom'
import { BankingShell } from './BankingShell'
import { useCustomerData } from './CustomerProvider'
import { supabase } from './supabaseClient'
import './feature-banking.css'
import './bill-pay.css'

const money = (n: number) => `$${Number(n || 0).toLocaleString('en-US', { minimumFractionDigits: 2, maximumFractionDigits: 2 })}`
const categories = ['Utilities', 'Internet', 'Mobile', 'Insurance', 'Credit card', 'Loan', 'Housing', 'Other']
type Payee = { id:string; name:string; account_reference:string|null; delivery_method:string; status:string; category:string }
type Biller = { id:string; name:string; category:string; description:string|null }

export default function BillPayPage() {
 const { account, profile } = useCustomerData(); const navigate = useNavigate()
 const [payees,setPayees]=useState<Payee[]>([]); const [billers,setBillers]=useState<Biller[]>([]); const [selected,setSelected]=useState<Payee|null>(null)
 const [name,setName]=useState(''); const [reference,setReference]=useState(''); const [category,setCategory]=useState('Utilities'); const [search,setSearch]=useState(''); const [categoryFilter,setCategoryFilter]=useState('All')
 const [amount,setAmount]=useState(''); const [date,setDate]=useState(new Date().toISOString().slice(0,10)); const [showAdd,setShowAdd]=useState(false); const [busy,setBusy]=useState(false); const [message,setMessage]=useState(''); const [paidAmount,setPaidAmount]=useState(0); const [error,setError]=useState('')
 const value=Number(amount)||0
 const today=new Date().toISOString().slice(0,10)
 const load=async()=>{const [{data:payeeData,error:payeeError},{data:billerData,error:billerError}]=await Promise.all([
  supabase.from('bill_payees').select('id,name,account_reference,delivery_method,status,category').eq('status','active').order('name'),
  supabase.from('biller_directory').select('id,name,category,description').eq('active',true).order('sort_order').order('name')
 ]);if(payeeError){setError(payeeError.message);return}if(billerError){setError(billerError.message);return}setPayees((payeeData||[]) as Payee[]);setBillers((billerData||[]) as Biller[])}
 useEffect(()=>{void load()},[])
 const visibleBillers=useMemo(()=>billers.filter(b=>(categoryFilter==='All'||b.category===categoryFilter)&&(!search.trim()||`${b.name} ${b.category}`.toLowerCase().includes(search.trim().toLowerCase()))),[billers,categoryFilter,search])
 const selectDirectoryBiller=(biller:Biller)=>{setName(biller.name);setCategory(biller.category);setShowAdd(true);setSearch('')}
 const savePayee=async()=>{if(!name.trim()||!profile?.id)return;setBusy(true);setError('');try{const{data,error:saveError}=await supabase.from('bill_payees').insert({user_id:profile.id,name:name.trim(),account_reference:reference.trim()||null,category,delivery_method:'electronic',status:'active'}).select('id,name,account_reference,delivery_method,status,category').single();if(saveError)throw saveError;setSelected(data as Payee);setShowAdd(false);setName('');setReference('');await load()}catch(err:any){setError(err?.message||'Unable to save payee.')}finally{setBusy(false)}}
 const pay=async()=>{const available=Number(account?.available_balance||0);if(!account||!selected||value<=0||value>available)return;setBusy(true);setError('');try{const{data,error:paymentError}=await supabase.rpc('create_bill_payment',{p_payee_id:selected.id,p_account_id:account.id,p_amount:value,p_scheduled_for:date});if(paymentError)throw paymentError;setPaidAmount(value);setMessage(data?.reference||'Bill payment scheduled');setAmount('')}catch(err:any){setError(err?.message||'Unable to schedule this bill payment.')}finally{setBusy(false)}}
 if(message)return <BankingShell><div className="fb-page bill-pay-workspace"><header className="fb-heading"><div className="fb-heading-actions"><button className="fb-btn" onClick={()=>navigate('/')}><ArrowLeft size={15}/> Account overview</button><button className="fb-btn" onClick={()=>navigate('/transfers')}>Transfer</button><button className="fb-btn" onClick={()=>navigate('/deposit')}>Deposit</button></div><span>BILL PAY</span><h1>Payment scheduled</h1><p>Your payment is scheduled with the biller.</p></header><section className="fb-card"><div className="fb-success"><Check size={22}/><div><b>{money(paidAmount)} scheduled to {selected?.name}</b><p>Reference {message}</p></div></div><div className="fb-actions"><button className="fb-btn primary" onClick={()=>{setMessage('');setSelected(null)}}>Pay another bill</button><button className="fb-btn" onClick={()=>navigate('/transactions')}>View activity</button></div></section></div></BankingShell>
 return <BankingShell><div className="fb-page bill-pay-workspace"><header className="fb-heading"><div className="fb-heading-actions"><button className="fb-btn" onClick={()=>navigate('/')}><ArrowLeft size={15}/> Account overview</button><button className="fb-btn" onClick={()=>navigate('/transfers')}>Transfer</button><button className="fb-btn" onClick={()=>navigate('/deposit')}>Deposit</button></div><span>BILL PAY</span><h1>Pay a bill</h1><p>Choose a biller or add a company you pay regularly.</p></header><div className="fb-grid"><section className="fb-card"><div className="fb-card-head"><h2>{selected?'Payment details':'Choose a biller'}</h2><p>{selected?`${selected.name} · ${selected.category}`:'Select a saved payee or choose a biller below.'}</p></div>{payees.length>0&&<div className="bill-payee-list">{payees.map(payee=><button key={payee.id} className={`bill-payee ${selected?.id===payee.id?'active':''}`} onClick={()=>setSelected(payee)}><span><Receipt size={17}/></span><div><b>{payee.name}</b><small>{payee.category} · {payee.account_reference||'Account reference not added'}</small></div><ChevronRight size={16}/></button>)}</div>}
 <div className="bill-directory"><div className="fb-card-head"><h3>Popular billers</h3><p>Choose a biller to save it to your payees.</p></div><label className="fb-field bill-search"><span className="sr-only">Search billers</span><Search size={15}/><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Search billers"/></label><div className="bill-category-filter"><button className={categoryFilter==='All'?'active':''} onClick={()=>setCategoryFilter('All')}>All</button>{categories.map(item=><button key={item} className={categoryFilter===item?'active':''} onClick={()=>setCategoryFilter(item)}>{item}</button>)}</div><div className="bill-directory-list">{visibleBillers.map(biller=><button key={biller.id} className="bill-directory-item" onClick={()=>selectDirectoryBiller(biller)}><span><Receipt size={17}/></span><div><b>{biller.name}</b><small>{biller.category}{biller.description?` · ${biller.description}`:''}</small></div><Plus size={15}/></button>)}</div>{visibleBillers.length===0&&<div className="fb-empty"><b>No billers found</b><span>Try another search or add the company manually.</span></div>}</div>
 <button className="fb-btn" onClick={()=>{setShowAdd(v=>!v);setName('');setReference('')}}>{showAdd?<><X size={15}/> Cancel</>:<><Plus size={15}/> Add a biller manually</>}</button>{showAdd&&<div className="bill-add"><label className="fb-field">Biller name<input value={name} onChange={e=>setName(e.target.value)} placeholder="Company or organization name"/></label><label className="fb-field">Bill category<select value={category} onChange={e=>setCategory(e.target.value)}>{categories.map(item=><option key={item}>{item}</option>)}</select></label><label className="fb-field">Account number / reference<input value={reference} onChange={e=>setReference(e.target.value)} placeholder="Account number or reference"/></label><button className="fb-btn primary" disabled={!name.trim()||busy||!profile?.id} onClick={()=>void savePayee()}>{busy?'Saving…':'Save biller'}</button></div>}
 {selected&&<><label className="fb-field">Amount<input value={amount} onChange={e=>setAmount(e.target.value.replace(/[^0-9.]/g,''))} inputMode="decimal" placeholder="0.00"/></label><label className="fb-field">Payment date<input value={date} min={today} onChange={e=>setDate(e.target.value)} type="date"/></label><button className="fb-btn primary" disabled={busy||!value||value>Number(account?.available_balance||0)} onClick={()=>void pay()}>{busy?'Processing…':date===today?'Pay now':'Schedule payment'} <CalendarDays size={15}/></button></>}{error&&<p className="fb-error">{error}</p>}</section><section className="fb-card"><div className="fb-card-head"><h2>Payment details</h2><p>Review the payment before you submit it.</p></div><div className="fb-detail"><span>From</span><b>{account?.account_name||'Checking'}<small>Available {money(Number(account?.available_balance||0))}</small></b></div>{selected&&<><div className="fb-detail"><span>Biller</span><b>{selected.name}<small>{selected.category}</small></b></div><div className="fb-detail"><span>Payment date</span><b>{new Date(`${date}T12:00:00`).toLocaleDateString('en-US',{month:'short',day:'numeric',year:'numeric'})}</b></div><div className="fb-total"><span>Payment amount</span><strong>{money(value)}</strong></div></>}{!selected&&<div className="fb-empty"><b>Select a biller to continue</b><span>Your payment details will appear here.</span></div>}</section></div></div></BankingShell>
}
