import { useEffect, useState } from 'react'
import { CreditCard, Lock, ShieldAlert, WalletCards, Repeat2, ChevronRight, Check, X } from 'lucide-react'
import { BankingShell } from './BankingShell'
import { useCustomerData } from './CustomerProvider'
import { supabase } from './supabaseClient'
import './cards-v5.css'
import './fncu-identity.css'

const money=(n:number)=>`$${Math.abs(n).toLocaleString('en-US',{minimumFractionDigits:2,maximumFractionDigits:2})`
type Tx={id:string;merchant_name:string;merchant_category:string|null;amount:number;currency:string;status:string;created_at:string}
export function CardsCenterV5(){
 const {card,profile,refresh}=useCustomerData(); const [tx,setTx]=useState<Tx[]>([]); const [controls,setControls]=useState({online_purchases:true,contactless:true}); const [modal,setModal]=useState<'details'|'replace'|'pin'|'dispute'|null>(null); const [reason,setReason]=useState(''); const [description,setDescription]=useState(''); const [busy,setBusy]=useState(false); const [notice,setNotice]=useState('');
 const frozen=card?.status==='frozen'; const last4=card?.last4||'4821'; const cardholder=profile?.preferred_name||profile?.full_name||'Customer';
 useEffect(()=>{let alive=true;(async()=>{if(!card)return;const [{data:c},{data:t}]=await Promise.all([supabase.from('card_controls').select('online_purchases,contactless').eq('id',card.id).maybeSingle(),supabase.from('card_transactions').select('id,merchant_name,merchant_category,amount,currency,status,created_at').eq('card_control_id',card.id).order('created_at',{ascending:false}).limit(8)]);if(alive){if(c)setControls({online_purchases:c.online_purchases,contactless:c.contactless});setTx((t||[]) as Tx[])}})();return()=>{alive=false}},[card?.id]);
 const control=async(key:'online_purchases'|'contactless')=>{if(!card)return;const next=!controls[key];const {error}=await supabase.from('card_controls').update({[key]:next}).eq('id',card.id);if(error)setNotice(error.message);else setControls(v=>({...v,[key]:next}))};
 const freeze=async()=>{if(!card||busy)return;setBusy(true);const next=frozen?'active':'frozen';const {error}=await supabase.from('card_controls').update({status:next}).eq('id',card.id);if(!error){await refresh();setNotice(next==='frozen'?'Card frozen':'Card reactivated')}else setNotice(error.message);setBusy(false)};
 const service=async(type:'replacement'|'pin_change')=>{const uid=(await supabase.auth.getUser()).data.user?.id;if(!uid||!card)return;setBusy(true);const {error}=await supabase.from('card_service_requests').insert({user_id:uid,card_control_id:card.id,request_type:type,status:'open'});if(!error){await supabase.from('audit_logs').insert({user_id:uid,action:'card_'+type+'_requested',resource_type:'card',resource_id:card.id});setModal(null);setNotice(type==='replacement'?'Replacement request opened':'PIN change request opened')}else setNotice(error.message);setBusy(false)};
 const dispute=async()=>{const uid=(await supabase.auth.getUser()).data.user?.id;if(!uid||!reason.trim())return;setBusy(true);const {error}=await supabase.from('card_disputes').insert({user_id:uid,reason:reason.trim(),description:description.trim()||null});if(!error){setModal(null);setReason('');setDescription('');setNotice('Dispute opened for review')}else setNotice(error.message);setBusy(false)};
 return <BankingShell><div className="cv5-page"><header className="cv5-head"><div><span>CARDS</span><h1>Private Banking Card</h1><p>Manage your card, payment channels and protected card services.</p></div><div className={`cv5-state ${frozen?'danger':''}`}><i/>{frozen?'Frozen':'Active'}</div></header>
 <section className="cv5-layout"><div><div className="cv5-atm-card"><div className="cv5-card-top"><div className="cv5-fncu-card-brand"><span><b>FNCU</b></span></div><span className="cv5-card-type">USD</span></div><div className="cv5-chip"><i/><i/><i/><i/><i/><i/></div><div className="cv5-contactless">)))</div><div className="cv5-number">•••• &nbsp; •••• &nbsp; •••• &nbsp; {last4}</div><div className="cv5-card-bottom"><div><small>CARDHOLDER</small><strong>{cardholder.toUpperCase()}</strong></div><div><small>VALID</small><strong>12/30</strong></div><div><small>TYPE</small><strong>DEBIT</strong></div></div></div><div className="cv5-card-caption"><span><CreditCard size={15}/> Debit card · USD</span><span>•••• {last4}</span></div></div><aside className="cv5-panel"><div className="cv5-panel-head"><span>Card controls</span><b>SECURITY</b></div><Control label="Online purchases" value={controls.online_purchases} onClick={()=>void control('online_purchases')}/><Control label="Contactless" value={controls.contactless} onClick={()=>void control('contactless')}/><Control label="Card status" value={!frozen} onClick={()=>void freeze()} status={frozen?'Frozen':'Active'}/></aside></section>
 {notice&&<div className="cv5-notice"><Check size={16}/><span>{notice}</span><button onClick={()=>setNotice('')}><X size={14}/></button></div>}
 <section className="cv5-services"><div className="cv5-title"><span>CARD SERVICES</span><h2>Manage your card</h2></div><div className="cv5-service-grid"><Service icon={<WalletCards/>} title="Card details" text="Protected card information" onClick={()=>setModal('details')}/><Service icon={<Repeat2/>} title="Replace card" text="Open replacement request" onClick={()=>setModal('replace')}/><Service icon={<Lock/>} title="Change PIN" text="Start secure PIN request" onClick={()=>setModal('pin')}/><Service icon={<ShieldAlert/>} title="Report a problem" text="Open a dispute" onClick={()=>setModal('dispute')}/></div></section>
 <section className="cv5-activity"><div className="cv5-title"><span>RECENT ACTIVITY</span><h2>Card transactions</h2></div>{tx.length?tx.map(t=><div className="cv5-tx" key={t.id}><div><b>{t.merchant_name}</b><small>{t.merchant_category||'Card purchase'} · {new Date(t.created_at).toLocaleDateString()}</small></div><strong>{money(Number(t.amount))}</strong><em>{t.status}</em></div>):<div className="cv5-empty">No card transactions have been posted yet.</div>}</section>
 {modal&&<Modal type={modal} last4={last4} cardholder={cardholder} reason={reason} setReason={setReason} description={description} setDescription={setDescription} close={()=>setModal(null)} busy={busy} service={service} dispute={dispute}/>}</div></BankingShell>
}