import { useEffect, useMemo, useState } from 'react'
import { ArrowLeft, Check, Upload, X } from 'lucide-react'
import { useNavigate } from 'react-router-dom'
import { BankingShell } from './BankingShell'
import { useCustomerData } from './CustomerProvider'
import { supabase } from './supabaseClient'
import './feature-banking.css'

type UploadState={file:File|null;preview:string}
const money=(n:number)=>`$${Number(n||0).toLocaleString('en-US',{minimumFractionDigits:2,maximumFractionDigits:2})}`

export default function CheckDepositPage(){
 const {account}=useCustomerData(); const navigate=useNavigate()
 const [amount,setAmount]=useState(''); const [front,setFront]=useState<UploadState>({file:null,preview:''}); const [back,setBack]=useState<UploadState>({file:null,preview:''})
 const [busy,setBusy]=useState(false); const [error,setError]=useState(''); const [reference,setReference]=useState('')
 const value=Number(amount)||0
 useEffect(()=>()=>{if(front.preview)URL.revokeObjectURL(front.preview);if(back.preview)URL.revokeObjectURL(back.preview)},[front.preview,back.preview])
 const ready=Boolean(account?.id&&value>0&&front.file&&back.file)
 const pick=(side:'front'|'back',file:File|null)=>{if(!file)return;if(!['image/jpeg','image/png','image/webp'].includes(file.type)){setError('Upload a JPG, PNG, or WebP image for the check.');return}if(file.size>8*1024*1024){setError('Each check image must be 8 MB or smaller.');return}setError('');const preview=URL.createObjectURL(file);const next={file,preview};if(side==='front')setFront(next);else setBack(next)}
 const submit=async()=>{if(!ready||!account)return;setBusy(true);setError('');const requestId=crypto.randomUUID();const base=`${(await supabase.auth.getUser()).data.user?.id||'unknown'}/check-deposits/${requestId}`;const frontPath=`${base}/front-${front.file!.name.replace(/[^a-zA-Z0-9._-]/g,'_')}`;const backPath=`${base}/back-${back.file!.name.replace(/[^a-zA-Z0-9._-]/g,'_')}`;try{const fu=await supabase.storage.from('customer-documents').upload(frontPath,front.file!,{upsert:false,contentType:front.file!.type});if(fu.error)throw fu.error;const bu=await supabase.storage.from('customer-documents').upload(backPath,back.file!,{upsert:false,contentType:back.file!.type});if(bu.error)throw bu.error;const{data,error:e}=await supabase.rpc('submit_check_deposit',{p_account_id:account.id,p_amount:value,p_front_document_path:frontPath,p_back_document_path:backPath});if(e)throw e;setReference(data?.reference||'Check deposit submitted');}catch(e:any){await supabase.storage.from('customer-documents').remove([frontPath,backPath]);setError(e?.message||'We could not submit the check deposit.')}finally{setBusy(false)}}
 if(reference)return <BankingShell><div className="fb-page"><header className="fb-heading"><span>DEPOSIT</span><h1>Check deposit submitted</h1><p>Your check images were received and the request is now awaiting review.</p></header><section className="fb-card"><div className="fb-success"><Check size={22}/><div><b>{money(value)} submitted for review</b><p>Reference {reference}</p></div></div><div className="fb-actions"><button className="fb-btn primary" onClick={()=>{setReference('');setAmount('');setFront({file:null,preview:''});setBack({file:null,preview:''})}}>Deposit another check</button><button className="fb-btn" onClick={()=>navigate('/transactions')}>View activity</button></div></section></div></BankingShell>
 return <BankingShell><div className="fb-page"><header className="fb-heading"><button className="fb-btn" onClick={()=>navigate('/')}><ArrowLeft size={15}/> Account overview</button><span>DEPOSIT</span><h1>Deposit a check</h1><p>Submit the front and back images of your check for FNCU review. Funds are not available until the deposit is approved.</p></header><section className="fb-card"><div className="fb-card-head"><h2>Check details</h2><p>Deposit to {account?.account_name||'Checking'} · •••• {account?.account_number_last4||'----'}</p></div><label className="fb-field">Check amount<input value={amount} onChange={e=>setAmount(e.target.value.replace(/[^0-9.]/g,''))} inputMode="decimal" placeholder="0.00"/></label><div className="fb-grid"><UploadBox label="Front of check" state={front} onPick={f=>pick('front',f)} onClear={()=>setFront({file:null,preview:''})}/><UploadBox label="Back of check" state={back} onPick={f=>pick('back',f)} onClear={()=>setBack({file:null,preview:''})}/></div><div className="fb-notice"><strong>Before submitting</strong><span>Make sure both sides are clear, fully visible, and legible. Endorse the back as required before taking the photo.</span></div><button className="fb-btn primary" disabled={!ready||busy} onClick={()=>void submit()}>{busy?'Submitting…':<>Submit check deposit <Upload size={15}/></>}</button>{error&&<p className="fb-error">{error}</p>}</section></div></BankingShell>
}
function UploadBox({label,state,onPick,onClear}:{label:string;state:UploadState;onPick:(f:File)=>void;onClear:()=>void}){const id=`check-${label.replace(/\W/g,'').toLowerCase()}`;return <div className="fb-upload"><div className="fb-upload-head"><b>{label}</b>{state.file&&<button type="button" onClick={onClear} aria-label={`Remove ${label}`}><X size={14}/></button>}</div>{state.preview?<img src={state.preview} alt={`${label} preview`}/>:<label htmlFor={id} className="fb-upload-drop"><Upload size={20}/><strong>Upload image</strong><span>JPG, PNG or WebP · max 8 MB</span><input id={id} type="file" accept="image/jpeg,image/png,image/webp" onChange={e=>{const f=e.target.files?.[0];if(f)onPick(f);e.currentTarget.value=''}}/></label>}{state.file&&<small>{state.file.name}</small>}</div>}
