import { useCallback, useEffect, useMemo, useState } from 'react'
import { ArrowLeft, Bot, CheckCheck, MessageCircle, Send, ShieldCheck, UserRound } from 'lucide-react'
import { BankingShell } from './BankingShell'
import { supabase } from './supabaseClient'
import './feature-banking.css'

type ChatMessage={id:string;user_id:string;subject:string;body:string;read_at:string|null;created_at:string;message_type:string;metadata:any}
const fmt=(v:string)=>new Date(v).toLocaleString('en-US',{month:'short',day:'numeric',hour:'numeric',minute:'2-digit'})
const chatId=()=>{const key='fncu.support.chat.id';let v=localStorage.getItem(key);if(!v){v=crypto.randomUUID();localStorage.setItem(key,v)}return v}

export default function CustomerServiceChatPage(){
 const[items,setItems]=useState<ChatMessage[]>([]);const[text,setText]=useState('');const[subject,setSubject]=useState('Customer service');const[loading,setLoading]=useState(true);const[sending,setSending]=useState(false);const[error,setError]=useState('');const[handoff,setHandoff]=useState(false)
 const conversationId=useMemo(()=>chatId(),[])
 const load=useCallback(async(silent=false)=>{if(!silent)setLoading(true);const r=await supabase.functions.invoke('customer-service-chat',{body:{action:'list',conversation_id:conversationId}});if(r.error)setError(r.error.message);else{const rows=(r.data?.messages||[]) as ChatMessage[];const next=rows.filter(m=>m.metadata?.conversation_id===conversationId);setItems(prev=>{if(prev.length===next.length&&prev.every((m,i)=>m.id===next[i]?.id&&m.body===next[i]?.body&&m.read_at===next[i]?.read_at))return prev;return next});setHandoff(next.some(m=>m.metadata?.handoff_required));const unread=next.filter(m=>m.metadata?.sender_role==='admin'&&!m.read_at).map(m=>m.id);if(unread.length)void supabase.functions.invoke('customer-service-chat',{body:{action:'mark_read',ids:unread}})}if(!silent)setLoading(false)},[conversationId])
 useEffect(()=>{let active=true;void load();const timer=window.setInterval(()=>{if(active&&document.visibilityState==='visible')void load(true)},10000);return()=>{active=false;window.clearInterval(timer)}},[load])
 const send=async()=>{const body=text.trim();if(!body||sending)return;setSending(true);setError('');const r=await supabase.functions.invoke('customer-service-chat',{body:{action:'ai_send',conversation_id:conversationId,subject,body}});if(r.error||r.data?.error){setError(r.error?.message||r.data?.error||'Unable to send message');setSending(false);return}setText('');if(r.data?.message)setItems(prev=>prev.some(m=>m.id===r.data.message.id)?prev:[...prev,r.data.message]);if(r.data?.assistant_message)setItems(prev=>prev.some(m=>m.id===r.data.assistant_message.id)?prev:[...prev,r.data.assistant_message]);if(r.data?.handoff_required)setHandoff(true);setSending(false);void load(true)}
 return <BankingShell><div className="fb-page customer-chat-page"><header className="fb-heading customer-chat-heading"><span>CUSTOMER SUPPORT</span><h1>FNCU Assistant</h1><p>Friendly, secure help with routine banking questions. If your request needs a person, the conversation stays available for FNCU customer service.</p></header><section className="fb-card customer-chat-shell"><div className="customer-chat-header"><div style={{display:'flex',alignItems:'center',gap:10}}><span className="customer-chat-avatar"><Bot size={18}/></span><div><strong>FNCU Assistant</strong><small>Friendly support · available anytime</small></div></div><span className="customer-chat-secure"><ShieldCheck size={14}/> Secure</span></div>{handoff&&<div className="customer-chat-handoff">This conversation has been flagged for FNCU customer service. A human representative can continue from here.</div>}<div className="customer-chat-messages">{loading?<p className="customer-chat-state">Loading conversation…</p>:items.length===0?<div className="customer-chat-welcome"><Bot size={30}/><h3>Welcome to FNCU</h3><p>I’m here to help with your account, transfers, transactions, savings, cards, deposits, and other banking questions.</p></div>:items.map(m=>{const role=m.metadata?.sender_role;const mine=role==='customer';const ai=role==='ai';return <div key={m.id} className={`customer-chat-row ${mine?'mine':''}`}><div className={`customer-chat-bubble ${mine?'mine':''}`}><div className="customer-chat-label">{ai?<><Bot size={11}/> FNCU Assistant</>:mine?<><UserRound size={11}/> You</>:<><MessageCircle size={11}/> FNCU Customer Service</>}</div><div className="customer-chat-body">{m.body}</div><small className="customer-chat-time">{fmt(m.created_at)}{mine&&<CheckCheck size={12}/>}</small></div></div>})}{sending&&<div className="customer-chat-row"><div className="customer-chat-typing"><Bot size={12}/><span>FNCU Assistant</span><span className="customer-chat-dots"><i/><i/><i/></span><span>typing…</span></div></div>}</div><div className="customer-chat-composer"><div className="customer-chat-composer-grid"><div><input value={subject} onChange={e=>setSubject(e.target.value)} placeholder="Subject"/><textarea value={text} onChange={e=>setText(e.target.value)} onKeyDown={e=>{if(e.key==='Enter'&&!e.shiftKey){e.preventDefault();void send()}}} placeholder="Ask FNCU Assistant…" rows={3}/></div><button type="button" onClick={()=>void send()} disabled={sending||!text.trim()}>{sending?<span>Sending…</span>:<Send size={15}/>}</button></div>{error&&<p className="customer-chat-error">{error}</p>}<p className="customer-chat-note">FNCU Assistant can answer routine questions but cannot authorize money movement or change security settings. Enter to send · Shift+Enter for a new line</p></div></section><button type="button" onClick={()=>history.back()} className="customer-chat-back"><ArrowLeft size={14}/> Back</button></div></BankingShell>
}
