import { StrictMode, useEffect, useState } from 'react'
import { createRoot } from 'react-dom/client'
import { BrowserRouter, useLocation, useNavigate } from 'react-router-dom'
import AuthPage from './AuthPage'
import ResetPasswordPage from './ResetPasswordPage'
import AdminLoginPage from './AdminLoginPage'
import AdminPasswordChangePage from './AdminPasswordChangePage'
import AdminRecoveryPage from './AdminRecoveryPage'
import AdminTransferNotificationsPage from './AdminTransferNotificationsPage'
import AdminTransferNotificationOverlay from './AdminTransferNotificationOverlay'
import { MFAChallenge } from './MFAChallenge'
import { CustomerProvider, useCustomerData } from './CustomerProvider'
import { supabase } from './supabaseClient'
import FNCUHome from './FNCUHome'
import { TransferCenterV2 } from './TransferCenterV2'
import TransferReviewPage from './TransferReviewPage'
import P2PPaymentPage from './P2PPaymentPage'
import P2PPaymentReviewPage from './P2PPaymentReviewPage'
import CheckDepositPage from './CheckDepositPage'
import BillPayPage from './BillPayPage'
import AdminDepositQueuePage from './AdminDepositQueuePage'
import AdminCreditPage from './AdminCreditPage'
import AdminOperationsPage from './AdminOperationsPage'
import { CardsCenterV5 } from './CardsCenterV5'
import TransactionsPage from './TransactionsPage'
import MessagesPage from './MessagesPage'
import ProfilePage from './ProfilePage'
import TransferPinPage from './TransferPinPage'
import { BeneficiariesPageV2 } from './BeneficiariesPageV2'
import './styles.css'
import './functional-ui.css'
import './auth.css'
import './fncu-identity.css'
import './ledger-shell.css'
import './card-atm.css'
import './receipt-presentation.css'
import './polish.css'
import './avatar-fix.css'
import './responsive-platform.css'
import './check-deposit.css'
import './admin-login.css'
import './admin-polish.css'
import './desktop-banking.css'
import './loading-presentation.css'
import './admin-customer-style.css'
import './admin-responsive-fix.css'
import './admin-unified-nav.css'
function useMfaGate(session: any) { const [ready,setReady]=useState(false);const[needs,setNeeds]=useState(false);useEffect(()=>{let active=true;const check=async()=>{if(!session){setReady(false);setNeeds(false);return};const{data,error}=await supabase.auth.mfa.getAuthenticatorAssuranceLevel();if(!active)return;if(error||data.nextLevel!=='aal2'||data.currentLevel==='aal2'){setNeeds(false);setReady(true);return}const token=sessionStorage.getItem('foxsycu.mfa.recovery.grant');if(token){const{data:grant}=await supabase.rpc('has_mfa_recovery_grant',{p_grant_token:token});if(grant?.valid){setNeeds(false);setReady(true);return}sessionStorage.removeItem('foxsycu.mfa.recovery.grant')}setNeeds(true);setReady(true)};void check();return()=>{active=false}},[session]);return{ready,needs,setNeeds}}
function Loading(){return <main className="fncu-loading" aria-label="Loading secure account"><div className="fncu-loading-card"><div className="fncu-loading-spinner" aria-hidden="true"/><p className="fncu-loading-copy">Loading your secure account…</p></div></main>}
function ProtectedCustomerApp(){const{session,loading,account,profile}=useCustomerData();const location=useLocation();const gate=useMfaGate(session);if(loading)return <Loading/>;if(!session)return <AuthPage/>;if(!account||!profile)return <Loading/>;if(!gate.ready)return <Loading/>;if(gate.needs)return <MFAChallenge onVerified={()=>gate.setNeeds(false)}/>;if(location.pathname==='/')return <FNCUHome/>;if(location.pathname==='/deposit')return <CheckDepositPage/>;if(location.pathname==='/bills')return <BillPayPage/>;if(location.pathname==='/transfers/review')return location.search.includes('mode=p2p')?<P2PPaymentReviewPage/>:<TransferReviewPage/>;if(location.pathname==='/transfers')return location.search.includes('mode=p2p')||location.search.includes('mode=zelle_like')?<P2PPaymentPage/>:<TransferCenterV2/>;if(location.pathname==='/transactions')return <TransactionsPage/>;if(location.pathname==='/messages')return <MessagesPage/>;if(location.pathname==='/cards')return <CardsCenterV5/>;if(location.pathname==='/beneficiaries')return <BeneficiariesPageV2/>;if(location.pathname==='/transfer-pin')return <TransferPinPage/>;return <FNCUHome/>}
function ProtectedProfile(){const{session,loading,account,profile}=useCustomerData();const gate=useMfaGate(session);if(loading)return <Loading/>;if(!session)return <AuthPage/>;if(!account||!profile)return <Loading/>;if(!gate.ready)return <Loading/>;if(gate.needs)return <MFAChallenge onVerified={()=>gate.setNeeds(false)}/>;return <ProfilePage/>}
function ProtectedAdmin(){const location=useLocation();const[session,setSession]=useState<any>(null);const[loading,setLoading]=useState(true);const[allowed,setAllowed]=useState(false);const[mustChange,setMustChange]=useState(false);const gate=useMfaGate(session);useEffect(()=>{let active=true;void supabase.auth.getSession().then(({data})=>{if(active){setSession(data.session);setLoading(false)}});const{data:listener}=supabase.auth.onAuthStateChange((_event,next)=>{if(active){setSession(next);setLoading(false)}});return()=>{active=false;listener.subscription.unsubscribe()}},[]);useEffect(()=>{if(loading)return;let active=true;void(async()=>{if(!session){setAllowed(false);setMustChange(false);return}await supabase.rpc('claim_bootstrap_admin');const{data:isAdmin}=await supabase.rpc('is_admin');if(!isAdmin){if(active){setAllowed(false);setMustChange(false)}return}const{data:changeRequired}=await supabase.rpc('admin_get_password_state');if(active){setAllowed(true);setMustChange(Boolean(changeRequired))}})();return()=>{active=false}},[loading,session]);if(loading)return <AdminLoginPage/>;if(!session)return <AdminLoginPage/>;if(!allowed)return <main className="admin-denied"><div><div className="admin-lock">ADMIN</div><h1>Admin access required</h1><p>This account is not authorized for the administration portal.</p><button onClick={()=>void supabase.auth.signOut()}>Sign out</button></div></main>;if(mustChange)return <AdminPasswordChangePage/>;if(!gate.ready)return <Loading/>;if(gate.needs)return <MFAChallenge onVerified={()=>gate.setNeeds(false)}/>;if(location.pathname==='/admin/deposits')return <AdminDepositQueuePage/>;if(location.pathname==='/admin/credits')return <AdminCreditPage/>;if(location.pathname==='/admin/recovery')return <AdminRecoveryPage/>;if(location.pathname==='/admin/transfer-notifications')return <AdminTransferNotificationsPage/>;return <><AdminOperationsPage/><AdminTransferNotificationOverlay/></>}
function Root(){const location=useLocation();const navigate=useNavigate();useEffect(()=>{if(location.pathname==='/private-banking'||location.pathname==='/services')navigate('/',{replace:true})},[location.pathname,navigate]);if(location.pathname==='/reset-password')return <ResetPasswordPage/>;if(location.pathname==='/login')return <AuthPage/>;if(location.pathname==='/admin/login')return <AdminLoginPage/>;if(location.pathname.startsWith('/admin'))return <ProtectedAdmin/>;return <CustomerProvider>{location.pathname==='/profile'?<ProtectedProfile/>:<ProtectedCustomerApp/>}</CustomerProvider>}
createRoot(document.getElementById('root')!).render(<StrictMode><BrowserRouter><Root/></BrowserRouter></StrictMode>)
