import { useEffect, useState } from 'react'
import { ArrowLeft, Check } from 'lucide-react'
import { useNavigate } from 'react-router-dom'
import { BankingShell } from './BankingShell'
import { useCustomerData } from './CustomerProvider'
import { createMoneyMovement } from './moneyMovementServiceV2'
import TransferAuthorizationPanel from './TransferAuthorizationPanel'
import './feature-banking.css'
const DRAFT_KEY='fncu:p2p-payment-draft';const money=(n:number)=>`$${Math.abs(n).toLocaleString('en-US',{minimumFractionDigits:2,maximumFractionDigits:2})}`
type Draft={recipient:string;email:string;amount:number;memo:string;sourceAccountId:string}
export default function P2PPaymentReviewPage(){
 const{account,refresh}=useCustomerData();const navigate=useNavigate();const[draft,setDraft]=useState<Draft|null>(null);const[busy,setBusy]=useState(false);const[error,setError]=useState('');const[movement,setMovement]=useState<any>(null);const[result,setResult]=useState<any>(null)
 useEffect(()=>{try{const raw=sessionStorage.getItem(DRAFT_KEY);if(raw)setDraft(JSON.parse(raw))}catch{setDraft(null)}},[])
 const create=async()=>{if(!account?.id||!draft)return;setBusy(true);setError('');try{if(draft.sourceAccountId!==account.id)throw new Error('The payment draft is no longer valid for this account.');if(draft.amount<=0||draft.amount>Number(account.available_balance||0))throw new Error('The payment amount is no longer available from this account.');const created=await createMoneyMovement({idempotencyKey:`fncu-p2p-${crypto.randomUUID()}`,rail:'zelle_like',sourceAccountId:account.id,destinationAccountId:null,beneficiaryId:null,amount:draft.amount,currency:'USD',memo:draft.memo,metadata:{counterparty:draft.recipient,recipient_name:draft.recipient,email:draft.email,synthetic_demo:true}});setMovement(created)}catch(e:any){setError(e?.message||'Unable to prepare this payment.')}finally{setBusy(false)}}
 if(result)return <BankingShell><div className="fb-page"><header className="fb-heading"><span>PAY A PERSON</span><h1>Payment submitted</h1><p>Your payment has been authorized and recorded.</p></header><section className="fb-card"><div className="fb-success"><Check size={22}/><div><b>Payment completed</b><p>{money(Number(result.amount||draft?.amount||0))} · {result.reference||'Reference pending'}</p></div></div><div className="fb-actions"><button className="fb-btn primary" onClick={()=>navigate('/transfers?mode=p2p')}>Make another payment</button><button className="fb-btn" onClick={()=>navigate('/transactions')}>View activity</button></div></section></div></BankingShell>
 if(!draft)return <BankingShell><div className="fb-page"><header className="fb-heading"><span>PAY A PERSON</span><h1>Payment summary unavailable</h1><p>Your payment draft is missing or has expired.</p></header><section className="fb-card"><div className="fb-actions"><button className="fb-btn primary" onClick={()=>navigate('/transfers?mode=p2p')}>Start a payment</button></div></section></div></BankingShell>
 if(movement)return <BankingShell><div className="fb-page"><header className="fb-heading"><span>PAY A PERSON · SECURITY</span><h1>Authorize payment</h1><p>For your security, enter your Transfer PIN and complete the authorization step.</p></header><TransferAuthorizationPanel movementId={movement.movement_id||movement.id} amount={draft.amount} reference={movement.reference||'P2P authorization'} onComplete={async r=>{setResult(r);sessionStorage.removeItem(DRAFT_KEY);await refresh()}} onBack={()=>setMovement(null)}/></div></BankingShell>
 const masked=account?.account_number_last4?`Checking •••• ${account.account_number_last4}`:'Checking'
 return <BankingShell><div className="fb-page"><header className="fb-heading"><span>PAY A PERSON · REVIEW</span><h1>Review payment</h1><p>Check the details before you continue.</p></header><section className="fb-card"><div className="fb-detail"><span>From</span><b>{masked}</b></div><div className="fb-detail"><span>To</span><b>{draft.recipient}<small>{draft.email}</small></b></div><div className="fb-detail"><span>Amount</span><b>{money(draft.amount)}</b></div>{draft.memo&&<div className="fb-detail"><span>Memo</span><b>{draft.memo}</b></div>}<div className="fb-total"><span>Available after</span><strong>{money(Math.max(0,Number(account?.available_balance||0)-draft.amount))}</strong></div><div className="fb-actions"><button className="fb-btn" disabled={busy} onClick={()=>navigate('/transfers?mode=p2p')}><ArrowLeft size={14}/> Edit payment</button><button className="fb-btn primary" disabled={busy} onClick={()=>void create()}>{busy?'Preparing…':'Continue to authorization'} <Check size={15}/></button></div>{error&&<p className="fb-error">{error}</p>}</section></div></BankingShell>
}
