import { useEffect, useState } from 'react'
import { ArrowRight, Search } from 'lucide-react'
import { useNavigate, useSearchParams } from 'react-router-dom'
import { BankingShell } from './BankingShell'
import { useCustomerData } from './CustomerProvider'
import { supabase } from './supabaseClient'
import type { MoneyMovementRail } from './moneyMovementServiceV2'
import './feature-banking.css'

type Destination={id:string;account_name:string;account_type:string;currency:string;account_number:string;directory_destination_id?:string|null}
type BeneficiaryBank={name:string;institution_name?:string|null;account_number?:string|null;account_masked?:string|null;account_type?:string|null;beneficiary_type?:string|null}
type InternationalDestination={id:string;recipient_name:string;country_code:'GB';country_name:string;institution_name:string;account_number:string|null;iban:string|null;routing_number:null;sort_code:string|null;swift_bic:string;destination_currency:string}
const rails:Array<{id:MoneyMovementRail;label:string}>=[{id:'internal',label:'FNCU account'},{id:'ach',label:'ACH'},{id:'wire',label:'Wire'},{id:'international',label:'International'},{id:'zelle_like',label:'Person'},{id:'deposit',label:'Deposit'}]
const mode=(v:string|null):MoneyMovementRail=>v==='deposit'?'deposit':v==='ach'||v==='send'?'ach':v==='wire'?'wire':v==='international'?'international':v==='p2p'||v==='zelle_like'?'zelle_like':'internal'
const money=(n:number)=>`$${Number(n||0).toLocaleString('en-US',{minimumFractionDigits:2,maximumFractionDigits:2})}`
const sortCode=(v:string)=>v?`${v.slice(0,2)}-${v.slice(2,4)}-${v.slice(4,6)}`:'—'
const REVIEW_KEY='fncu:transfer-review-draft'

export function TransferCenterV2(){
 const{account,beneficiaries}=useCustomerData();const navigate=useNavigate();const[params]=useSearchParams()
 const[rail,setRail]=useState<MoneyMovementRail>(()=>mode(params.get('mode')));const[destinationNumber,setDestinationNumber]=useState('');const[selectedDestination,setSelectedDestination]=useState<Destination|null>(null)
 const[beneficiaryBank,setBeneficiaryBank]=useState('');const[internationalAccount,setInternationalAccount]=useState('');const[internationalSort,setInternationalSort]=useState('');const[internationalSwift,setInternationalSwift]=useState('');const[internationalDestination,setInternationalDestination]=useState<InternationalDestination|null>(null)
 const[recipientName,setRecipientName]=useState('');const[externalAccount,setExternalAccount]=useState('');const[externalRouting,setExternalRouting]=useState('');const[externalAccountType,setExternalAccountType]=useState('checking');const[p2pEmail,setP2pEmail]=useState('');const[amount,setAmount]=useState('');const[memo,setMemo]=useState('');const[busy,setBusy]=useState(false);const[error,setError]=useState('')
 useEffect(()=>setRail(mode(params.get('mode'))),[params])
 useEffect(()=>{const id=params.get('beneficiary');if(!id)return;const b=(beneficiaries as any[]).find(x=>x.id===id);if(!b)return;setRail('ach');setRecipientName(String(b.name||''));setExternalAccount(String(b.account_number||''));setExternalRouting(String(b.routing_number||''));setExternalAccountType(String(b.account_type||'checking'));setBeneficiaryBank(String(b.institution_name||''))},[beneficiaries,params])
 const available=Number(account?.available_balance||0);const value=Number(amount)||0;const fee=rail==='wire'||rail==='international'?15:0;const emailOk=/^[^@\s]+@[^@\s]+\.[^@\s]+$/.test(p2pEmail.trim());const externalOk=rail==='zelle_like'?Boolean(recipientName.trim()&&emailOk):Boolean(recipientName.trim()&&/^\d{12}$/.test(externalAccount)&&/^\d{9}$/.test(externalRouting));const ready=value>0&&value+fee<=available&&(rail==='deposit'?Boolean(account?.id):rail==='internal'?Boolean(selectedDestination):rail==='international'?Boolean(internationalDestination):externalOk)
 const lookup=async()=>{const v=destinationNumber.replace(/\D/g,'');if(v.length!==12){setError('Enter the 12-digit FNCU account number.');return}setBusy(true);setError('');try{const{data,error:e}=await supabase.rpc('lookup_account_for_transfer',{p_account_number:v});if(e)throw e;setSelectedDestination(data as Destination)}catch(e:any){setSelectedDestination(null);setError(e?.message||'Account not found.')}finally{setBusy(false)}}
 const lookupInternational=async()=>{const iban=internationalAccount.toUpperCase().replace(/\s/g,'');const sort=internationalSort.replace(/\D/g,'');const swift=internationalSwift.trim().toUpperCase();if(iban.length<15||sort.length!==6){setError('Enter a valid UK IBAN and 6-digit sort code.');return}if(!/^[A-Z0-9]{8}(?:[A-Z0-9]{3})?$/.test(swift)){setError('Enter a valid SWIFT/BIC.');return}setBusy(true);setError('');try{const{data,error:e}=await supabase.rpc('lookup_international_transfer_destination',{p_country_code:'GB',p_account_identifier:iban,p_routing_or_sort_code:sort,p_swift_bic:swift});if(e)throw e;if(data?.country_code&&data.country_code!=='GB')throw new Error('International destinations are limited to the United Kingdom.');setInternationalDestination(data as InternationalDestination)}catch(e:any){setInternationalDestination(null);setError(e?.message||'International destination not recognized.')}finally{setBusy(false)}}
 const review=()=>{if(!ready||!account?.id)return;sessionStorage.setItem(REVIEW_KEY,JSON.stringify({rail,sourceAccountId:account.id,amount:value,memo:memo.trim(),fee,destinationNumber,selectedDestination,internationalDestination,recipientName:recipientName.trim(),externalAccount,externalRouting,externalAccountType,p2pEmail:p2pEmail.trim().toLowerCase()}));navigate(`/transfers/review?rail=${rail}`)}
 const destinationName=internationalDestination?.recipient_name||selectedDestination?.account_name||recipientName||'Select destination';const destinationBank=internationalDestination?.institution_name||selectedDestination?.account_name||beneficiaryBank||'Bank / institution';const destinationIdentifier=internationalDestination?.iban||internationalDestination?.account_number||selectedDestination?.account_number||externalAccount||p2pEmail||'—';const title=rail==='internal'?'Transfer between FNCU accounts':rail==='deposit'?'Deposit funds':rail==='international'?'International transfer':rail==='zelle_like'?'Pay a person':`${rail.toUpperCase()} transfer`
 const reset=(next:MoneyMovementRail)=>{setRail(next);setError('');setSelectedDestination(null);setInternationalDestination(null)}
 return <BankingShell><div className="fb-page transfer-center-page"><header className="fb-heading"><span>MOVE MONEY</span><h1>{title}</h1><p>Enter the details you need, then review before authorization.</p></header><div className="fb-tabs transfer-rail-tabs" role="tablist" aria-label="Transfer type">{rails.map(r=><button key={r.id} role="tab" aria-selected={rail===r.id} className={rail===r.id?'active':''} onClick={()=>reset(r.id)}>{r.label}</button>)}</div><div className="fb-grid"><section className="fb-card transfer-entry-card"><div className="fb-card-head"><h2>Payment details</h2><p>Only the information needed for this payment.</p></div>
 {rail==='internal'&&<><label className="fb-field">Destination account<input value={destinationNumber} onChange={e=>{setDestinationNumber(e.target.value.replace(/\D/g,'').slice(0,12));setSelectedDestination(null)}} inputMode="numeric" maxLength={12} placeholder="12-digit account number"/></label><button className="fb-btn" type="button" disabled={busy} onClick={()=>void lookup()}>{busy?'Checking…':<><Search size={15}/> Find account</>}</button>{selectedDestination&&<div className="fb-account-preview"><div><span>FNCU ACCOUNT</span><b>{selectedDestination.account_name}</b><small>{selectedDestination.account_type}</small></div><strong>•••• {selectedDestination.account_number.slice(-4)}</strong></div>}</>}
 {['ach','wire'].includes(rail)&&<><label className="fb-field">Recipient name<input value={recipientName} onChange={e=>setRecipientName(e.target.value)} placeholder="Full name"/></label><label className="fb-field">Bank / institution<input value={beneficiaryBank} onChange={e=>setBeneficiaryBank(e.target.value)} placeholder="Bank name"/></label><label className="fb-field">Account number<input value={externalAccount} onChange={e=>setExternalAccount(e.target.value.replace(/\D/g,'').slice(0,12))} inputMode="numeric" maxLength={12} placeholder="12-digit account number"/></label><label className="fb-field">Routing number<input value={externalRouting} onChange={e=>setExternalRouting(e.target.value.replace(/\D/g,'').slice(0,9))} inputMode="numeric" maxLength={9} placeholder="9-digit routing number"/></label><label className="fb-field">Account type<select value={externalAccountType} onChange={e=>setExternalAccountType(e.target.value)}><option value="checking">Checking</option><option value="savings">Savings</option></select></label></>}
 {rail==='zelle_like'&&<><label className="fb-field">Recipient name<input value={recipientName} onChange={e=>setRecipientName(e.target.value)} placeholder="Full name"/></label><label className="fb-field">Recipient email<input value={p2pEmail} onChange={e=>setP2pEmail(e.target.value)} type="email" inputMode="email" placeholder="recipient@example.com"/></label></>}
 {rail==='international'&&<><div className="fb-destination-card" aria-label="International transfer destination"><div className="fb-destination-copy"><span>DESTINATION</span><strong>United Kingdom</strong></div><div className="fb-currency-badge" aria-label="Destination currency GBP"><span>GBP</span><small>British pound</small></div></div><label className="fb-field">IBAN<input value={internationalAccount} onChange={e=>{setInternationalAccount(e.target.value);setInternationalDestination(null)}} placeholder="UK IBAN" autoComplete="off"/></label><label className="fb-field">Sort code<input value={internationalSort} onChange={e=>{setInternationalSort(e.target.value.replace(/\D/g,'').slice(0,6));setInternationalDestination(null)}} inputMode="numeric" maxLength={6} placeholder="6-digit sort code"/></label><label className="fb-field">SWIFT / BIC<input value={internationalSwift} onChange={e=>{setInternationalSwift(e.target.value.toUpperCase().slice(0,11));setInternationalDestination(null)}} maxLength={11} placeholder="8 or 11 characters"/></label><button className="fb-btn" type="button" disabled={busy} onClick={()=>void lookupInternational()}>{busy?'Checking…':<><Search size={15}/> Verify destination</>}</button>{internationalDestination&&<div className="fb-account-preview"><div><span>UNITED KINGDOM</span><b>{internationalDestination.recipient_name}</b><small>{internationalDestination.institution_name} · Sort {sortCode(internationalDestination.sort_code||'')} · {internationalDestination.swift_bic}</small></div><strong>•••• {(internationalDestination.iban||internationalDestination.account_number||'').slice(-4)}</strong></div>}</>}
 <label className="fb-field">Amount<input value={amount} onChange={e=>setAmount(e.target.value.replace(/[^0-9.]/g,''))} inputMode="decimal" placeholder="0.00"/></label><label className="fb-field">Memo <span style={{fontWeight:400,color:'#667085'}}>(optional)</span><input value={memo} onChange={e=>setMemo(e.target.value)} placeholder="Add a note"/></label><div className="fb-actions"><button className="fb-btn primary" disabled={!ready} onClick={review}>Review transfer <ArrowRight size={15}/></button></div>{error&&<p className="fb-error">{error}</p>}</section><aside className="fb-card payment-summary-card"><div className="fb-card-head"><h2>Summary</h2><p>Key payment details.</p></div><div className="fb-detail"><span>From</span><b>{account?.account_name||'Checking'}<small>•••• {account?.account_number_last4||'----'}</small></b></div>{rail!=='deposit'&&<div className="fb-detail"><span>To</span><b>{destinationName}<small>{destinationBank} · {destinationIdentifier==='—'?'—':`•••• ${destinationIdentifier.slice(-4)}`}</small></b></div>}<div className="fb-detail"><span>Amount</span><b>{money(value)}</b></div>{fee>0&&<div className="fb-detail"><span>Fee</span><b>{money(fee)}</b></div>}<div className="fb-total"><span>Total</span><strong>{money(value+fee)}</strong></div></aside></div></div></BankingShell>
}