import { useEffect, useState } from 'react'
import { ArrowLeft, Check, Clock, ShieldCheck } from 'lucide-react'
import { useNavigate } from 'react-router-dom'
import { supabase } from './supabaseClient'
import './feature-banking.css'

type Props={movementId:string;amount:number;reference:string;onComplete:(result:any)=>void;onBack:()=>void}
const money=(n:number)=>`$${Number(n||0).toLocaleString('en-US',{minimumFractionDigits:2,maximumFractionDigits:2})`
const secondsLeft=(iso:string)=>Math.max(0,Math.ceil((new Date(iso).getTime()-Date.now())/1000))
const format=(s:number)=>`${Math.floor(s/60)}:${String(s%60).padStart(2,'0')}`

export default function TransferAuthorizationPanel({movementId,amount,reference,onComplete,onBack}:Props){
 const navigate=useNavigate();const[stage,setStage]=useState<'pin'|'token'>('pin');const[pin,setPin]=useState('');const[token,setToken]=useState('');const[expiresAt,setExpiresAt]=useState('');const[remaining,setRemaining]=useState(0);const[busy,setBusy]=useState(false);const[error,setError]=useState('');const[delivered,setDelivered]=useState('')
 useEffect(()=>{if(!expiresAt)return;const tick=()=>setRemaining(secondsLeft(expiresAt));tick();const id=setInterval(tick,1000);return()=>clearInterval(id)},[expiresAt])
 const requestToken=async()=>{if(!/^\d{4,6}$/.test(pin))return setError('Enter your 4–6 digit Transfer PIN.');setBusy(true);setError('');try{const{data,error:e}=await supabase.functions.invoke('transfer-security',{body:{action:'send_token',movement_id:movementId,pin}});if(e)throw e;if(data?.error)throw new Error(data.error);setExpiresAt(data.expires_at);setRemaining(secondsLeft(data.expires_at));setDelivered(data.message||'Authorization token delivered to your notification center.');setStage('token')}catch(e:any){setError(e?.message||'Unable to issue the authorization token.')}finally{setBusy(false)}}
 const authorize=async()=>{if(remaining<=0)return setError('This authorization token has expired. Request a new token.');if(!/^\d{8}$/.test(token))return setError('Enter the 8-digit authorization token.');setBusy(true);setError('');try{const{data,error:e}=await supabase.functions.invoke('transfer-security',{body:{action:'authorize',movement_id:movementId,pin,token}});if(e)throw e;if(data?.error)throw new Error(data.error);onComplete(data.result)}catch(e:any){setError(e?.message||'Unable to authorize this transfer.')}finally{setBusy(false)}}
 const resend=async()=>{setToken('');setStage('pin');setExpiresAt('');setRemaining(0);setError('')}
 return <section className="fb-card"><div className="fb-card-head"><div style={{display:'flex',alignItems:'center',gap:10}}><ShieldCheck size={20}/><div><h2>Transfer authorization</h2><p>{reference} · {money(amount)}</p></div></div></div>{stage==='pin'?<><div className="fb-detail"><span>Step 1</span><b>Confirm your Transfer PIN<small>Your PIN is verified securely and is never shown to FNCU staff.</small></b></div><label className="fb-field">Transfer PIN<input value={pin} onChange={e=>setPin(e.target.value.replace(/\D/g,'').slice(0,6))} inputMode="numeric" type="password" maxLength={6} autoComplete="off" placeholder="4–6 digits"/></label><div className="fb-actions"><button className="fb-btn" disabled={busy} onClick={onBack}><ArrowLeft size={14}/> Back</button><button className="fb-btn primary" disabled={busy} onClick={()=>void requestToken()}>{busy?'Verifying…':'Verify PIN & request token'} <Check size={15}/></button></div></>:<><div className="fb-detail"><span>Step 2</span><b>Enter your authorization token<small>{delivered}</small></b></div><div className="fb-card" style={{marginTop:12,background:'rgba(11,94,215,.04)'}}><div style={{display:'flex',justifyContent:'space-between',alignItems:'center',gap:12}}><span style={{display:'inline-flex',alignItems:'center',gap:7}}><Clock size={16}/> Token expires in</span><strong style={{fontSize:22,fontVariantNumeric:'tabular-nums'}}>{remaining>0?format(remaining):'00:00'}</strong></div></div><label className="fb-field">8-digit authorization token<input value={token} onChange={e=>setToken(e.target.value.replace(/\D/g,'').slice(0,8))} inputMode="numeric" maxLength={8} autoComplete="one-time-code" placeholder="00000000"/></label>{remaining<=0&&<p className="fb-error">The token has expired. Request a new token using your Transfer PIN.</p>}<div className="fb-actions"><button className="fb-btn" disabled={busy} onClick={resend}>Request new token</button><button className="fb-btn" onClick={()=>navigate('/messages')}>Open notifications</button><button className="fb-btn primary" disabled={busy||remaining<=0} onClick={()=>void authorize()}>{busy?'Authorizing…':'Authorize transfer'} <Check size={15}/></button></div></>}{error&&<p className="fb-error">{error}</p>}</section>
}
