import { useEffect, useState } from 'react'
import { ArrowLeft, Check } from 'lucide-react'
import { useNavigate, useSearchParams } from 'react-router-dom'
import { BankingShell } from './BankingShell'
import { useCustomerData } from './CustomerProvider'
import { createMoneyMovement } from './moneyMovementServiceV2'
import TransferAuthorizationPanel from './TransferAuthorizationPanel'
import './feature-banking.css'

type Draft={rail:any;sourceAccountId:string;amount:number;memo:string;fee:number;destinationNumber:string;selectedDestination:any;country:'US'|'GB';internationalDestination:any;recipientName:string;externalAccount:string;externalRouting:string;externalAccountType:string;beneficiaryBank?:string;p2pEmail:string}
const KEY='fncu:transfer-review-draft';const money=(n:number)=>`${n<0?'-':''}$${Math.abs(n).toLocaleString('en-US',{minimumFractionDigits:2,maximumFractionDigits:2})}`;const label=(r:string)=>r==='zelle_like'?'Person':r==='internal'?'FNCU account':r.toUpperCase()
export default function TransferReviewPage(){
 const{account,refresh}=useCustomerData();const navigate=useNavigate();const[params]=useSearchParams();const[draft,setDraft]=useState<Draft|null>(null);const[busy,setBusy]=useState(false);const[error,setError]=useState('');const[movement,setMovement]=useState<any>(null);const[result,setResult]=useState<any>(null)
 useEffect(()=>{try{const raw=sessionStorage.getItem(KEY);if(raw)setDraft(JSON.parse(raw))}catch{setDraft(null)}},[])
 const create=async()=>{if(!draft||!account?.id)return;setBusy(true);setError('');try{if(draft.sourceAccountId!==account.id)throw new Error('This transfer draft is no longer valid for this account.');if(draft.rail!=='deposit'&&draft.amount+draft.fee>Number(account.available_balance||0))throw new Error('The transfer amount is no longer available.');let metadata:Record<string,unknown>;if(draft.rail==='international')metadata={counterparty:draft.internationalDestination?.recipient_name||null,directory_destination_id:draft.internationalDestination?.id||null,destination_country:draft.internationalDestination?.country_code||null,destination_currency:draft.internationalDestination?.destination_currency||null,destination_account_identifier:draft.internationalDestination?.account_number||draft.internationalDestination?.iban||null,destination_routing_or_sort:draft.internationalDestination?.routing_number||draft.internationalDestination?.sort_code||null,destination_swift_bic:draft.internationalDestination?.swift_bic||null,destination_institution:draft.internationalDestination?.institution_name||null,synthetic_demo:true};else if(draft.rail==='internal')metadata={counterparty:draft.selectedDestination?.account_name||null,destination_account_number:draft.selectedDestination?.account_number||null,destination_account_type:draft.selectedDestination?.account_type||null,directory_destination_id:draft.selectedDestination?.directory_destination_id||null,synthetic_demo:Boolean(draft.selectedDestination?.synthetic_demo)};else if(draft.rail==='zelle_like')metadata={counterparty:draft.recipientName.trim(),recipient_name:draft.recipientName.trim(),email:draft.p2pEmail.trim().toLowerCase(),synthetic_demo:true};else metadata={counterparty:draft.recipientName.trim(),recipient_name:draft.recipientName.trim(),account_number:draft.externalAccount,routing_number:draft.externalRouting,account_type:draft.externalAccountType,institution_name:draft.beneficiaryBank||null,destination_institution:draft.beneficiaryBank||null,synthetic_demo:true};const created=await createMoneyMovement({idempotencyKey:`fncu-transfer-${crypto.randomUUID()}`,rail:draft.rail,sourceAccountId:draft.rail==='deposit'?null:account.id,destinationAccountId:draft.rail==='internal'&&!draft.selectedDestination?.directory_destination_id?draft.selectedDestination?.id:null,beneficiaryId:null,amount:draft.amount,currency:'USD',memo:draft.memo,metadata});setMovement(created)}catch(e:any){setError(e?.message||'Unable to prepare this transfer.')}finally{setBusy(false)}}
 if(!draft)return <BankingShell><div className="fb-page"><header className="fb-heading"><span>MOVE MONEY</span><h1>Review unavailable</h1><p>This transfer draft is missing or has expired.</p></header><section className="fb-card"><button className="fb-btn primary" onClick={()=>navigate('/transfers')}>Return to transfers</button></section></div></BankingShell>
 if(result)return <BankingShell><div className="fb-page"><header className="fb-heading"><span>MOVE MONEY</span><h1>Transfer complete</h1><p>Your transfer has been authorized.</p></header><section className="fb-card"><div className="fb-success"><Check size={22}/><div><b>{money(Number(result.amount||draft.amount))}</b><p>{result.reference||'Reference pending'}</p></div></div><div className="fb-actions"><button className="fb-btn primary" onClick={()=>navigate(`/transfers?mode=${params.get('rail')||draft.rail}`)}>Make another</button><button className="fb-btn" onClick={()=>navigate('/transactions')}>View activity</button></div></section></div></BankingShell>
 if(movement)return <BankingShell><div className="fb-page"><header className="fb-heading"><span>MOVE MONEY · SECURITY</span><h1>Authorize transfer</h1><p>For your security, enter your Transfer PIN and authorization code.</p></header><TransferAuthorizationPanel movementId={movement.movement_id||movement.id} amount={draft.amount} reference={movement.reference||'Transfer'} onComplete={async r=>{setResult(r);sessionStorage.removeItem(KEY);await refresh()}} onBack={()=>setMovement(null)}/></div></BankingShell>
 const name=draft.internationalDestination?.recipient_name||draft.selectedDestination?.account_name||draft.recipientName||'Deposit';const identifier=draft.internationalDestination?.account_number||draft.internationalDestination?.iban||draft.selectedDestination?.account_number||draft.externalAccount||draft.p2pEmail||'—';const bank=draft.rail==='international'?draft.internationalDestination?.institution_name:draft.rail==='internal'?null:draft.beneficiaryBank;const masked=account?.account_number_last4?`•••• ${account.account_number_last4}`:'•••• ----'
 return <BankingShell><div className="fb-page"><header className="fb-heading"><span>MOVE MONEY · REVIEW</span><h1>Review transfer</h1><p>Check the details before authorization.</p></header><section className="fb-card"><div className="fb-detail"><span>Transfer type</span><b>{label(draft.rail)}</b></div><div className="fb-detail"><span>From</span><b>{account?.account_name||'Checking'}<small>{masked}</small></b></div><div className="fb-detail"><span>To</span><b>{name}<small>{bank?bank+' · ':''}{identifier}</small></b></div>{bank&&<div className="fb-detail"><span>Bank / institution</span><b>{bank}</b></div>}<div className="fb-detail"><span>Amount</span><b>{money(draft.amount)}</b></div><div className="fb-detail"><span>Fee</span><b>{money(draft.fee)}</b></div><div className="fb-total"><span>Total</span><strong>{money(draft.amount+draft.fee)}</strong></div>{draft.memo&&<div className="fb-detail"><span>Memo</span><b>{draft.memo}</b></div>}<div className="fb-actions"><button className="fb-btn" disabled={busy} onClick={()=>navigate(`/transfers?mode=${params.get('rail')||draft.rail}`)}><ArrowLeft size={14}/> Edit transfer</button><button className="fb-btn primary" disabled={busy} onClick={()=>void create()}>{busy?'Preparing…':'Continue to authorization'} <Check size={15}/></button></div>{error&&<p className="fb-error">{error}</p>}</section></div></BankingShell>
}
