import { useState } from 'react'
import { ArrowRight, Check, Search, X } from 'lucide-react'
import { useNavigate, useSearchParams } from 'react-router-dom'
import { BankingShell } from './BankingShell'
import { useCustomerData } from './CustomerProvider'
import { supabase } from './supabaseClient'
import { createMoneyMovement, executeMoneyMovement, type MoneyMovementRail } from './moneyMovementServiceV2'
import './feature-banking.css'
import './beneficiaries-v2.css'

type Destination={id:string;account_name:string;account_type:string;currency:string;account_number:string;account_number_last4:string;status:string;synthetic_demo?:boolean;directory_destination_id?:string|null}
type InternationalDestination={id:string;recipient_name:string;country_code:'US'|'GB';country_name:string;institution_name:string;account_number:string|null;iban:string|null;routing_number:string|null;sort_code:string|null;swift_bic:string;destination_currency:string;synthetic_demo:boolean}
const money=(n:number)=>`${n<0?'-':''}$${Math.abs(n).toLocaleString('en-US',{minimumFractionDigits:2,maximumFractionDigits:2})}`
const rails:Array<{id:MoneyMovementRail;label:string}>= [{id:'internal',label:'Internal'},{id:'ach',label:'ACH'},{id:'wire',label:'Wire'},{id:'international',label:'International'},{id:'zelle_like',label:'Zelle'},{id:'deposit',label:'Deposit'}]
const routing=(v:string)=>v?`${v.slice(0,3)}-${v.slice(3,6)}-${v.slice(6)}`:'—'
const sortCode=(v:string)=>v?`${v.slice(0,2)}-${v.slice(2,4)}-${v.slice(4,6)}`:'—'

export function TransferCenterV4(){
 const {account,refresh}=useCustomerData(); const navigate=useNavigate(); const [params]=useSearchParams()
 const [rail,setRail]=useState<MoneyMovementRail>(()=>params.get('mode')==='deposit'?'deposit':'internal')
 const [destinationNumber,setDestinationNumber]=useState(''); const [selectedDestination,setSelectedDestination]=useState<Destination|null>(null)
 const [country,setCountry]=useState<'US'|'GB'>('US'); const [internationalAccount,setInternationalAccount]=useState(''); const [internationalRouting,setInternationalRouting]=useState(''); const [internationalSwift,setInternationalSwift]=useState(''); const [internationalDestination,setInternationalDestination]=useState<InternationalDestination|null>(null)
 const [recipientName,setRecipientName]=useState(''); const [externalAccount,setExternalAccount]=useState(''); const [externalRouting,setExternalRouting]=useState(''); const [externalAccountType,setExternalAccountType]=useState('checking'); const [zelleEmail,setZelleEmail]=useState('')
 const [amount,setAmount]=useState(''); const [memo,setMemo]=useState(''); const [review,setReview]=useState(false); const [busy,setBusy]=useState(false); const [lookupBusy,setLookupBusy]=useState(false); const [result,setResult]=useState<any>(null); const [error,setError]=useState('')
 const source=account?.id||''; const available=Number(account?.available_balance||0); const value=Number(amount)||0; const fee=rail==='wire'||rail==='international'?15:0
 const externalReady=rail==='zelle_like'?Boolean(recipientName.trim()&&/^[^@\s]+@[^@\s]+\.[^@\s]+$/.test(zelleEmail.trim())):Boolean(recipientName.trim()&&/^\d{12}$/.test(externalAccount)&&/^\d{9}$/.test(externalRouting))
 const canContinue=value>0&&value+fee<=available&&(rail==='deposit'?!!source:rail==='internal'?!!source&&!!selectedDestination:rail==='international'?!!source&&!!internationalDestination:!!source&&externalReady)
 const lookup=async()=>{const clean=destinationNumber.replace(/\D/g,'');if(clean.length!==12){setError('Enter the full 12-digit FNCU destination account number.');return}setLookupBusy(true);setError('');try{const{data,error:e}=await supabase.rpc('lookup_account_for_transfer',{p_account_number:clean});if(e)throw e;setSelectedDestination(data as Destination)}catch(e:any){setSelectedDestination(null);setError(e?.message||'Destination account not found.')}finally{setLookupBusy(false)}}
 const lookupInternational=async()=>{const accountIdentifier=country==='US'?internationalAccount.replace(/\D/g,''):internationalAccount.toUpperCase().replace(/\s/g,'');const routingIdentifier=internationalRouting.replace(/\D/g,'');const swift=internationalSwift.trim().toUpperCase();if(country==='US'&&(accountIdentifier.length!==12||routingIdentifier.length!==9)){setError('US destinations require a 12-digit account number and 9-digit routing number.');return}if(country==='GB'&&(accountIdentifier.length<15||routingIdentifier.length!==6)){setError('UK destinations require a valid IBAN and 6-digit sort code.');return}if(!/^[A-Z0-9]{8}(?:[A-Z0-9]{3})?$/.test(swift)){setError('Enter a valid 8 or 11 character SWIFT/BIC.');return}setLookupBusy(true);setError('');try{const{data,error:e}=await supabase.rpc('lookup_international_transfer_destination',{p_country_code:country,p_account_identifier:accountIdentifier,p_routing_or_sort_code:routingIdentifier,p_swift_bic:swift});if(e)throw e;setInternationalDestination(data as InternationalDestination)}catch(e:any){setInternationalDestination(null);setError(e?.message||'International destination not recognized.')}finally{setLookupBusy(false)}}
 const authorize=async()=>{setBusy(true);setError('');try{const key=`fncu-v4-${crypto.randomUUID()}`;const isExternal=['ach','wire','zelle_like'].includes(rail);const metadata=rail==='international'?{counterparty:internationalDestination?.recipient_name||null,directory_destination_id:internationalDestination?.id||null,destination_country:internationalDestination?.country_code||null,destination_currency:internationalDestination?.destination_currency||null,destination_account_identifier:internationalDestination?.account_number||internationalDestination?.iban||null,destination_routing_or_sort:internationalDestination?.routing_number||internationalDestination?.sort_code||null,destination_swift_bic:internationalDestination?.swift_bic||null,destination_institution:internationalDestination?.institution_name||null,synthetic_demo:true}:rail==='internal'?{counterparty:selectedDestination?.account_name||null,destination_account_number:selectedDestination?.account_number||null,destination_account_type:selectedDestination?.account_type||null,directory_destination_id:selectedDestination?.directory_destination_id||null,synthetic_demo:Boolean(selectedDestination?.synthetic_demo)}:isExternal?{counterparty:recipientName.trim(),recipient_name:recipientName.trim(),account_number:externalAccount||null,routing_number:externalRouting||null,account_type:externalAccountType||null,email:zelleEmail.trim().toLowerCase()||null,synthetic_demo:true}:{counterparty:null,synthetic_demo:true};const created=await createMoneyMovement({idempotencyKey:key,rail,sourceAccountId:rail==='deposit'?null:source,destinationAccountId:rail==='internal'&&!selectedDestination?.directory_destination_id?selectedDestination?.id:null,beneficiaryId:null,amount:value,currency:'USD',memo,metadata});const completed=created.status==='processing'?await executeMoneyMovement(created.movement_id):created;setResult(completed);setReview(false);await refresh()}catch(e:any){setError(e?.message||'Unable to authorize this movement')}finally{setBusy(false)}}
 if(result)return <BankingShell><div className="fb-page"><header className="fb-heading"><span>MOVE MONEY</span><h1>{result.status==='completed'?'Payment completed':'Payment status'}</h1><p>The ledger was updated only after successful authorization.</p></header><section className="fb-card"><div className="fb-success"><Check size={22}/><div><b>{result.status==='completed'?'Movement posted successfully':'Movement accepted for processing'}</b><p>{money(value)} · {result.reference||'Reference pending'}</p></div></div><div className="fb-actions"><button className="fb-btn primary" onClick={()=>{setResult(null);setAmount('');setMemo('');setDestinationNumber('');setSelectedDestination(null);setInternationalAccount('');setInternationalRouting('');setInternationalSwift('');setInternationalDestination(null);setRecipientName('');setExternalAccount('');setExternalRouting('');setZelleEmail('')}}>Make another</button><button className="fb-btn" onClick={()=>navigate('/transactions')}>View activity <ArrowRight size={14}/></button></div></section></div></BankingShell>
 const destinationName=internationalDestination?.recipient_name||selectedDestination?.account_name||recipientName||'Select destination'
 const destinationIdentifier=internationalDestination?.account_number||internationalDestination?.iban||selectedDestination?.account_number||externalAccount||zelleEmail||'—'
 return <BankingShell><div className="fb-page"><header className="fb-heading"><span>MOVE MONEY</span><h1>Transfer center</h1><p>Enter the destination details for the selected rail. Nothing is saved as a beneficiary unless you explicitly use the Beneficiaries page.</p></header><div className="fb-tabs">{rails.map(r=><button key={r.id} className={rail===r.id?'active':''} onClick={()=>{setRail(r.id);setError('');setSelectedDestination(null);setInternationalDestination(null)}}>{r.label}</button>)}</div><div className="fb-grid"><section className="fb-card"><div className="fb-card-head"><div><h2>{rail==='internal'?'Internal account transfer':rail==='deposit'?'Deposit funds':rail==='international'?'International wire':rail==='zelle_like'?'Zelle payment':`${rail.toUpperCase()} payment`}</h2><p>{rail==='internal'?'FNCU recognizes registered internal directory accounts without turning them into beneficiaries.':rail==='zelle_like'?'Zelle-style transfers use the recipient email address rather than an account/routing selector.':rail==='international'?'US and UK destinations are recognized by their country-specific account and SWIFT details. They are not saved as beneficiaries.':'Enter the one-time recipient details required for this payment. Saved beneficiaries are not listed here.'}</p></div></div>
 {rail==='internal'&&<><label className="fb-field">FNCU destination account number<input value={destinationNumber} onChange={e=>{setDestinationNumber(e.target.value.replace(/\D/g,'').slice(0,12));setSelectedDestination(null)}} inputMode="numeric" maxLength={12} placeholder="12-digit account number"/></label><button className="fb-btn" type="button" disabled={lookupBusy} onClick={()=>void lookup()}>{lookupBusy?<span>Checking…</span>:<><Search size={15}/> Find internal account</>}</button>{selectedDestination&&<div className="fb-account-preview"><div><span>{selectedDestination.synthetic_demo?'FNCU INTERNAL DIRECTORY':'FNCU ACCOUNT'}</span><b>{selectedDestination.account_name}</b><small>{selectedDestination.account_type} · {selectedDestination.currency}</small></div><strong>{selectedDestination.account_number}</strong></div>}</>}
 {['ach','wire'].includes(rail)&&<><label className="fb-field">Recipient name<input value={recipientName} onChange={e=>setRecipientName(e.target.value)} placeholder="Full recipient name"/></label><label className="fb-field">Account number<input value={externalAccount} onChange={e=>{setExternalAccount(e.target.value.replace(/\D/g,'').slice(0,12))}} inputMode="numeric" maxLength={12} placeholder="12-digit account number"/></label><label className="fb-field">Routing number<input value={externalRouting} onChange={e=>setExternalRouting(e.target.value.replace(/\D/g,'').slice(0,9))} inputMode="numeric" maxLength={9} placeholder="9-digit routing number"/></label><label className="fb-field">Account type<select value={externalAccountType} onChange={e=>setExternalAccountType(e.target.value)}><option value="checking">Checking</option><option value="savings">Savings</option></select></label></>}
 {rail==='zelle_like'&&<><div className="fb-account-preview"><div><span>ZELLE-STYLE REQUIREMENT</span><b>Recipient email</b><small>Use the recipient's email address. No beneficiary account list is used.</small></div></div><label className="fb-field">Recipient name<input value={recipientName} onChange={e=>setRecipientName(e.target.value)} placeholder="Full recipient name"/></label><label className="fb-field">Recipient email<input value={zelleEmail} onChange={e=>setZelleEmail(e.target.value)} type="email" inputMode="email" placeholder="recipient@example.com"/></label></>}
 {rail==='international'&&<><label className="fb-field">Destination country<select value={country} onChange={e=>{setCountry(e.target.value as 'US'|'GB');setInternationalDestination(null);setError('')}}><option value="US">United States</option><option value="GB">United Kingdom</option></select></label><label className="fb-field">{country==='US'?'Account number':'IBAN'}<input value={internationalAccount} onChange={e=>{setInternationalAccount(e.target.value);setInternationalDestination(null)}} placeholder={country==='US'?'12-digit account number':'GB IBAN, e.g. GB82 FOXS 2045 7812 6390 44'}/></label><label className="fb-field">{country==='US'?'Routing number':'Sort code'}<input value={internationalRouting} onChange={e=>{setInternationalRouting(e.target.value.replace(/\D/g,'').slice(0,country==='US'?9:6));setInternationalDestination(null)}} inputMode="numeric" placeholder={country==='US'?'9-digit routing number':'6-digit sort code'}/></label><label className="fb-field">SWIFT / BIC<input value={internationalSwift} onChange={e=>{setInternationalSwift(e.target.value.toUpperCase().slice(0,11));setInternationalDestination(null)}} placeholder="8 or 11 characters" maxLength={11}/></label><button className="fb-btn" type="button" disabled={lookupBusy} onClick={()=>void lookupInternational()}>{lookupBusy?<span>Checking…</span>:<><Search size={15}/> Recognize international destination</>}</button>{internationalDestination&&<div className="fb-account-preview"><div><span>{internationalDestination.country_name.toUpperCase()} · {internationalDestination.institution_name}</span><b>{internationalDestination.recipient_name}</b><small>{internationalDestination.country_code==='US'?`Routing ${routing(internationalDestination.routing_number||'')} · `:`Sort ${sortCode(internationalDestination.sort_code||'')}`}{internationalDestination.swift_bic} · {internationalDestination.destination_currency}</small></div><strong>{internationalDestination.account_number||internationalDestination.iban}</strong></div>}</>}
 <label className="fb-field">Amount<input value={amount} onChange={e=>setAmount(e.target.value.replace(/[^0-9.]/g,''))} inputMode="decimal" placeholder="0.00"/></label><label className="fb-field">Memo<input value={memo} onChange={e=>setMemo(e.target.value)} placeholder="Optional memo"/></label><button className="fb-btn primary" disabled={!canContinue||busy} onClick={()=>setReview(true)}>Review & authorize <ArrowRight size={15}/></button>{error&&<p className="fb-error">{error}</p>}</section>
 <section className="fb-card"><div className="fb-card-head"><div><h2>Payment summary</h2><p>Nothing is posted until authorization succeeds.</p></div></div><div className="fb-detail"><span>From</span><b>{account?.account_name||'Checking'}<small>{account?.account_number||`•••• ${account?.account_number_last4||'----'}`}</small></b></div><div className="fb-detail"><span>To</span><b>{destinationName}<small>{destinationIdentifier}</small></b></div>{internationalDestination&&<><div className="fb-detail"><span>SWIFT / BIC</span><b>{internationalDestination.swift_bic}</b></div><div className="fb-detail"><span>{internationalDestination.country_code==='US'?'Routing number':'Sort code'}</span><b>{internationalDestination.country_code==='US'?routing(internationalDestination.routing_number||''):sortCode(internationalDestination.sort_code||'')}</b></div></>}<div className="fb-detail"><span>Amount</span><b>{money(value)}</b></div><div className="fb-detail"><span>Fee</span><b>{money(fee)}</b></div><div className="fb-total"><span>Total</span><strong>{money(value+fee)}</strong></div><div className="fb-detail"><span>Available after movement</span><b>{money(Math.max(0,available-value-fee))}</b></div></section></div>
 {review&&<div className="fb-modal"><div className="fb-dialog"><button className="fb-x" onClick={()=>setReview(false)}><X/></button><span>REVIEW & AUTHORIZE</span><h2>Confirm movement</h2><div className="fb-review"><div><span>Rail</span><b>{rail.toUpperCase()}</b></div><div><span>Destination</span><b>{destinationName}</b></div><div><span>{rail==='zelle_like'?'Recipient email':'Account / IBAN'}</span><b>{destinationIdentifier}</b></div>{(rail==='ach'||rail==='wire')&&<><div><span>Routing number</span><b>{routing(externalRouting)}</b></div><div><span>Account type</span><b>{externalAccountType}</b></div></>}{internationalDestination&&<><div><span>SWIFT / BIC</span><b>{internationalDestination.swift_bic}</b></div><div><span>{internationalDestination.country_code==='US'?'Routing number':'Sort code'}</span><b>{internationalDestination.country_code==='US'?routing(internationalDestination.routing_number||''):sortCode(internationalDestination.sort_code||'')}</b></div><div><span>Destination currency</span><b>{internationalDestination.destination_currency}</b></div></>}<div><span>Settlement currency</span><b>USD</b></div><div><span>Amount</span><b>{money(value)}</b></div><div><span>Total</span><b>{money(value+fee)}</b></div></div><button className="fb-btn primary" disabled={busy} onClick={()=>void authorize()}>{busy?'Authorizing…':'Authorize'} <Check size={15}/></button></div></div>}
 </div></BankingShell>
}
