import { useEffect, useMemo, useState } from 'react'
import { ArrowRight, Search } from 'lucide-react'
import { useNavigate, useSearchParams } from 'react-router-dom'
import { BankingShell } from './BankingShell'
import { useCustomerData } from './CustomerProvider'
import { supabase } from './supabaseClient'
import type { MoneyMovementRail } from './moneyMovementServiceV2'
import './feature-banking.css'

type Rail=MoneyMovementRail
type Destination={id:string;account_name:string;account_type:string;currency:string;account_number:string;synthetic_demo?:boolean;directory_destination_id?:string|null}
type InternationalDestination={id:string;recipient_name:string;country_code:'US'|'GB';country_name:string;institution_name:string;account_number:string|null;iban:string|null;routing_number:string|null;sort_code:string|null;swift_bic:string;destination_currency:string;synthetic_demo:boolean}
const rails:Array<{id:Rail;label:string}>= [{id:'internal',label:'Internal'},{id:'ach',label:'ACH'},{id:'wire',label:'Wire'},{id:'international',label:'International'},{id:'zelle_like',label:'P2P'},{id:'deposit',label:'Deposit'}]
const normalizeMode=(mode:string|null):Rail=>{if(mode==='deposit')return'deposit';if(mode==='ach')return'ach';if(mode==='wire')return'wire';if(mode==='international')return'international';if(mode==='p2p'||mode==='zelle_like')return'zelle_like';if(mode==='internal'||mode==='a2a')return'internal';return'internal'}
const routing=(v:string)=>v?`${v.slice(0,3)}-${v.slice(3,6)}-${v.slice(6)}`:'—'
const sortCode=(v:string)=>v?`${v.slice(0,2)}-${v.slice(2,4)}-${v.slice(4,6)}`:'—'
const REVIEW_KEY='fncu:transfer-review-draft'

export function TransferCenterV2(){
 const {account}=useCustomerData();const navigate=useNavigate();const[params]=useSearchParams();const[rail,setRail]=useState<Rail>(()=>normalizeMode(params.get('mode')))
 const[destinationNumber,setDestinationNumber]=useState('');const[selectedDestination,setSelectedDestination]=useState<Destination|null>(null);const[country,setCountry]=useState<'US'|'GB'>('US');const[internationalAccount,setInternationalAccount]=useState('');const[internationalRouting,setInternationalRouting]=useState('');const[internationalSwift,setInternationalSwift]=useState('');const[internationalDestination,setInternationalDestination]=useState<InternationalDestination|null>(null);const[recipientName,setRecipientName]=useState('');const[externalAccount,setExternalAccount]=useState('');const[externalRouting,setExternalRouting]=useState('');const[externalAccountType,setExternalAccountType]=useState('checking');const[p2pEmail,setP2pEmail]=useState('');const[amount,setAmount]=useState('');const[memo,setMemo]=useState('');const[lookupBusy,setLookupBusy]=useState(false);const[error,setError]=useState('')
 useEffect(()=>setRail(normalizeMode(params.get('mode'))),[params])
 const source=account?.id||'';const available=Number(account?.available_balance||0);const value=Number(amount)||0;const fee=rail==='wire'||rail==='international'?15:0;const emailValid=/^[^@\s]+@[^@\s]+\.[^@\s]+$/.test(p2pEmail.trim());const externalReady=rail==='zelle_like'?Boolean(recipientName.trim()&&emailValid):Boolean(recipientName.trim()&&/^\d{12}$/.test(externalAccount)&&/^\d{9}$/.test(externalRouting));const canContinue=useMemo(()=>value>0&&value+fee<=available&&(rail==='deposit'?!!source:rail==='internal'?!!source&&!!selectedDestination:rail==='international'?!!source&&!!internationalDestination:!!source&&externalReady),[value,fee,available,rail,source,selectedDestination,internationalDestination,externalReady])
 const resetForRail=(next:Rail)=>{setRail(next);setError('');setSelectedDestination(null);setInternationalDestination(null)}
 const lookup=async()=>{const clean=destinationNumber.replace(/\D/g,'');if(clean.length!==12){setError('Enter the full 12-digit FNCU destination account number.');return}setLookupBusy(true);setError('');try{const{data,error:e}=await supabase.rpc('lookup_account_for_transfer',{p_account_number:clean});if(e)throw e;setSelectedDestination(data as Destination)}catch(e:any){setSelectedDestination(null);setError(e?.message||'Destination account not found.')}finally{setLookupBusy(false)}}
 const lookupInternational=async()=>{const id=country==='US'?internationalAccount.replace(/\D/g,''):internationalAccount.toUpperCase().replace(/\s/g,'');const routingId=internationalRouting.replace(/\D/g,'');const swift=internationalSwift.trim().toUpperCase();if(country==='US'&&(id.length!==12||routingId.length!==9)){setError('US destinations require a 12-digit account number and 9-digit routing number.');return}if(country==='GB'&&(id.length<15||routingId.length!==6)){setError('UK destinations require a valid IBAN and 6-digit sort code.');return}if(!/^[A-Z0-9]{8}(?:[A-Z0-9]{3})?$/.test(swift)){setError('Enter a valid 8 or 11 character SWIFT/BIC.');return}setLookupBusy(true);setError('');try{const{data,error:e}=await supabase.rpc('lookup_international_transfer_destination',{p_country_code:country,p_account_identifier:id,p_routing_or_sort_code:routingId,p_swift_bic:swift});if(e)throw e;setInternationalDestination(data as InternationalDestination)}catch(e:any){setInternationalDestination(null);setError(e?.message||'International destination not recognized.')}finally{setLookupBusy(false)}}
 const continueToReview=()=>{if(!canContinue)return;sessionStorage.setItem(REVIEW_KEY,JSON.stringify({rail,sourceAccountId:source,amount:value,memo:memo.trim(),fee,destinationNumber,selectedDestination,country,internationalDestination,recipientName:recipientName.trim(),externalAccount,externalRouting,externalAccountType,p2pEmail:p2pEmail.trim().toLowerCase()}));navigate(`/transfers/review?rail=${rail}`)}
 const destinationName=internationalDestination?.recipient_name||selectedDestination?.account_name||recipientName||'Select destination';const destinationIdentifier=internationalDestination?.account_number||internationalDestination?.iban||selectedDestination?.account_number||externalAccount||p2pEmail||'—';const railTitle=rail==='internal'?'Internal account transfer':rail==='deposit'?'Deposit funds':rail==='international'?'International transfer':rail==='zelle_like'?'Person-to-person payment':`${rail.toUpperCase()} payment`
 return <BankingShell><div className="fb-page transfer-center-page"><header className="fb-heading"><span>MOVE MONEY</span><h1>Transfer center</h1><p>Enter the transfer details first. The payment summary is shown on the next page before authorization.</p></header><div className="fb-tabs transfer-rail-tabs" role="tablist" aria-label="Transfer type">{rails.map(r=><button key={r.id} role="tab" aria-selected={rail===r.id} className={rail===r.id?'active':''} onClick={()=>resetForRail(r.id)}>{r.label}</button>)}</div><section className="fb-card transfer-entry-card"><div className="fb-card-head"><h2>{railTitle}</h2><p>{rail==='internal'?'Transfer to a registered FNCU internal account.':rail==='zelle_like'?'Send USD to a person using their name and email.':rail==='deposit'?'Record a deposit into the account workflow.':rail==='international'?'Recognize the destination before authorization.':'Enter the one-time recipient details required for this transfer.'}</p></div>
 {rail==='internal'&&<><label className="fb-field">FNCU destination account number<input value={destinationNumber} onChange={e=>{setDestinationNumber(e.target.value.replace(/\D/g,'').slice(0,12));setSelectedDestination(null)}} inputMode="numeric" maxLength={12} placeholder="12-digit account number"/></label><button className="fb-btn" type="button" disabled={lookupBusy} onClick={()=>void lookup()}>{lookupBusy?'Checking…':<><Search size={15}/> Find internal account</>}</button>{selectedDestination&&<div className="fb-account-preview"><div><span>FNCU ACCOUNT</span><b>{selectedDestination.account_name}</b><small>{selectedDestination.account_type} · {selectedDestination.currency}</small></div><strong>{selectedDestination.account_number}</strong></div>}</>}
 {['ach','wire'].includes(rail)&&<><label className="fb-field">Recipient name<input value={recipientName} onChange={e=>setRecipientName(e.target.value)} placeholder="Full recipient name"/></label><label className="fb-field">Account number<input value={externalAccount} onChange={e=>setExternalAccount(e.target.value.replace(/\D/g,'').slice(0,12))} inputMode="numeric" maxLength={12} placeholder="12-digit account number"/></label><label className="fb-field">Routing number<input value={externalRouting} onChange={e=>setExternalRouting(e.target.value.replace(/\D/g,'').slice(0,9))} inputMode="numeric" maxLength={9} placeholder="9-digit routing number"/></label><label className="fb-field">Account type<select value={externalAccountType} onChange={e=>setExternalAccountType(e.target.value)}><option value="checking">Checking</option><option value="savings">Savings</option></select></label></>}
 {rail==='zelle_like'&&<><label className="fb-field">Recipient name<input value={recipientName} onChange={e=>setRecipientName(e.target.value)} placeholder="Full recipient name"/></label><label className="fb-field">Recipient email<input value={p2pEmail} onChange={e=>setP2pEmail(e.target.value)} type="email" inputMode="email" placeholder="recipient@example.com"/></label></>}
 {rail==='international'&&<><label className="fb-field">Destination country<select value={country} onChange={e=>{setCountry(e.target.value as 'US'|'GB');setInternationalDestination(null);setError('')}}><option value="US">United States</option><option value="GB">United Kingdom</option></select></label><label className="fb-field">{country==='US'?'Account number':'IBAN'}<input value={internationalAccount} onChange={e=>{setInternationalAccount(e.target.value);setInternationalDestination(null)}} placeholder={country==='US'?'12-digit account number':'GB IBAN'}/></label><label className="fb-field">{country==='US'?'Routing number':'Sort code'}<input value={internationalRouting} onChange={e=>{setInternationalRouting(e.target.value.replace(/\D/g,'').slice(0,country==='US'?9:6));setInternationalDestination(null)}} inputMode="numeric" placeholder={country==='US'?'9-digit routing number':'6-digit sort code'}/></label><label className="fb-field">SWIFT / BIC<input value={internationalSwift} onChange={e=>{setInternationalSwift(e.target.value.toUpperCase().slice(0,11));setInternationalDestination(null)}} maxLength={11} placeholder="8 or 11 characters"/></label><button className="fb-btn" type="button" disabled={lookupBusy} onClick={()=>void lookupInternational()}>{lookupBusy?'Checking…':<><Search size={15}/> Recognize destination</>}</button>{internationalDestination&&<div className="fb-account-preview"><div><span>{internationalDestination.country_name.toUpperCase()} · {internationalDestination.institution_name}</span><b>{internationalDestination.recipient_name}</b><small>{internationalDestination.country_code==='US'?`Routing ${routing(internationalDestination.routing_number||'')} · `:`Sort ${sortCode(internationalDestination.sort_code||'')}`}{internationalDestination.swift_bic} · {internationalDestination.destination_currency}</small></div><strong>{internationalDestination.account_number||internationalDestination.iban}</strong></div>}</>}
 <label className="fb-field">Amount<input value={amount} onChange={e=>setAmount(e.target.value.replace(/[^0-9.]/g,''))} inputMode="decimal" placeholder="0.00"/></label><label className="fb-field">Memo<input value={memo} onChange={e=>setMemo(e.target.value)} placeholder="Optional memo"/></label><div className="fb-actions"><button className="fb-btn primary" disabled={!canContinue} onClick={continueToReview}>Continue to payment summary <ArrowRight size={15}/></button></div>{error&&<p className="fb-error">{error}</p>}</section><div className="fb-card" style={{marginTop:14}}><div className="fb-card-head"><h2>Step 1 of 2</h2><p>Payment details only. Your funds are not moved on this page.</p></div><div className="fb-detail"><span>Destination</span><b>{destinationName}<small>{destinationIdentifier}</small></b></div><div className="fb-detail"><span>Amount entered</span><b>{value>0?`$${value.toLocaleString('en-US',{minimumFractionDigits:2,maximumFractionDigits:2})}`:'—'}</b></div></div></div></BankingShell>
}
