import { NavLink, Route, Routes, useLocation } from 'react-router-dom'
import { Activity, ArrowDownLeft, ArrowUpRight, Bell, ChevronDown, ChevronRight, CreditCard, FileText, HelpCircle, Home, LockKeyhole, LogOut, Menu, MessageSquare, MoreHorizontal, MoveRight, PiggyBank, Plus, Search, Settings, ShieldCheck, User, Users, Wallet, X } from 'lucide-react'
import { useState } from 'react'
import { customer } from './data/mockData'

const nav = [
  ['Dashboard', '/', Home], ['Accounts', '/accounts', Wallet], ['Savings', '/savings', PiggyBank], ['Transfers', '/transfers', MoveRight], ['Cards', '/cards', CreditCard], ['Transactions', '/transactions', Activity], ['Statements', '/statements', FileText], ['Beneficiaries', '/beneficiaries', Users], ['Messages', '/messages', MessageSquare], ['Support', '/support', HelpCircle], ['Settings', '/settings', Settings],
] as const

const money = (value: number) => `${value < 0 ? '-' : ''}$${Math.abs(value).toLocaleString('en-US', { minimumFractionDigits: 2, maximumFractionDigits: 2 })}`

function Brand() {
  return <div className="brand-lockup" aria-label="FOXSYCU Digital Banking System"><div className="brand-mark">F</div><div><strong>FOXSYCU</strong><span>DIGITAL BANKING SYSTEM</span></div></div>
}

function Shell({ children }: { children: React.ReactNode }) {
  const [open, setOpen] = useState(false)
  const location = useLocation()
  const title = location.pathname === '/' ? 'Overview' : location.pathname.slice(1).split('/')[0].replace(/\b\w/g, c => c.toUpperCase())
  return <div className="app-shell">
    <aside className={open ? 'sidebar open' : 'sidebar'}>
      <div className="sidebar-top"><Brand/><button className="close-mobile" onClick={() => setOpen(false)} aria-label="Close navigation"><X size={18}/></button></div>
      <div className="account-switcher"><div className="mini-avatar">JD</div><div><strong>John Doe</strong><span>Personal · USD</span></div><ChevronDown size={14}/></div>
      <nav className="desktop-nav" aria-label="Primary navigation">{nav.map(([label, path, Icon]) => <NavLink key={path} to={path} end={path === '/'} onClick={() => setOpen(false)} className={({isActive}) => isActive ? 'nav-item active' : 'nav-item'}><Icon size={17}/><span>{label}</span></NavLink>)}</nav>
      <div className="sidebar-footer"><div className="security-note"><ShieldCheck size={15}/><span>Protected & encrypted</span></div><button className="logout"><LogOut size={15}/> Sign out</button></div>
    </aside>
    <div className="main-area">
      <header className="topbar"><div className="topbar-left"><button className="menu" onClick={() => setOpen(true)} aria-label="Open navigation"><Menu size={21}/></button><div><span className="top-kicker">FOXSYCU / CUSTOMER</span><span className="top-title">{title}</span></div></div><div className="top-actions"><label className="search"><Search size={16}/><input placeholder="Search FOXSYCU" aria-label="Search"/></label><button className="icon-btn" aria-label="Notifications"><Bell size={18}/><i/></button><NavLink to="/messages" className="icon-btn" aria-label="Messages"><MessageSquare size={18}/></NavLink><NavLink to="/profile" className="profile"><span className="avatar">JD</span><span className="profile-text"><strong>John Doe</strong><small>Premium User</small></span><ChevronDown size={14}/></NavLink></div></header>
      <main className="content">{children}</main>
      <div className="simulation-banner"><ShieldCheck size={13}/><span>SIMULATED ENVIRONMENT</span><em>All balances and transactions shown are test data and have no real monetary value.</em></div>
    </div>
    <nav className="mobile-nav" aria-label="Mobile navigation">{[['Home','/',Home],['Savings','/savings',PiggyBank],['Activity','/transactions',Activity],['Move','/transfers',MoveRight],['Profile','/profile',User]].map(([label,path,Icon]) => <NavLink key={label as string} to={path as string} end={path === '/'}>{<Icon size={19}/>}<span>{label as string}</span></NavLink>)}</nav>
  </div>
}

function PageHead({ eyebrow, title, description, action }: { eyebrow: string; title: string; description?: string; action?: React.ReactNode }) { return <section className="page-head"><div><p className="eyebrow">{eyebrow}</p><h1>{title}</h1>{description && <p>{description}</p>}</div>{action}</section> }
function Panel({ title, subtitle, action, children, className='' }: { title: string; subtitle?: string; action?: React.ReactNode; children: React.ReactNode; className?: string }) { return <article className={`panel ${className}`}><div className="panel-head"><div><h2>{title}</h2>{subtitle && <p>{subtitle}</p>}</div>{action}</div>{children}</article> }
function ActionButton({ to, icon: Icon, title, detail }: { to: string; icon: typeof ArrowUpRight; title: string; detail: string }) { return <NavLink to={to} className="action-tile"><span className="action-icon"><Icon size={17}/></span><span><b>{title}</b><small>{detail}</small></span><ChevronRight size={15}/></NavLink> }

function Dashboard() {
  return <>
    <PageHead eyebrow="PERSONAL BANKING · USD" title={`Good morning, ${customer.name.split(' ')[0]}.`} description="Here is your financial position and recent account activity." action={<div className="head-actions"><NavLink to="/transfers" className="secondary">View activity</NavLink><NavLink to="/transfers" className="primary"><MoveRight size={16}/> Move money</NavLink></div>}/>
    <section className="hero-grid">
      <article className="balance-card"><div className="balance-top"><div><span className="card-eyebrow">TOTAL AVAILABLE BALANCE</span><span className="currency-pill">USD</span></div><button className="card-more" aria-label="Balance options"><MoreHorizontal size={18}/></button></div><div className="balance">{money(customer.availableBalance)}</div><div className="balance-meta"><span>Available to move</span><span className="secure-inline"><ShieldCheck size={13}/> Secure account</span></div><div className="balance-actions"><NavLink to="/transfers"><ArrowDownLeft size={15}/> Deposit</NavLink><NavLink to="/transfers"><ArrowUpRight size={15}/> Withdraw</NavLink><NavLink to="/transfers"><MoveRight size={15}/> Send USD</NavLink></div></article>
      <div className="side-metrics"><article className="metric-card"><div className="metric-icon blue"><PiggyBank size={17}/></div><span>SAVINGS BALANCE</span><strong>{money(customer.savingsBalance)}</strong><small><b>{customer.apy.toFixed(2)}%</b> APY · Across 3 vaults</small></article><article className="metric-card"><div className="metric-icon green"><ArrowUpRight size={17}/></div><span>INTEREST EARNED</span><strong className="positive">+{money(customer.interestEarned)}</strong><small>Earned this period</small></article></div>
    </section>
    <section className="dashboard-grid">
      <Panel title="Balance overview" subtitle="Available USD balance · last 30 days" action={<select aria-label="Chart period"><option>30 days</option><option>90 days</option></select>} className="chart-panel"><div className="chart-value">$12,450.00 <span>+6.8% <ArrowUpRight size={12}/></span></div><div className="chart"><div className="gridline g1"/><div className="gridline g2"/><div className="gridline g3"/><svg viewBox="0 0 800 220" preserveAspectRatio="none" aria-label="Balance trend"><defs><linearGradient id="fill" x1="0" x2="0" y1="0" y2="1"><stop offset="0%" stopColor="#155EEF" stopOpacity=".18"/><stop offset="100%" stopColor="#155EEF" stopOpacity="0"/></linearGradient></defs><path d="M0 170 C70 165 95 142 150 151 S235 165 290 128 S380 145 430 104 S520 125 575 89 S650 105 705 70 S755 77 800 40 L800 220 L0 220 Z" fill="url(#fill)"/><path d="M0 170 C70 165 95 142 150 151 S235 165 290 128 S380 145 430 104 S520 125 575 89 S650 105 705 70 S755 77 800 40" fill="none" stroke="#155EEF" strokeWidth="3"/></svg><div className="chart-labels"><span>Aug 12</span><span>Aug 19</span><span>Aug 26</span><span>Sep 2</span><span>Sep 10</span></div></div></Panel>
      <Panel title="Quick actions" subtitle="Common account tasks"><div className="action-list"><ActionButton to="/accounts" icon={Wallet} title="View USD account" detail="Account number & details"/><ActionButton to="/savings" icon={PiggyBank} title="Manage savings" detail="Vaults & interest"/><ActionButton to="/beneficiaries" icon={Users} title="Beneficiaries" detail="Recipients & transfer details"/></div></Panel>
    </section>
    <section className="dashboard-grid lower-grid"><Panel title="Recent activity" subtitle="Latest posted activity" action={<NavLink to="/transactions" className="text-link">View all <ChevronRight size={13}/></NavLink>}><TransactionList limit={4}/></Panel><Panel title="Savings performance" subtitle="Your savings at a glance" action={<NavLink to="/savings" className="text-link">Manage <ChevronRight size={13}/></NavLink>}><div className="savings-summary"><div><span>Total savings</span><strong>{money(customer.savingsBalance)}</strong></div><div className="apy-box"><b>4.50%</b><span>Current APY</span></div></div><div className="progress"><span style={{width:'75%'}}/></div><div className="savings-meta"><span>75% of combined targets</span><b>+$31.25 earned</b></div>{customer.vaults.map(v => <div className="vault-row" key={v.id}><span><i/>{v.name}</span><b>{money(v.balance)}</b></div>)}</Panel></section>
    <section className="security-strip"><div><LockKeyhole size={18}/><div><b>Your account is protected</b><span>Security checks and account controls are available in Settings.</span></div></div><NavLink to="/settings">Review security <ChevronRight size={14}/></NavLink></section>
  </>
}

function TransactionList({ limit }: { limit?: number }) { return <div className="transactions">{customer.transactions.slice(0, limit).map(t => <div className="transaction" key={t.id}><div className={`tx-icon ${t.amount >= 0 ? 'in' : 'out'}`}>{t.amount >= 0 ? <ArrowDownLeft size={15}/> : <ArrowUpRight size={15}/>}</div><div className="tx-main"><b>{t.description}</b><small>{t.date} · {t.time} · {t.reference}</small></div><div className="tx-amount-wrap"><strong className={t.amount >= 0 ? 'positive' : ''}>{t.amount >= 0 ? '+' : ''}{money(t.amount)}</strong><span className="status">{t.status}</span></div></div>)}</div> }

function Accounts() { return <><PageHead eyebrow="ACCOUNTS" title="Your accounts" description="Manage your USD account and view account details." action={<NavLink to="/transfers" className="primary"><Plus size={16}/> Add funds</NavLink>}/><section className="account-hero"><div><span className="card-eyebrow">PRIMARY USD ACCOUNT</span><h2>USD Personal Account</h2><p>Available balance</p><strong>{money(customer.availableBalance)}</strong></div><div className="account-number"><span>ACCOUNT NUMBER</span><b>•••• 4821</b><small>Checking · USD</small></div></section><section className="account-grid"><Panel title="Account details" subtitle="Information for your primary USD account"><div className="detail-grid"><div><span>Account type</span><b>Personal checking</b></div><div><span>Currency</span><b>United States Dollar (USD)</b></div><div><span>Account status</span><b className="green-text">Active</b></div><div><span>Opened</span><b>August 2026</b></div><div><span>Available balance</span><b>{money(customer.availableBalance)}</b></div><div><span>Pending balance</span><b>$0.00</b></div></div></Panel><Panel title="Account actions" subtitle="Move money or manage your account"><div className="action-list"><ActionButton to="/transfers" icon={ArrowDownLeft} title="Deposit" detail="Add simulated USD funds"/><ActionButton to="/transfers" icon={ArrowUpRight} title="Withdraw" detail="Move funds out"/><ActionButton to="/transactions" icon={Activity} title="View activity" detail="Review transactions"/></div></Panel></section></> }

function Savings() { return <><PageHead eyebrow="SAVINGS" title="Save with purpose." description="Organize your USD savings into dedicated vaults and track your progress." action={<button className="primary"><Plus size={16}/> Create vault</button>}/><section className="savings-overview"><article><span>TOTAL SAVINGS</span><strong>{money(customer.savingsBalance)}</strong><small>Across 3 savings vaults</small></article><article><span>CURRENT APY</span><strong>4.50%</strong><small>Annual percentage yield</small></article><article><span>INTEREST EARNED</span><strong className="positive">+{money(customer.interestEarned)}</strong><small>This period</small></article></section><section className="vault-grid">{customer.vaults.map(v => <article className="vault-card" key={v.id}><div className="vault-head"><span className="vault-dot"/><button aria-label="Vault options"><MoreHorizontal size={17}/></button></div><span className="vault-label">SAVINGS VAULT</span><h3>{v.name}</h3><strong>{money(v.balance)}</strong><div className="vault-target"><span>Target {money(v.target)}</span><b>{Math.round(v.balance / v.target * 100)}%</b></div><div className="progress"><span style={{width:`${Math.round(v.balance / v.target * 100)}%`}}/></div><div className="vault-foot"><span>{v.apy.toFixed(2)}% APY</span><NavLink to="#">View details <ChevronRight size={12}/></NavLink></div></article>)}<button className="new-vault"><Plus size={20}/><b>Create a savings vault</b><span>Set a goal and start building toward it.</span></button></section></> }

function Transfers() { return <><PageHead eyebrow="MOVE MONEY" title="Move money" description="Deposit, withdraw, or send simulated USD securely."/><section className="transfer-grid"><ActionButton to="#" icon={ArrowDownLeft} title="Deposit USD" detail="Add simulated funds to your account"/><ActionButton to="#" icon={ArrowUpRight} title="Withdraw USD" detail="Move funds out of your account"/><ActionButton to="#" icon={MoveRight} title="Send USD" detail="Transfer to a beneficiary"/></section><Panel title="Recent recipients" subtitle="Beneficiaries you can send to"><div className="recipient-list"><div><span className="recipient-avatar">AS</span><div><b>Alex Smith</b><small>•••• 1920 · USD</small></div><ChevronRight size={15}/></div><div><span className="recipient-avatar">MJ</span><div><b>Maria Johnson</b><small>•••• 4472 · USD</small></div><ChevronRight size={15}/></div></div></Panel></> }

function Transactions() { return <><PageHead eyebrow="ACTIVITY" title="Transactions" description="A complete record of your simulated account activity." action={<button className="secondary"><FileText size={15}/> Export statement</button>}/><Panel title="All transactions" subtitle={`${customer.transactions.length} posted transactions`}><div className="transaction-table"><div className="table-head"><span>TRANSACTION</span><span>DATE</span><span>REFERENCE</span><span>AMOUNT</span><span>STATUS</span></div>{customer.transactions.map(t => <div className="table-row" key={t.id}><div className="table-name"><span className={`tx-icon ${t.amount >= 0 ? 'in' : 'out'}`}>{t.amount >= 0 ? <ArrowDownLeft size={15}/> : <ArrowUpRight size={15}/>}</span><div><b>{t.description}</b><small>{t.kind} · {t.currency}</small></div></div><span>{t.date}</span><span>{t.reference}</span><strong className={t.amount >= 0 ? 'positive' : ''}>{t.amount >= 0 ? '+' : ''}{money(t.amount)}</strong><span className="status">{t.status}</span></div>)}</div></Panel></> }

function Cards() { return <><PageHead eyebrow="CARDS" title="Your cards" description="Manage your simulated FOXSYCU cards and card controls." action={<button className="primary"><Plus size={16}/> Add card</button>}/><section className="card-product"><div className="virtual-card"><div className="vc-top"><span>FOXSYCU</span><span>USD</span></div><div className="chip"/><div className="vc-number">•••• &nbsp; •••• &nbsp; •••• &nbsp; 4821</div><div className="vc-bottom"><span>JOHN DOE</span><span>09/29</span></div></div><Panel title="Primary card" subtitle="Virtual debit card"><div className="card-details"><div><span>Status</span><b className="green-text">Active</b></div><div><span>Card type</span><b>Virtual debit</b></div><div><span>Currency</span><b>USD</b></div><div><span>Last four</span><b>4821</b></div></div><button className="secondary full">Manage card controls</button></Panel></section><div className="info-note"><ShieldCheck size={17}/><span>Card data in this environment is simulated. No real card network or payment processor is connected.</span></div></> }

function GenericPage({ title, icon: Icon, description }: { title: string; icon: typeof FileText; description: string }) { return <><PageHead eyebrow="FOXSYCU CUSTOMER APPLICATION" title={title} description={description}/><Panel title="Coming into focus" subtitle="This area is part of the production application architecture."><div className="empty-state"><span><Icon size={20}/></span><b>{title} is ready for the next workflow stage.</b><p>The navigation, information architecture, responsive shell, and reusable FOXSYCU components are in place. Detailed workflow behavior will be added deliberately without connecting real financial infrastructure.</p></div></Panel></> }

function AppRoutes() { return <Routes><Route path="/" element={<Dashboard/>}/><Route path="/accounts" element={<Accounts/>}/><Route path="/savings" element={<Savings/>}/><Route path="/transfers" element={<Transfers/>}/><Route path="/cards" element={<Cards/>}/><Route path="/transactions" element={<Transactions/>}/><Route path="/statements" element={<GenericPage title="Statements" icon={FileText} description="Review and export account statements."/>}/><Route path="/beneficiaries" element={<GenericPage title="Beneficiaries" icon={Users} description="Manage trusted recipients for USD transfers."/>}/><Route path="/messages" element={<GenericPage title="Messages" icon={MessageSquare} description="Secure communication and account notifications."/>}/><Route path="/support" element={<GenericPage title="Help & Support" icon={HelpCircle} description="Get help with your FOXSYCU account."/>}/><Route path="/settings" element={<GenericPage title="Settings & Security" icon={ShieldCheck} description="Manage profile, security, devices, and account preferences."/>}/><Route path="/profile" element={<GenericPage title="Profile" icon={User} description="Manage your personal account information."/>}/></Routes> }
export default function App() { return <Shell><AppRoutes/></Shell> }
