import { NavLink, Routes, Route, useLocation, useNavigate } from 'react-router-dom'
import { Activity, ArrowDownLeft, ArrowUpRight, Bell, ChevronDown, ChevronRight, CreditCard, FileText, HelpCircle, Home, LockKeyhole, LogOut, Menu, MessageSquare, MoreHorizontal, MoveRight, PiggyBank, Plus, Search, Settings, ShieldCheck, User, Users, Wallet, X } from 'lucide-react'
import { useMemo, useState } from 'react'
import { customer } from './data/mockData'
import { refreshCustomerSnapshot, runtimeEngine, useRuntimeRefresh } from './data/runtimeBanking'
import { supabase } from './supabaseClient'

const nav = [
  ['Dashboard', '/', Home], ['Accounts', '/accounts', Wallet], ['Savings', '/savings', PiggyBank], ['Transfers', '/transfers', MoveRight], ['Cards', '/cards', CreditCard], ['Transactions', '/transactions', Activity], ['Statements', '/statements', FileText], ['Beneficiaries', '/beneficiaries', Users], ['Messages', '/messages', MessageSquare], ['Support', '/support', HelpCircle], ['Settings', '/settings', Settings],
] as const

const money = (value: number) => `${value < 0 ? '-' : ''}$${Math.abs(value).toLocaleString('en-US', { minimumFractionDigits: 2, maximumFractionDigits: 2 })}`

function Brand() {
  return <div className="brand-lockup" aria-label="FOXSYCU Digital Banking System"><div className="brand-mark">F</div><div><strong>FOXSYCU</strong><span>DIGITAL BANKING SYSTEM</span></div></div>
}

function Shell({ children }: { children: React.ReactNode }) {
  const [open, setOpen] = useState(false)
  const [accountOpen, setAccountOpen] = useState(false)
  const [profileOpen, setProfileOpen] = useState(false)
  const [notificationsOpen, setNotificationsOpen] = useState(false)
  const [search, setSearch] = useState('')
  const location = useLocation()
  const navigate = useNavigate()
  useRuntimeRefresh()
  const title = location.pathname === '/' ? 'Overview' : location.pathname.slice(1).split('/')[0].replace(/\b\w/g, c => c.toUpperCase())
  const results = useMemo(() => {
    const q = search.trim().toLowerCase()
    if (!q) return []
    return customer.transactions.filter(t => `${t.description} ${t.reference} ${t.kind} ${t.counterparty ?? ''}`.toLowerCase().includes(q)).slice(0, 6)
  }, [search])
  const signOut = async () => { await supabase.auth.signOut(); navigate('/login', { replace: true }) }
  return <div className="app-shell">
    <aside className={open ? 'sidebar open' : 'sidebar'}>
      <div className="sidebar-top"><Brand/><button className="close-mobile" onClick={() => setOpen(false)} aria-label="Close navigation"><X size={18}/></button></div>
      <button className="account-switcher" onClick={() => setAccountOpen(v => !v)} aria-expanded={accountOpen}><div className="mini-avatar">JD</div><div><strong>John Doe</strong><span>Personal · USD</span></div><ChevronDown size={14}/></button>
      {accountOpen && <div className="shell-popover"><b>Personal USD</b><span>Primary checking · •••• 4821</span><button onClick={() => setAccountOpen(false)}>Current account</button></div>}
      <nav className="desktop-nav" aria-label="Primary navigation">{nav.map(([label, path, Icon]) => <NavLink key={path} to={path} end={path === '/'} onClick={() => setOpen(false)} className={({isActive}) => isActive ? 'nav-item active' : 'nav-item'}><Icon size={17}/><span>{label}</span></NavLink>)}</nav>
      <div className="sidebar-footer"><div className="security-note"><ShieldCheck size={15}/><span>Protected & encrypted</span></div><button className="logout" onClick={() => void signOut}><LogOut size={15}/> Sign out</button></div>
    </aside>
    <div className="main-area">
      <header className="topbar"><div className="topbar-left"><button className="menu" onClick={() => setOpen(true)} aria-label="Open navigation"><Menu size={21}/></button><div><span className="top-kicker">FOXSYCU / CUSTOMER</span><span className="top-title">{title}</span></div></div><div className="top-actions">
        <div className="search-wrap"><label className="search"><Search size={16}/><input value={search} onChange={e => setSearch(e.target.value)} placeholder="Search FOXSYCU" aria-label="Search"/></label>{search && <div className="search-results">{results.length ? results.map(t => <button key={t.id} onClick={() => { setSearch(''); navigate('/transactions') }}><span>{t.description}</span><small>{t.reference} · {money(t.amount)}</small></button>) : <span>No matching transactions</span>}</div>}</div>
        <button className="icon-btn" aria-label="Notifications" onClick={() => setNotificationsOpen(v => !v)}><Bell size={18}/><i/></button>
        <NavLink to="/messages" className="icon-btn" aria-label="Messages"><MessageSquare size={18}/></NavLink>
        <button className="profile" onClick={() => setProfileOpen(v => !v)} aria-expanded={profileOpen}><span className="avatar">JD</span><span className="profile-text"><strong>John Doe</strong><small>Premium User</small></span><ChevronDown size={14}/></button>
        {profileOpen && <div className="shell-popover profile-popover"><b>John Doe</b><span>Premium User · Personal USD</span><button onClick={() => { setProfileOpen(false); navigate('/profile') }}>View profile</button><button onClick={() => { setProfileOpen(false); navigate('/settings') }}>Settings & security</button><button onClick={() => void signOut}>Sign out</button></div>}
        {notificationsOpen && <div className="shell-popover notification-popover"><b>Notifications</b><span>Your account is secure and up to date.</span><button onClick={() => { setNotificationsOpen(false); navigate('/messages') }}>Open messages</button></div>}
      </div></header>
      <main className="content">{children}</main>
    </div>
    <nav className="mobile-nav" aria-label="Mobile navigation">{[['Home','/',Home],['Savings','/savings',PiggyBank],['Activity','/transactions',Activity],['Move','/transfers',MoveRight],['Profile','/profile',User]].map(([label,path,Icon]) => <NavLink key={label as string} to={path as string} end={path === '/'}>{<Icon size={19}/>}<span>{label as string}</span></NavLink>)}</nav>
  </div>
}

function PageHead({ eyebrow, title, description, action }: { eyebrow: string; title: string; description?: string; action?: React.ReactNode }) { return <section className="page-head"><div><p className="eyebrow">{eyebrow}</p><h1>{title}</h1>{description && <p>{description}</p>}</div>{action}</section> }
function Panel({ title, subtitle, action, children, className='' }: { title: string; subtitle?: string; action?: React.ReactNode; children: React.ReactNode; className?: string }) { return <article className={`panel ${className}`}><div className="panel-head"><div><h2>{title}</h2>{subtitle && <p>{subtitle}</p>}</div>{action}</div>{children}</article> }
function ActionButton({ to, icon: Icon, title, detail }: { to: string; icon: typeof ArrowUpRight; title: string; detail: string }) { return <NavLink to={to} className="action-tile"><span className="action-icon"><Icon size={17}/></span><span><b>{title}</b><small>{detail}</small></span><ChevronRight size={15}/></NavLink> }

function MoneyModal({ mode, close }: { mode: 'send' | 'withdraw'; close: () => void }) {
  const [amount, setAmount] = useState('')
  const [beneficiary, setBeneficiary] = useState('Alex Smith')
  const [memo, setMemo] = useState('')
  const [error, setError] = useState('')
  const [success, setSuccess] = useState('')
  const [busy, setBusy] = useState(false)
  const submit = () => {
    setError(''); setSuccess(''); setBusy(true)
    try {
      const value = Number(amount)
      if (mode === 'send') runtimeEngine.send({ amount: value, beneficiary, memo })
      else runtimeEngine.withdraw({ amount: value, memo })
      refreshCustomerSnapshot(); setSuccess(mode === 'send' ? 'Transfer completed successfully.' : 'Withdrawal completed successfully.'); setAmount(''); setMemo('')
    } catch (e) { setError(e instanceof Error ? e.message : 'Transaction could not be completed.') } finally { setBusy(false) }
  }
  return <div className="modal-backdrop" role="presentation" onMouseDown={e => { if (e.target === e.currentTarget) close() }}><section className="modal" role="dialog" aria-modal="true" aria-labelledby="money-title"><div className="modal-head"><div><p className="eyebrow">MOVE MONEY · USD</p><h2 id="money-title">{mode === 'send' ? 'Send USD' : 'Withdraw USD'}</h2></div><button className="icon-btn" onClick={close} aria-label="Close"><X size={18}/></button></div><div className="modal-body"><div className="modal-summary"><span>Available balance</span><strong>{money(customer.availableBalance)}</strong></div>{mode === 'send' && <label><span>Beneficiary</span><select value={beneficiary} onChange={e => setBeneficiary(e.target.value)}><option>Alex Smith</option><option>Maria Johnson</option><option>Northstar Holdings</option></select></label>}<label><span>Amount (USD)</span><input value={amount} onChange={e => setAmount(e.target.value)} inputMode="decimal" placeholder="0.00" autoFocus/></label><label><span>Memo (optional)</span><input value={memo} onChange={e => setMemo(e.target.value)} placeholder="Payment reference"/></label>{error && <p role="alert" className="error-text">{error}</p>}{success && <p className="green-text">{success}</p>}</div><div className="modal-foot"><button className="secondary" onClick={close}>Cancel</button><button className="primary" disabled={busy} onClick={submit}>{busy ? 'Processing…' : 'Review & confirm'}</button></div></section></div>
}

function DepositModal({ close }: { close: () => void }) {
  const [requested, setRequested] = useState(false)
  return <div className="modal-backdrop" role="presentation" onMouseDown={e => { if (e.target === e.currentTarget) close() }}><section className="modal" role="dialog" aria-modal="true" aria-labelledby="deposit-title"><div className="modal-head"><div><p className="eyebrow">MOVE MONEY · USD</p><h2 id="deposit-title">Deposit USD</h2></div><button className="icon-btn" onClick={close} aria-label="Close"><X size={18}/></button></div><div className="modal-body"><div className="modal-summary"><span>Current available balance</span><strong>{money(customer.availableBalance)}</strong></div>{requested ? <div className="success-box"><b>Deposit request recorded</b><span>The request is queued for administrative approval. No customer balance was changed.</span></div> : <p className="modal-note">Customer deposits are controlled by the administrative funding workflow in this environment. You can submit a request without changing the customer ledger.</p>}</div><div className="modal-foot"><button className="secondary" onClick={close}>Close</button>{!requested && <button className="primary" onClick={() => setRequested(true)}>Request admin review</button>}</div></section></div>
}

function VaultModal({ vault, close }: { vault?: typeof customer.vaults[number]; close: () => void }) {
  const [created, setCreated] = useState(false)
  const target = vault?.target ?? 0
  const progress = target > 0 ? Math.min(100, Math.round(vault!.balance / target * 100)) : 0
  return <div className="modal-backdrop" role="presentation" onMouseDown={e => { if (e.target === e.currentTarget) close() }}><section className="modal" role="dialog" aria-modal="true" aria-labelledby="vault-title"><div className="modal-head"><div><p className="eyebrow">SAVINGS</p><h2 id="vault-title">{vault ? vault.name : 'Create a savings vault'}</h2></div><button className="icon-btn" onClick={close} aria-label="Close"><X size={18}/></button></div><div className="modal-body">{vault ? <><div className="modal-summary"><span>Current balance</span><strong>{money(vault.balance)}</strong></div><div className="detail-grid"><div><span>Target</span><b>{money(target)}</b></div><div><span>Progress</span><b>{progress}%</b></div><div><span>APY</span><b>{vault.apy.toFixed(2)}%</b></div><div><span>Interest earned</span><b>{money(vault.interestEarned ?? 0)}</b></div></div></> : created ? <div className="success-box"><b>Vault setup opened</b><span>The vault creation workflow is ready for the next savings configuration step.</span></div> : <><label><span>Vault name</span><input defaultValue="New savings goal"/></label><label><span>Target amount (USD)</span><input defaultValue="10000" inputMode="decimal"/></label></>}</div><div className="modal-foot"><button className="secondary" onClick={close}>Close</button>{!vault && !created && <button className="primary" onClick={() => setCreated(true)}>Create vault</button>}</div></section></div>
}

function Dashboard() {
  const [period, setPeriod] = useState('30 days')
  const totalTarget = customer.vaults.reduce((sum, v) => sum + (v.target ?? 0), 0)
  const progress = totalTarget > 0 ? Math.min(100, Math.round(customer.vaults.reduce((sum, v) => sum + v.balance, 0) / totalTarget * 100)) : 0
  return <>
    <PageHead eyebrow="PERSONAL BANKING · USD" title={`Good morning, ${customer.name.split(' ')[0]}.`} description="Here is your financial position and recent account activity." action={<div className="head-actions"><NavLink to="/transactions" className="secondary">View activity</NavLink><NavLink to="/transfers" className="primary"><MoveRight size={16}/> Move money</NavLink></div>}/>
    <section className="hero-grid"><article className="balance-card"><div className="balance-top"><div><span className="card-eyebrow">TOTAL AVAILABLE BALANCE</span><span className="currency-pill">USD</span></div><NavLink className="card-more" to="/accounts" aria-label="Balance options"><MoreHorizontal size={18}/></NavLink></div><div className="balance">{money(customer.availableBalance)}</div><div className="balance-meta"><span>Available to move</span><span className="secure-inline"><ShieldCheck size={13}/> Secure account</span></div><div className="balance-actions"><NavLink to="/transfers?mode=deposit"><ArrowDownLeft size={15}/> Deposit</NavLink><NavLink to="/transfers?mode=withdraw"><ArrowUpRight size={15}/> Withdraw</NavLink><NavLink to="/transfers?mode=send"><MoveRight size={15}/> Send USD</NavLink></div></article><div className="side-metrics"><article className="metric-card"><div className="metric-icon blue"><PiggyBank size={17}/></div><span>SAVINGS BALANCE</span><strong>{money(customer.savingsBalance)}</strong><small><b>{customer.apy.toFixed(2)}%</b> APY · Across {customer.vaults.length} vaults</small></article><article className="metric-card"><div className="metric-icon green"><ArrowUpRight size={17}/></div><span>INTEREST EARNED</span><strong className="positive">+{money(customer.interestEarned)}</strong><small>Earned this period</small></article></div></section>
    <section className="dashboard-grid"><Panel title="Balance overview" subtitle={`Available USD balance · ${period}`} action={<select aria-label="Chart period" value={period} onChange={e => setPeriod(e.target.value)}><option>30 days</option><option>90 days</option></select>} className="chart-panel"><div className="chart-value">{money(customer.availableBalance)} <span>Live balance <ArrowUpRight size={12}/></span></div><div className="chart"><div className="gridline g1"/><div className="gridline g2"/><div className="gridline g3"/><svg viewBox="0 0 800 220" preserveAspectRatio="none" aria-label="Balance trend"><defs><linearGradient id="fill" x1="0" x2="0" y1="0" y2="1"><stop offset="0%" stopColor="#155EEF" stopOpacity=".18"/><stop offset="100%" stopColor="#155EEF" stopOpacity="0"/></linearGradient></defs><path d="M0 170 C70 165 95 142 150 151 S235 165 290 128 S380 145 430 104 S520 125 575 89 S650 105 705 70 S755 77 800 40 L800 220 L0 220 Z" fill="url(#fill)"/><path d="M0 170 C70 165 95 142 150 151 S235 165 290 128 S380 145 430 104 S520 125 575 89 S650 105 705 70 S755 77 800 40" fill="none" stroke="#155EEF" strokeWidth="3"/></svg><div className="chart-labels">{period === '30 days' ? <><span>Aug 12</span><span>Aug 19</span><span>Aug 26</span><span>Sep 2</span><span>Sep 10</span></> : <><span>Jun 14</span><span>Jul 1</span><span>Jul 19</span><span>Aug 7</span><span>Sep 10</span></>}</div></div></Panel><Panel title="Quick actions" subtitle="Common account tasks"><div className="action-list"><ActionButton to="/accounts" icon={Wallet} title="View USD account" detail="Account number & details"/><ActionButton to="/savings" icon={PiggyBank} title="Manage savings" detail="Vaults & interest"/><ActionButton to="/beneficiaries" icon={Users} title="Beneficiaries" detail="Recipients & transfer details"/></div></Panel></section>
    <section className="dashboard-grid lower-grid"><Panel title="Recent activity" subtitle="Latest posted activity" action={<NavLink to="/transactions" className="text-link">View all <ChevronRight size={13}/></NavLink>}><TransactionList limit={4}/></Panel><Panel title="Savings performance" subtitle="Your savings at a glance" action={<NavLink to="/savings" className="text-link">Manage <ChevronRight size={13}/></NavLink>}><div className="savings-summary"><div><span>Total savings</span><strong>{money(customer.savingsBalance)}</strong></div><div className="apy-box"><b>{customer.apy.toFixed(2)}%</b><span>Current APY</span></div></div><div className="progress"><span style={{width:`${progress}%`}}/></div><div className="savings-meta"><span>{progress}% of combined targets</span><b>+{money(customer.interestEarned)} earned</b></div>{customer.vaults.map(v => <div className="vault-row" key={v.id}><span><i/>{v.name}</span><b>{money(v.balance)}</b></div>)}</Panel></section><section className="security-strip"><div><LockKeyhole size={18}/><div><b>Your account is protected</b><span>Security checks and account controls are available in Settings.</span></div></div><NavLink to="/settings">Review security <ChevronRight size={14}/></NavLink></section>
  </>
}

function TransactionList({ limit }: { limit?: number }) { return <div className="transactions">{customer.transactions.slice(0, limit).map(t => <div className="transaction" key={t.id}><div className={`tx-icon ${t.amount >= 0 ? 'in' : 'out'}`}>{t.amount >= 0 ? <ArrowDownLeft size={15}/> : <ArrowUpRight size={15}/>}</div><div className="tx-main"><b>{t.description}</b><small>{t.date} · {t.time} · {t.reference}</small></div><div className="tx-amount-wrap"><strong className={t.amount >= 0 ? 'positive' : ''}>{t.amount >= 0 ? '+' : ''}{money(t.amount)}</strong><span className="status">{t.status}</span></div></div>)}</div> }

function Accounts() { return <><PageHead eyebrow="ACCOUNTS" title="Your accounts" description="Manage your USD account and view account details." action={<NavLink to="/transfers?mode=deposit" className="primary"><Plus size={16}/> Add funds</NavLink>}/><section className="account-hero"><div><span className="card-eyebrow">PRIMARY USD ACCOUNT</span><h2>USD Personal Account</h2><p>Available balance</p><strong>{money(customer.availableBalance)}</strong></div><div className="account-number"><span>ACCOUNT NUMBER</span><b>•••• 4821</b><small>Checking · USD</small></div></section><section className="account-grid"><Panel title="Account details" subtitle="Information for your primary USD account"><div className="detail-grid"><div><span>Account type</span><b>Personal checking</b></div><div><span>Currency</span><b>United States Dollar (USD)</b></div><div><span>Account status</span><b className="green-text">Active</b></div><div><span>Opened</span><b>August 2026</b></div><div><span>Available balance</span><b>{money(customer.availableBalance)}</b></div><div><span>Pending balance</span><b>$0.00</b></div></div></Panel><Panel title="Account actions" subtitle="Move money or manage your account"><div className="action-list"><ActionButton to="/transfers?mode=deposit" icon={ArrowDownLeft} title="Deposit" detail="Request a deposit"/><ActionButton to="/transfers?mode=withdraw" icon={ArrowUpRight} title="Withdraw" detail="Move funds out"/><ActionButton to="/transactions" icon={Activity} title="View activity" detail="Review transactions"/></div></Panel></section></> }

function Savings() { const [vault, setVault] = useState<typeof customer.vaults[number] | undefined>(); const [create, setCreate] = useState(false); const [options, setOptions] = useState<string | null>(null); return <><PageHead eyebrow="SAVINGS" title="Save with purpose." description="Organize your USD savings into dedicated vaults and track your progress." action={<button className="primary" onClick={() => setCreate(true)}><Plus size={16}/> Create vault</button>}/><section className="savings-overview"><article><span>TOTAL SAVINGS</span><strong>{money(customer.savingsBalance)}</strong><small>Across {customer.vaults.length} savings vaults</small></article><article><span>CURRENT APY</span><strong>{customer.apy.toFixed(2)}%</strong><small>Annual percentage yield</small></article><article><span>INTEREST EARNED</span><strong className="positive">+{money(customer.interestEarned)}</strong><small>This period</small></article></section><section className="vault-grid">{customer.vaults.map(v => { const target=v.target ?? 0; const pct=target ? Math.min(100,Math.round(v.balance/target*100)) : 0; return <article className="vault-card" key={v.id}><div className="vault-head"><span className="vault-dot"/><button onClick={() => setOptions(options === v.id ? null : v.id)} aria-label={`Vault options for ${v.name}`}><MoreHorizontal size={17}/></button>{options === v.id && <div className="vault-menu"><button onClick={() => { setVault(v); setOptions(null) }}>View details</button><button onClick={() => { setVault(v); setOptions(null) }}>Manage vault</button></div>}</div><span className="vault-label">SAVINGS VAULT</span><h3>{v.name}</h3><strong>{money(v.balance)}</strong><div className="vault-target"><span>Target {money(target)}</span><b>{pct}%</b></div><div className="progress"><span style={{width:`${pct}%`}}/></div><div className="vault-foot"><span>{v.apy.toFixed(2)}% APY</span><button className="text-link" onClick={() => setVault(v)}>View details <ChevronRight size={12}/></button></div></article>})}<button className="new-vault" onClick={() => setCreate(true)}><Plus size={20}/><b>Create a savings vault</b><span>Set a goal and start building toward it.</span></button></section>{(vault || create) && <VaultModal vault={vault} close={() => { setVault(undefined); setCreate(false) }}/>}</> }

function Transfers() { const params = new URLSearchParams(useLocation().search); const initial = params.get('mode') as 'send'|'withdraw'|'deposit'|null; const [mode,setMode]=useState<'send'|'withdraw'|'deposit'|null>(initial); return <><PageHead eyebrow="MOVE MONEY" title="Move money" description="Deposit, withdraw, or send simulated USD securely."/><section className="transfer-grid"><button className="action-tile" onClick={() => setMode('deposit')}><span className="action-icon"><ArrowDownLeft size={17}/></span><span><b>Deposit USD</b><small>Request simulated funds</small></span><ChevronRight size={15}/></button><button className="action-tile" onClick={() => setMode('withdraw')}><span className="action-icon"><ArrowUpRight size={17}/></span><span><b>Withdraw USD</b><small>Move funds out of your account</small></span><ChevronRight size={15}/></button><button className="action-tile" onClick={() => setMode('send')}><span className="action-icon"><MoveRight size={17}/></span><span><b>Send USD</b><small>Transfer to a beneficiary</small></span><ChevronRight size={15}/></button></section>{mode==='send' && <MoneyModal mode="send" close={() => setMode(null)}/>} {mode==='withdraw' && <MoneyModal mode="withdraw" close={() => setMode(null)}/>} {mode==='deposit' && <DepositModal close={() => setMode(null)}/>}<Panel title="Recent recipients" subtitle="Beneficiaries you can send to"><div className="recipient-list"><div><span className="recipient-avatar">AS</span><div><b>Alex Smith</b><small>•••• 1920 · USD</small></div><ChevronRight size={15}/></div><div><span className="recipient-avatar">MJ</span><div><b>Maria Johnson</b><small>•••• 4472 · USD</small></div><ChevronRight size={15}/></div><div><span className="recipient-avatar">NH</span><div><b>Northstar Holdings</b><small>•••• 8104 · USD</small></div><ChevronRight size={15}/></div></div></Panel></> }

function exportStatement() { const rows = [['Date','Time','Description','Reference','Amount','Status'], ...customer.transactions.map(t => [t.date,t.time,t.description,t.reference,String(t.amount.toFixed(2)),t.status])]; const csv=rows.map(row=>row.map(cell=>`"${cell.replaceAll('"','""')}"`).join(',')).join('\n'); const blob=new Blob([csv],{type:'text/csv;charset=utf-8'}); const url=URL.createObjectURL(blob); const a=document.createElement('a'); a.href=url; a.download='foxsycu-statement.csv'; a.click(); URL.revokeObjectURL(url) }
function Transactions() { return <><PageHead eyebrow="ACTIVITY" title="Transactions" description="A complete record of your simulated account activity." action={<button className="secondary" onClick={exportStatement}><FileText size={15}/> Export statement</button>}/><Panel title="All transactions" subtitle={`${customer.transactions.length} posted transactions`}><div className="transaction-table"><div className="table-head"><span>TRANSACTION</span><span>DATE</span><span>REFERENCE</span><span>AMOUNT</span><span>STATUS</span></div>{customer.transactions.map(t => <div className="table-row" key={t.id}><div className="table-name"><span className={`tx-icon ${t.amount >= 0 ? 'in' : 'out'}`}>{t.amount >= 0 ? <ArrowDownLeft size={15}/> : <ArrowUpRight size={15}/>}</span><div><b>{t.description}</b><small>{t.kind} · {t.currency}</small></div></div><span>{t.date}</span><span>{t.reference}</span><strong className={t.amount >= 0 ? 'positive' : ''}>{t.amount >= 0 ? '+' : ''}{money(t.amount)}</strong><span className="status">{t.status}</span></div>)}</div></Panel></> }

function Cards() { return <><PageHead eyebrow="CARDS" title="Your cards" description="Manage your simulated FOXSYCU cards and card controls." action={<button className="primary"><Plus size={16}/> Add card</button>}/><section className="card-product"><div className="virtual-card"><div className="vc-top"><span>FOXSYCU</span><span>USD</span></div><div className="chip"/><div className="vc-number">•••• &nbsp; •••• &nbsp; •••• &nbsp; 4821</div><div className="vc-bottom"><span>JOHN DOE</span><span>09/29</span></div></div><Panel title="Primary card" subtitle="Virtual debit card"><div className="card-details"><div><span>Status</span><b className="green-text">Active</b></div><div><span>Card type</span><b>Virtual debit</b></div><div><span>Currency</span><b>USD</b></div><div><span>Last four</span><b>4821</b></div></div><button className="secondary full">Manage card controls</button></Panel></section><div className="info-note"><ShieldCheck size={17}/><span>Card data in this environment is simulated. No real card network or payment processor is connected.</span></div></> }

function GenericPage({ title, icon: Icon, description }: { title: string; icon: typeof FileText; description: string }) { return <><PageHead eyebrow="FOXSYCU CUSTOMER APPLICATION" title={title} description={description}/><Panel title="Coming into focus" subtitle="This area is part of the production application architecture."><div className="empty-state"><span><Icon size={20}/></span><b>{title} is ready for the next workflow stage.</b><p>The navigation, information architecture, responsive shell, and reusable FOXSYCU components are in place. Detailed workflow behavior will be added deliberately without connecting real financial infrastructure.</p></div></Panel></> }

function AppRoutes() { return <Routes><Route path="/" element={<Dashboard/>}/><Route path="/accounts" element={<Accounts/>}/><Route path="/savings" element={<Savings/>}/><Route path="/transfers" element={<Transfers/>}/><Route path="/cards" element={<Cards/>}/><Route path="/transactions" element={<Transactions/>}/><Route path="/statements" element={<GenericPage title="Statements" icon={FileText} description="Review and export account statements."/>}/><Route path="/beneficiaries" element={<GenericPage title="Beneficiaries" icon={Users} description="Manage trusted recipients for USD transfers."/>}/><Route path="/messages" element={<GenericPage title="Messages" icon={MessageSquare} description="Secure communication and account notifications."/>}/><Route path="/support" element={<GenericPage title="Help & Support" icon={HelpCircle} description="Get help with your FOXSYCU account."/>}/><Route path="/settings" element={<GenericPage title="Settings & Security" icon={ShieldCheck} description="Manage profile, security, devices, and account preferences."/>}/><Route path="/profile" element={<GenericPage title="Profile" icon={User} description="Manage your personal account information."/>}/></Routes> }
export default function App() { return <Shell><AppRoutes/></Shell> }
