import { useMemo, useState } from 'react'
import { NavLink } from 'react-router-dom'
import { ArrowRight, FileText, LockKeyhole, Plus, ShieldCheck, Trash2, Users } from 'lucide-react'
import { customer as seed } from './data/mockData'
import './core-banking-services.css'

const money = (n: number) => `${n < 0 ? '-' : ''}$${Math.abs(n).toLocaleString('en-US', { minimumFractionDigits: 2, maximumFractionDigits: 2 })}`
const ACCOUNT = '•••• 4821'
type SavedBeneficiary = { id: string; name: string; account: string }

function Page({ eyebrow, title, description, children }: { eyebrow: string; title: string; description: string; children: React.ReactNode }) { return <div className="core-page"><header className="core-top"><NavLink to="/" className="core-brand"><span>F</span><div><b>FOXSYCU</b><small>DIGITAL BANKING SYSTEM</small></div></NavLink><nav><NavLink to="/">Overview</NavLink><NavLink to="/accounts">Accounts</NavLink><NavLink to="/transfers">Move money</NavLink><NavLink to="/transactions">Activity</NavLink></nav><NavLink className="core-secure" to="/security"><ShieldCheck size={16}/>Security</NavLink></header><main className="core-main"><div className="core-heading"><div><span>{eyebrow}</span><h1>{title}</h1><p>{description}</p></div><NavLink to="/" className="core-back">Back to overview</NavLink></div>{children}</main></div> }
function Card({ title, note, children }: { title: string; note?: string; children: React.ReactNode }) { return <section className="core-card"><div className="core-card-head"><div><h2>{title}</h2>{note && <p>{note}</p>}</div></div>{children}</section> }

export function BeneficiariesPage() {
  const initial: SavedBeneficiary[] = [{ id: 'alex', name: 'Alex Smith', account: '••••1920' }, { id: 'maria', name: 'Maria Johnson', account: '••••4472' }, { id: 'northstar', name: 'Northstar Holdings', account: '••••8104' }]
  const [items, setItems] = useState<SavedBeneficiary[]>(initial)
  const [adding, setAdding] = useState(false); const [name, setName] = useState(''); const [account, setAccount] = useState('')
  const add = () => { if (!name.trim() || account.length < 4) return; setItems(v => [...v, { id: `ben-${Date.now()}`, name: name.trim(), account: `••••${account.slice(-4)}` }]); setName(''); setAccount(''); setAdding(false) }
  return <Page eyebrow="BENEFICIARIES" title="Recipients you trust" description="Manage saved recipients before sending transfers, wires or payments."><Card title="Saved beneficiaries" note={`${items.length} saved recipients`}><div className="core-list">{items.map(b => <div className="core-row" key={b.id}><span className="core-avatar"><Users size={18}/></span><div><b>{b.name}</b><small>Account {b.account}</small></div><NavLink className="core-text-action" to={`/transfers?recipient=${encodeURIComponent(b.name)}`}>Send money <ArrowRight size={14}/></NavLink><button className="core-icon-action" onClick={() => setItems(v => v.filter(x => x.id !== b.id))} aria-label={`Remove ${b.name}`}><Trash2 size={16}/></button></div>)}</div>{adding ? <div className="core-form"><label>Name<input value={name} onChange={e => setName(e.target.value)} placeholder="Recipient name"/></label><label>Account number<input value={account} onChange={e => setAccount(e.target.value.replace(/\D/g, ''))} inputMode="numeric" placeholder="Last 4 digits" maxLength={4}/></label><div className="core-actions"><button className="secondary" onClick={() => setAdding(false)}>Cancel</button><button className="primary" disabled={!name.trim() || account.length < 4} onClick={add}>Save beneficiary</button></div></div> : <button className="primary" onClick={() => setAdding(true)}><Plus size={16}/>Add beneficiary</button>}</Card><Card title="Before you send" note="Security guidance"><div className="core-notice"><ShieldCheck/><div><b>Review recipient details carefully</b><small>Transfers can be difficult to reverse once authorized. Confirm the name and account before continuing.</small></div></div></Card></Page>
}

export function SavingsPage() { const [vaults, setVaults] = useState(seed.savingsVaults ?? seed.vaults); const [selected, setSelected] = useState<string | null>(null); const total = vaults.reduce((s, v) => s + v.balance, 0); return <Page eyebrow="SAVINGS" title="Savings & vaults" description="Organize your USD savings by purpose while keeping every balance visible."><section className="core-hero"><div><span>TOTAL SAVINGS</span><strong>{money(total)}</strong><p>{seed.apy.toFixed(2)}% APY · USD</p></div><div><span>INTEREST EARNED</span><b>{money(seed.interestEarned)}</b><small>Current relationship</small></div></section><div className="core-grid">{vaults.map(v => <Card key={v.id} title={v.name} note={`Target ${money(v.target)}`}><div className="vault-balance"><strong>{money(v.balance)}</strong><span>{Math.round((v.balance / v.target) * 100)}% funded</span></div><div className="progress"><i style={{ width: `${Math.min(100, (v.balance / v.target) * 100)}%` }}/></div><div className="core-actions"><button className="secondary" onClick={() => setSelected(v.id)}>Manage</button><NavLink className="primary" to="/transfers?mode=transfer">Move money</NavLink></div></Card>)}</div>{selected && <div className="core-overlay" role="dialog" aria-modal="true"><div className="core-dialog"><button className="core-close" onClick={() => setSelected(null)}>×</button><span>SAVINGS VAULT</span><h2>{vaults.find(v => v.id === selected)?.name}</h2><p>Transfers to and from this vault are reviewed before authorization.</p><NavLink className="primary full" to="/transfers?mode=transfer" onClick={() => setSelected(null)}>Open transfer flow</NavLink></div></div>}</Page> }

export function CardsPage() { const [frozen, setFrozen] = useState(false); const [show, setShow] = useState(false); return <Page eyebrow="CARDS" title="Cards & payment controls" description="Manage card visibility and security controls for your banking relationship."><Card title="Private Banking Card" note="Virtual card · •••• 4821"><div className={`bank-card-visual ${frozen ? 'frozen' : ''}`}><div><b>FOXSYCU</b><small>PRIVATE BANKING</small></div><strong>•••• 4821</strong><span>JOHN DOE</span></div><div className="core-card-controls"><div><b>{frozen ? 'Card frozen' : 'Card active'}</b><small>{frozen ? 'New purchases are blocked.' : 'Purchases are currently permitted.'}</small></div><button className={frozen ? 'primary' : 'secondary'} onClick={() => setFrozen(v => !v)}>{frozen ? 'Unfreeze card' : 'Freeze card'}</button><button className="secondary" onClick={() => setShow(v => !v)}>{show ? 'Hide details' : 'View details'}</button></div></Card><Card title="Security controls" note="Keep card activity under your control"><div className="core-detail"><span>Online purchases</span><b>Enabled</b></div><div className="core-detail"><span>Contactless</span><b>Enabled</b></div><div className="core-detail"><span>Card status</span><b>{frozen ? 'Frozen' : 'Active'}</b></div>{show && <div className="core-notice"><LockKeyhole/><div><b>Card number protected</b><small>Only the last four digits are shown in the customer interface.</small></div></div>}</Card></Page> }

export function StatementsPage() { const months = useMemo(() => ['September 2026','August 2026','July 2026','June 2026','May 2026','April 2026','March 2026','February 2026','January 2026'], []); const [selected, setSelected] = useState<string | null>(null); return <Page eyebrow="STATEMENTS & DOCUMENTS" title="Statements" description="Review your monthly account records and open a statement summary before exporting it."><Card title="Monthly statements" note={`Private Checking · USD · ${ACCOUNT}`}><div className="core-list">{months.map(month => <div className="core-row" key={month}><span className="core-avatar"><FileText size={18}/></span><div><b>{month} statement</b><small>Private Checking · USD</small></div><strong>{money(5000000)}</strong><button className="core-text-action" onClick={() => setSelected(month)}>View statement <ArrowRight size={14}/></button></div>)}</div></Card>{selected && <div className="core-overlay" role="dialog" aria-modal="true"><div className="statement"><button className="core-close" onClick={() => setSelected(null)}>×</button><span>FOXSYCU · ACCOUNT STATEMENT</span><h2>{selected}</h2><p>Private Checking {ACCOUNT} · USD</p><div className="statement-total"><span>Ending balance</span><strong>{money(5000000)}</strong></div><div className="core-detail"><span>Account status</span><b>Active</b></div><div className="core-detail"><span>Currency</span><b>United States Dollar</b></div><div className="core-actions"><button className="secondary" onClick={() => setSelected(null)}>Close</button><button className="primary" onClick={() => window.print()}>Print / save PDF</button></div></div></div>}</Page> }

export function SettingsPage() { const [mask, setMask] = useState(true); const [alerts, setAlerts] = useState(true); return <Page eyebrow="SETTINGS" title="Account preferences" description="Control presentation and notification preferences for your banking experience."><div className="core-grid"><Card title="Privacy & display" note="Personalize what is visible on screen"><div className="core-row"><div><b>Mask account numbers</b><small>Keep account identifiers abbreviated in the interface.</small></div><button className={mask ? 'primary' : 'secondary'} onClick={() => setMask(v => !v)}>{mask ? 'Enabled' : 'Disabled'}</button></div><div className="core-row"><div><b>Security notifications</b><small>Receive alerts for sign-ins and sensitive account changes.</small></div><button className={alerts ? 'primary' : 'secondary'} onClick={() => setAlerts(v => !v)}>{alerts ? 'Enabled' : 'Disabled'}</button></div></Card><Card title="Account relationship" note="Read-only customer information"><div className="core-detail"><span>Customer</span><b>John Doe</b></div><div className="core-detail"><span>Primary currency</span><b>USD</b></div><div className="core-detail"><span>Relationship tier</span><b>Private Banking</b></div><div className="core-detail"><span>Status</span><b>Active</b></div></Card></div></Page> }
