import { useMemo, useState } from 'react'
import { ArrowRight, FileText, LockKeyhole, Plus, ShieldCheck, Trash2, Users } from 'lucide-react'
import { NavLink } from 'react-router-dom'
import { supabase } from './supabaseClient'
import { useCustomerData } from './CustomerProvider'
import './core-banking-services.css'

const money = (n: number) => `${n < 0 ? '-' : ''}$${Math.abs(n).toLocaleString('en-US', { minimumFractionDigits: 2, maximumFractionDigits: 2 })}`

function Page({ eyebrow, title, description, children }: { eyebrow: string; title: string; description: string; children: React.ReactNode }) {
  return <div className="core-page"><div className="core-heading"><div><span>{eyebrow}</span><h1>{title}</h1><p>{description}</p></div></div>{children}</div>
}
function Card({ title, note, children }: { title: string; note?: string; children: React.ReactNode }) { return <section className="core-card"><div className="core-card-head"><div><h2>{title}</h2>{note && <p>{note}</p>}</div></div>{children}</section> }

export function BeneficiariesPage() {
  const { beneficiaries, refresh } = useCustomerData()
  const [adding, setAdding] = useState(false); const [name, setName] = useState(''); const [account, setAccount] = useState('')
  const add = async () => {
    if (!name.trim() || account.length < 4) return
    const { session } = await supabase.auth.getSession(); if (!session.session) return
    await supabase.from('beneficiaries').insert({ user_id: session.session.user.id, name: name.trim(), account_masked: `••••${account.slice(-4)}`, beneficiary_type: 'individual', status: 'active' })
    await supabase.from('audit_logs').insert({ user_id: session.session.user.id, action: 'beneficiary_created', resource_type: 'beneficiary', metadata: { name: name.trim() } })
    setName(''); setAccount(''); setAdding(false); await refresh()
  }
  const remove = async (id: string) => { await supabase.from('beneficiaries').delete().eq('id', id); await refresh() }
  return <Page eyebrow="BENEFICIARIES" title="Recipients you trust" description="Manage saved recipients before sending transfers, wires or payments."><Card title="Saved beneficiaries" note={`${beneficiaries.length} saved recipients`}><div className="core-list">{beneficiaries.map(b => <div className="core-row" key={b.id}><span className="core-avatar"><Users size={18}/></span><div><b>{b.name}</b><small>Account {b.account_masked}</small></div><NavLink className="core-text-action" to={`/transfers?recipient=${encodeURIComponent(b.name)}`}>Send money <ArrowRight size={14}/></NavLink><button className="core-icon-action" onClick={() => remove(b.id)} aria-label={`Remove ${b.name}`}><Trash2 size={16}/></button></div>)}</div>{adding ? <div className="core-form"><label>Name<input value={name} onChange={e => setName(e.target.value)} placeholder="Recipient name"/></label><label>Account number<input value={account} onChange={e => setAccount(e.target.value.replace(/\D/g, ''))} inputMode="numeric" placeholder="Last 4 digits" maxLength={4}/></label><div className="core-actions"><button className="secondary" onClick={() => setAdding(false)}>Cancel</button><button className="primary" disabled={!name.trim() || account.length < 4} onClick={add}>Save beneficiary</button></div></div> : <button className="primary" onClick={() => setAdding(true)}><Plus size={16}/>Add beneficiary</button>}</Card><Card title="Before you send" note="Security guidance"><div className="core-notice"><ShieldCheck/><div><b>Review recipient details carefully</b><small>Transfers can be difficult to reverse once authorized. Confirm the name and account before continuing.</small></div></div></Card></Page>
}

export function SavingsPage() {
  const { vaults, refresh } = useCustomerData(); const [selected, setSelected] = useState<string | null>(null)
  const total = vaults.reduce((s, v) => s + Number(v.balance), 0)
  return <Page eyebrow="SAVINGS" title="Savings & vaults" description="Organize your USD savings by purpose while keeping every balance visible."><section className="core-hero"><div><span>TOTAL SAVINGS</span><strong>{money(total)}</strong><p>4.50% APY · USD</p></div><div><span>INTEREST EARNED</span><b>{money(1842.36)}</b><small>Current relationship</small></div></section><div className="core-grid">{vaults.map(v => <Card key={v.id} title={v.name} note={`Target ${money(Number(v.target_amount))}`}><div className="vault-balance"><strong>{money(Number(v.balance))}</strong><span>{Math.round((Number(v.balance) / Number(v.target_amount)) * 100)}% funded</span></div><div className="progress"><i style={{ width: `${Math.min(100, (Number(v.balance) / Number(v.target_amount)) * 100)}%` }}/></div><div className="core-actions"><button className="secondary" onClick={() => setSelected(v.id)}>Manage</button><NavLink className="primary" to="/transfers?mode=transfer">Move money</NavLink></div></Card>)}</div>{selected && <div className="core-overlay" role="dialog" aria-modal="true"><div className="core-dialog"><button className="core-close" onClick={() => setSelected(null)}>×</button><span>SAVINGS VAULT</span><h2>{vaults.find(v => v.id === selected)?.name}</h2><p>Transfers to and from this vault are reviewed before authorization.</p><button className="primary full" onClick={async () => { const vault = vaults.find(v => v.id === selected); if (vault) await supabase.from('audit_logs').insert({ user_id: (await supabase.auth.getUser()).data.user?.id, action: 'savings_vault_viewed', resource_type: 'savings_vault', resource_id: vault.id }); await refresh(); setSelected(null) }}>Close vault</button></div></div>}</Page>
}

export function CardsPage() {
  const { card, refresh } = useCustomerData(); const [show, setShow] = useState(false)
  const frozen = card?.status === 'frozen'
  const toggle = async () => { if (!card) return; const next = frozen ? 'active' : 'frozen'; const { error } = await supabase.from('card_controls').update({ status: next }).eq('id', card.id); if (!error) { const uid = (await supabase.auth.getUser()).data.user?.id; if (uid) await supabase.from('audit_logs').insert({ user_id: uid, action: `card_${next}`, resource_type: 'card', resource_id: card.id }); await refresh() } }
  return <Page eyebrow="CARDS" title="Cards & payment controls" description="Manage card visibility and security controls for your banking relationship."><Card title="Private Banking Card" note={`Virtual card · •••• ${card?.last4 ?? '4821'}`}><div className={`bank-card-visual ${frozen ? 'frozen' : ''}`}><div><b>FOXSYCU</b><small>PRIVATE BANKING</small></div><strong>•••• {card?.last4 ?? '4821'}</strong><span>JOHN DOE</span></div><div className="core-card-controls"><div><b>{frozen ? 'Card frozen' : 'Card active'}</b><small>{frozen ? 'New purchases are blocked.' : 'Purchases are currently permitted.'}</small></div><button className={frozen ? 'primary' : 'secondary'} onClick={toggle}>{frozen ? 'Unfreeze card' : 'Freeze card'}</button><button className="secondary" onClick={() => setShow(v => !v)}>{show ? 'Hide details' : 'View details'}</button></div></Card><Card title="Security controls" note="Keep card activity under your control"><div className="core-detail"><span>Online purchases</span><b>{card?.online_purchases ? 'Enabled' : 'Disabled'}</b></div><div className="core-detail"><span>Contactless</span><b>{card?.contactless ? 'Enabled' : 'Disabled'}</b></div><div className="core-detail"><span>Card status</span><b>{frozen ? 'Frozen' : 'Active'}</b></div>{show && <div className="core-notice"><LockKeyhole/><div><b>Card number protected</b><small>Only the last four digits are shown in the customer interface.</small></div></div>}</Card></Page>
}

export function StatementsPage() {
  const { transactions, account } = useCustomerData(); const [selected, setSelected] = useState<string | null>(null)
  const months = useMemo(() => {
    const map = new Map<string, any[]>()
    transactions.forEach(t => { const date = String(t.effective_date ?? t.date); const key = date.slice(0, 7); if (!map.has(key)) map.set(key, []); map.get(key)!.push(t) })
    return [...map.entries()].sort((a, b) => b[0].localeCompare(a[0])).map(([key, rows]) => ({ key, label: new Date(`${key}-01T00:00:00`).toLocaleDateString('en-US', { month: 'long', year: 'numeric' }), closing: Number(rows[0]?.posted_balance_after ?? 0), opening: Number(rows[rows.length - 1]?.posted_balance_after ?? 125000) }))
  }, [transactions])
  const statement = months.find(m => m.key === selected)
  return <Page eyebrow="STATEMENTS & DOCUMENTS" title="Statements" description="Review monthly account records generated directly from the transaction universe."><Card title="Monthly statements" note={`Private Checking · USD · •••• ${account?.account_number_last4 ?? '4821'}`}><div className="core-list">{months.map(m => <div className="core-row" key={m.key}><span className="core-avatar"><FileText size={18}/></span><div><b>{m.label} statement</b><small>Private Checking · USD</small></div><strong>{money(m.closing)}</strong><button className="core-text-action" onClick={() => setSelected(m.key)}>View statement <ArrowRight size={14}/></button></div>)}</div></Card>{statement && <div className="core-overlay" role="dialog" aria-modal="true"><div className="statement"><button className="core-close" onClick={() => setSelected(null)}>×</button><span>FOXSYCU · ACCOUNT STATEMENT</span><h2>{statement.label}</h2><p>Private Checking · USD</p><div className="statement-total"><span>Opening balance</span><strong>{money(statement.opening)}</strong></div><div className="statement-total"><span>Ending balance</span><strong>{money(statement.closing)}</strong></div><div className="core-detail"><span>Account status</span><b>{account?.status === 'active' ? 'Active' : account?.status}</b></div><div className="core-actions"><button className="secondary" onClick={() => setSelected(null)}>Close</button><button className="primary" onClick={() => window.print()}>Print / save PDF</button></div></div></div>}</Page>
}

export function SettingsPage() {
  const { profile, account, security, refresh } = useCustomerData()
  const updateSecurity = async () => { const uid = (await supabase.auth.getUser()).data.user?.id; if (!uid) return; await supabase.from('security_preferences').update({ alerts: !security.alerts, updated_at: new Date().toISOString() }).eq('user_id', uid); await refresh() }
  return <Page eyebrow="SETTINGS" title="Account preferences" description="Control presentation and notification preferences for your banking experience."><div className="core-grid"><Card title="Privacy & display" note="Personalize what is visible on screen"><div className="core-row"><div><b>Mask account numbers</b><small>Keep account identifiers abbreviated in the interface.</small></div><button className="primary">Enabled</button></div><div className="core-row"><div><b>Security notifications</b><small>Receive alerts for sign-ins and sensitive account changes.</small></div><button className={security.alerts ? 'primary' : 'secondary'} onClick={updateSecurity}>{security.alerts ? 'Enabled' : 'Disabled'}</button></div></Card><Card title="Account relationship" note="Authenticated customer information"><div className="core-detail"><span>Customer</span><b>{profile?.full_name ?? 'John Doe'}</b></div><div className="core-detail"><span>Primary currency</span><b>{profile?.currency ?? 'USD'}</b></div><div className="core-detail"><span>Relationship tier</span><b>{profile?.tier ?? 'Premium User'}</b></div><div className="core-detail"><span>Status</span><b>{account?.status ?? 'Active'}</b></div></Card></div></Page>
}
