import { useMemo, useState } from 'react'
import { ArrowRight, Bell, CalendarClock, Check, CreditCard, FileText, HelpCircle, Lock, MessageSquare, Plus, Repeat2, Search, ShieldAlert, Trash2, UserPlus, WalletCards, X } from 'lucide-react'
import { NavLink, useLocation, useNavigate } from 'react-router-dom'
import { BankingShell } from './BankingShell'
import { useCustomerData } from './CustomerProvider'
import { supabase } from './supabaseClient'
import { addTransaction } from './ledgerStore'
import type { Transaction } from './types'
import './feature-banking.css'

const money = (n:number) => `${n < 0 ? '-' : ''}$${Math.abs(n).toLocaleString('en-US',{minimumFractionDigits:2,maximumFractionDigits:2})}`
function Page({eyebrow,title,description,children}:{eyebrow:string;title:string;description:string;children:React.ReactNode}) { return <div className="fb-page"><header className="fb-heading"><span>{eyebrow}</span><h1>{title}</h1><p>{description}</p></header>{children}</div> }
function Card({title,note,children}:{title:string;note?:string;children:React.ReactNode}) { return <section className="fb-card"><div className="fb-card-head"><div><h2>{title}</h2>{note && <p>{note}</p>}</div></div>{children}</section> }
function Button({children,primary=false,...props}:{children:React.ReactNode;primary?:boolean}&React.ButtonHTMLAttributes<HTMLButtonElement>){return <button className={`fb-btn ${primary?'primary':''}`} {...props}>{children}</button>}
function Shell({children}:{children:React.ReactNode}){return <BankingShell>{children}</BankingShell>}

export function TransferCenter(){
 const {beneficiaries,transactions,refresh}=useCustomerData(); const location=useLocation(); const navigate=useNavigate()
 const params=useMemo(()=>new URLSearchParams(location.search),[location.search])
 const [rail,setRail]=useState(params.get('mode')||'transfer'); const [recipient,setRecipient]=useState(params.get('recipient')||beneficiaries[0]?.name||'Alex Smith'); const [amount,setAmount]=useState(''); const [memo,setMemo]=useState(''); const [schedule,setSchedule]=useState(false); const [review,setReview]=useState(false); const [done,setDone]=useState(false)
 const balance=transactions.filter((t:any)=>t.status==='Completed').reduce((sum:number,t:any)=>sum+(t.direction==='DEBIT'?-Number(t.amount):Number(t.amount)),125000); const value=Number(amount)||0; const fee=rail==='wire'?15:0; const canContinue=value>0&&(rail==='deposit'||value+fee<=balance)
 const submit=async()=>{if(!canContinue)return; if(schedule){localStorage.setItem('foxsycu.scheduled-transfer',JSON.stringify({rail,recipient,amount:value,memo,frequency:'Monthly'}));setReview(false);setDone(true);return}; const now=new Date(); const reference=`FX-${now.toISOString().slice(0,10).replaceAll('-','')}-${Math.random().toString(36).slice(2,8).toUpperCase()}`; const transaction:Transaction={id:reference,kind:rail==='deposit'?'Deposit':'Transfer',type:rail==='wire'?'WIRE_OUT':rail==='zelle'?'ZELLE_OUT':'TRANSFER',status:'Completed',amount:rail==='deposit'?value:-(value+fee),currency:'USD',reference,description:rail==='wire'?`Domestic wire to ${recipient}`:rail==='zelle'?`Zelle payment to ${recipient}`:rail==='deposit'?'Deposit to Private Checking':`Transfer to ${recipient}`,date:now.toISOString().slice(0,10),time:now.toLocaleTimeString('en-US',{hour:'2-digit',minute:'2-digit'}),counterparty:recipient,fee,category:rail,memo,metadata:{synthetic:true,rail}}; addTransaction(transaction); const user=(await supabase.auth.getUser()).data.user; if(user) await supabase.from('notifications').insert({user_id:user.id,title:'Transfer completed',body:`${money(value)} payment completed.`,notification_type:'transaction'}); setReview(false);setDone(true);await refresh()}
 const form=<><div className="fb-tabs">{[['transfer','Transfer'],['wire','Wire'],['zelle','Zelle'],['deposit','Deposit']].map(([id,label])=><button key={id} className={rail===id?'active':''} onClick={()=>{setRail(id);setAmount('')}}>{label}</button>)}</div><div className="fb-grid"><Card title={rail==='wire'?'Domestic wire':rail==='zelle'?'Send money with Zelle':rail==='deposit'?'Deposit funds':'Transfer money'} note="Review recipient, amount, timing and fees before authorization.">{rail!=='deposit'&&<label className="fb-field">Recipient<select value={recipient} onChange={e=>setRecipient(e.target.value)}>{beneficiaries.map((b:any)=><option key={b.id}>{b.name}</option>)}</select></label>}<label className="fb-field">Amount<input value={amount} onChange={e=>setAmount(e.target.value.replace(/[^0-9.]/g,''))} inputMode="decimal" placeholder="0.00"/></label><label className="fb-field">Memo<input value={memo} onChange={e=>setMemo(e.target.value)} placeholder="Optional memo"/></label><label className="fb-check"><input type="checkbox" checked={schedule} onChange={e=>setSchedule(e.target.checked)}/><span><b><CalendarClock size={15}/> Schedule this transfer</b><small>Monthly recurring movement</small></span></label><Button primary disabled={!canContinue} onClick={()=>setReview(true)}>Review & authorize <ArrowRight size={15}/></Button></Card><Card title="Payment summary" note="Before authorization"><div className="fb-detail"><span>From</span><b>Private Checking · ••••4821</b></div>{rail!=='deposit'&&<div className="fb-detail"><span>Recipient</span><b>{recipient}</b></div>}<div className="fb-detail"><span>Amount</span><b>{money(value)}</b></div><div className="fb-detail"><span>Fee</span><b>{money(fee)}</b></div><div className="fb-total"><span>Total</span><strong>{money(rail==='deposit'?value:value+fee)}</strong></div></Card></div>{review&&<div className="fb-modal"><div className="fb-dialog"><button className="fb-x" onClick={()=>setReview(false)}><X/></button><span>REVIEW & AUTHORIZE</span><h2>Confirm payment</h2><div className="fb-review"><div><span>Rail</span><b>{rail.toUpperCase()}</b></div><div><span>Amount</span><b>{money(value)}</b></div><div><span>Recipient</span><b>{rail==='deposit'?'Private Checking':recipient}</b></div><div><span>Fee</span><b>{money(fee)}</b></div></div><Button primary onClick={submit}>Authorize <Check size={15}/></Button></div></div>}</>
 if(done)return <Shell>{Page({eyebrow:'MOVE MONEY',title:schedule?'Transfer scheduled':'Transfer completed',description:'Your payment activity is available from Activity and Notifications.',children:<Card title={schedule?'Scheduled transfer':'Payment posted'}><div className="fb-success"><Check size={22}/><div><b>{schedule?'Scheduled successfully':'Payment posted'}</b><p>{money(value)} · {schedule?'Monthly recurring transfer':'Transaction reference generated'}</p></div></div><div className="fb-actions"><Button primary onClick={()=>{setDone(false);setAmount('')}}>Make another</Button><Button onClick={()=>navigate('/transactions')}>View activity</Button></div></Card>})}</Shell>
 return <Shell>{Page({eyebrow:'MOVE MONEY',title:'Transfer center',description:'Transfer, wire, Zelle-style payments, deposits and scheduled movement with a full review before authorization.',children:form})}</Shell>
}

export function SavingsCenter(){
 const {vaults,refresh}=useCustomerData(); const [adding,setAdding]=useState(false); const [name,setName]=useState(''); const [target,setTarget]=useState(''); const total=vaults.reduce((s:number,v:any)=>s+Number(v.balance),0)
 const create=async()=>{const user=(await supabase.auth.getUser()).data.user;if(!user||!name.trim()||Number(target)<=0)return;await supabase.from('savings_vaults').insert({user_id:user.id,name:name.trim(),balance:0,target_amount:Number(target),apy:4.5,status:'active'});await refresh();setAdding(false);setName('');setTarget('')}
 return <Shell>{Page({eyebrow:'SAVINGS',title:'Savings center',description:'Goal-based savings, APY visibility, progress and account controls in one place.',children:<><section className="fb-hero"><div><span>TOTAL SAVINGS</span><strong>{money(total)}</strong><p>4.50% APY · active goals</p></div><div><span>INTEREST EARNED</span><b>{money(1842.36)}</b><small>This relationship</small></div></section><div className="fb-toolbar"><div><b>Goals & vaults</b><small>Organize savings by purpose.</small></div><Button primary onClick={()=>setAdding(true)}><Plus size={15}/> New goal</Button></div><div className="fb-grid">{vaults.map((v:any)=>{const pct=Math.min(100,Math.round(Number(v.balance)/Number(v.target_amount)*100));return <Card key={v.id} title={v.name} note={`${pct}% of ${money(Number(v.target_amount))}`}><div className="fb-vault"><strong>{money(Number(v.balance))}</strong><span>{pct}%</span></div><div className="fb-progress"><i style={{width:`${pct}%`}}/></div><div className="fb-actions"><Button onClick={()=>{}}>Manage</Button><NavLink className="fb-link-btn" to="/transfers?mode=transfer">Move money <ArrowRight size={14}/></NavLink></div></Card>})}</div>{adding&&<div className="fb-modal"><div className="fb-dialog"><button className="fb-x" onClick={()=>setAdding(false)}><X/></button><span>NEW SAVINGS GOAL</span><h2>Create a goal</h2><label className="fb-field">Goal name<input value={name} onChange={e=>setName(e.target.value)} placeholder="e.g. Home Reserve"/></label><label className="fb-field">Target amount<input value={target} onChange={e=>setTarget(e.target.value.replace(/[^0-9.]/g,''))} placeholder="0.00"/></label><Button primary disabled={!name||Number(target)<=0} onClick={create}>Create goal</Button></div></div>}</>})}</Shell>
}

function Toggle({label,value,onClick,locked=false}:{label:string;value:boolean;onClick?:()=>void;locked?:boolean}){return <div className="fb-control"><div><b>{label}</b><small>{locked?'Available after enrollment.':value?'Enabled':'Disabled'}</small></div><button disabled={locked} onClick={onClick} className={value?'on':''}><span/></button></div>}
export function CardsCenter(){
 const {card,refresh}=useCustomerData(); const frozen=card?.status==='frozen'; const [show,setShow]=useState(false); const [controls,setControls]=useState(()=>JSON.parse(localStorage.getItem('foxsycu.card.controls')||'{"online":true,"contactless":true,"atm":true}'))
 const save=(key:string)=>{const next={...controls,[key]:!controls[key]};setControls(next);localStorage.setItem('foxsycu.card.controls',JSON.stringify(next))}; const toggle=async()=>{if(!card)return;await supabase.from('card_controls').update({status:frozen?'active':'frozen'}).eq('id',card.id);await refresh()}
 return <Shell>{Page({eyebrow:'CARDS',title:'Card controls',description:'Manage card status, purchase channels and security controls.',children:<><div className="fb-grid"><Card title="Private Banking Card" note={`Virtual debit · •••• ${card?.last4||'4821'}`}><div className={`fb-card-visual ${frozen?'frozen':''}`}><div><b>FOXSYCU</b><small>PRIVATE BANKING</small></div><strong>•••• {card?.last4||'4821'}</strong><span>JOHN DOE</span></div><div className="fb-card-status"><div><b>{frozen?'Card frozen':'Card active'}</b><small>{frozen?'Purchases are blocked.':'Purchases are permitted.'}</small></div><Button primary onClick={toggle}>{frozen?'Unfreeze card':'Freeze card'}</Button></div></Card><Card title="Purchase controls" note="Turn channels on or off"><Toggle label="Online purchases" value={controls.online} onClick={()=>save('online')}/><Toggle label="Contactless" value={controls.contactless} onClick={()=>save('contactless')}/><Toggle label="ATM withdrawals" value={controls.atm} onClick={()=>save('atm')}/><Toggle label="Digital wallet" value={false} locked/></Card></div><Card title="Card services" note="Common card actions"><div className="fb-service-grid"><button onClick={()=>setShow(true)}><WalletCards/><b>View details</b><small>Protected information</small></button><button><Repeat2/><b>Replace card</b><small>Lost, stolen or damaged</small></button><button><Lock/><b>Change PIN</b><small>Update your PIN</small></button><button><ShieldAlert/><b>Report a problem</b><small>Start a dispute</small></button></div></Card>{show&&<div className="fb-modal"><div className="fb-dialog"><button className="fb-x" onClick={()=>setShow(false)}><X/></button><span>CARD DETAILS</span><h2>•••• {card?.last4||'4821'}</h2><p>Full card credentials remain protected.</p><Button onClick={()=>setShow(false)}>Close</Button></div></div>}</>})}</Shell>
}

export function BeneficiariesCenter(){
 const {beneficiaries,refresh}=useCustomerData(); const [adding,setAdding]=useState(false); const [query,setQuery]=useState(''); const [name,setName]=useState(''); const [last4,setLast4]=useState(''); const filtered=beneficiaries.filter((b:any)=>b.name.toLowerCase().includes(query.toLowerCase()))
 const save=async()=>{const user=(await supabase.auth.getUser()).data.user;if(!user||!name||last4.length!==4)return;await supabase.from('beneficiaries').insert({user_id:user.id,name,account_masked:`••••${last4}`,beneficiary_type:'individual',status:'active'});await refresh();setAdding(false);setName('');setLast4('')}; const remove=async(id:string)=>{await supabase.from('beneficiaries').delete().eq('id',id);await refresh()}
 return <Shell>{Page({eyebrow:'BENEFICIARIES',title:'Recipients',description:'Saved recipients for transfers, wires and payments.',children:<><Card title="Saved recipients" note={`${beneficiaries.length} recipients`}><div className="fb-search"><Search size={16}/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search recipients"/></div><div className="fb-list">{filtered.map((b:any)=><div className="fb-list-row" key={b.id}><span className="fb-avatar">{b.name.slice(0,2).toUpperCase()}</span><div><b>{b.name}</b><small>{b.beneficiary_type==='business'?'Business':'Individual'} · {b.account_masked}</small></div><NavLink className="fb-link-btn" to={`/transfers?recipient=${encodeURIComponent(b.name)}`}>Send <ArrowRight size={14}/></NavLink><button className="fb-icon" onClick={()=>remove(b.id)}><Trash2 size={16}/></button></div>)}</div><Button primary onClick={()=>setAdding(true)}><UserPlus size={15}/> Add recipient</Button></Card>{adding&&<div className="fb-modal"><div className="fb-dialog"><button className="fb-x" onClick={()=>setAdding(false)}><X/></button><span>NEW RECIPIENT</span><h2>Add beneficiary</h2><label className="fb-field">Name<input value={name} onChange={e=>setName(e.target.value)} placeholder="Full name or business"/></label><label className="fb-field">Account last 4<input maxLength={4} value={last4} onChange={e=>setLast4(e.target.value.replace(/\D/g,''))} placeholder="4821"/></label><Button primary disabled={!name||last4.length!==4} onClick={save}>Save recipient</Button></div></div>}</>})}</Shell>
}

export function StatementsCenter(){
 const {transactions,account}=useCustomerData(); const [selected,setSelected]=useState<string|null>(null)
 const groups=useMemo(()=>{const map=new Map<string,any[]>();transactions.forEach((t:any)=>{const date=String(t.effective_date||t.effectiveDate||t.date);const key=date.slice(0,7);if(!map.has(key))map.set(key,[]);map.get(key)!.push(t)});return [...map.entries()].sort((a,b)=>b[0].localeCompare(a[0])).map(([key,rows])=>{const sorted=rows.slice().sort((a,b)=>String(a.effective_date||a.date).localeCompare(String(b.effective_date||b.date)));const net=sorted.reduce((s:number,t:any)=>s+(t.direction==='DEBIT'?-Number(t.amount):Number(t.amount))-(Number(t.fee)||0),0);const ending=Number(sorted[sorted.length-1]?.posted_balance_after||sorted[sorted.length-1]?.postedBalanceAfter||0);return {key,label:new Date(`${key}-01T00:00:00`).toLocaleDateString('en-US',{month:'long',year:'numeric'}),net,ending,opening:ending-net}})},[transactions]); const statement=groups.find(g=>g.key===selected)
 return <Shell>{Page({eyebrow:'STATEMENTS & DOCUMENTS',title:'Statements',description:'Monthly statements, document access and print-ready records.',children:<><Card title="Statements" note={`Private Checking · ••••${account?.account_number_last4||'4821'}`}><div className="fb-list">{groups.map(g=><div className="fb-list-row" key={g.key}><span className="fb-avatar"><FileText size={16}/></span><div><b>{g.label}</b><small>Opening {money(g.opening)} · Ending {money(g.ending)}</small></div><strong>{money(g.net)}</strong><button className="fb-link-btn" onClick={()=>setSelected(g.key)}>View <ArrowRight size={14}/></button></div>)}</div></Card>{statement&&<div className="fb-modal"><div className="fb-dialog statement-dialog"><button className="fb-x" onClick={()=>setSelected(null)}><X/></button><span>FOXSYCU · ACCOUNT STATEMENT</span><h2>{statement.label}</h2><p>Private Checking · USD · ••••{account?.account_number_last4||'4821'}</p><div className="fb-statement-grid"><div><span>Opening balance</span><b>{money(statement.opening)}</b></div><div><span>Credits/debits</span><b>{money(statement.net)}</b></div><div><span>Ending balance</span><b>{money(statement.ending)}</b></div></div><div className="fb-actions"><Button onClick={()=>setSelected(null)}>Close</Button><Button primary onClick={()=>window.print()}>Print / Save PDF</Button></div></div></div>}</>})}</Shell>
}

export function CommunicationCenterV2(){
 const {notifications,supportCases,messages,refresh}=useCustomerData(); const [tab,setTab]=useState('notifications'); const [subject,setSubject]=useState(''); const [body,setBody]=useState(''); const [caseSubject,setCaseSubject]=useState('');
 const userId=async()=> (await supabase.auth.getUser()).data.user?.id
 const markRead=async(id:string)=>{await supabase.from('notifications').update({read_at:new Date().toISOString()}).eq('id',id);await refresh()}; const send=async()=>{const id=await userId();if(!id||!subject||!body)return;await supabase.from('secure_messages').insert({user_id:id,subject,body});setSubject('');setBody('');await refresh()}; const createCase=async()=>{const id=await userId();if(!id||!caseSubject)return;await supabase.from('support_cases').insert({user_id:id,case_number:`FX-${Date.now().toString().slice(-8)}`,subject:caseSubject,status:'open',priority:'normal'});setCaseSubject('');await refresh()}
 const unread=notifications.filter((n:any)=>!n.read_at).length
 const content=tab==='notifications'?<Card title="Account notifications" note={`${unread} unread`}><div className="fb-list">{notifications.map((n:any)=><div className={`fb-list-row ${n.read_at?'':'unread'}`} key={n.id}><span className="fb-avatar"><Bell size={16}/></span><div><b>{n.title}</b><small>{n.body}</small></div><button className="fb-link-btn" onClick={()=>markRead(n.id)}>{n.read_at?'Read':'Mark read'}</button></div>)}</div></Card>:tab==='messages'?<div className="fb-grid"><Card title="Secure mailbox" note={`${messages.length} messages`}><div className="fb-list">{messages.map((m:any)=><div className="fb-list-row" key={m.id}><span className="fb-avatar"><MessageSquare size={16}/></span><div><b>{m.subject}</b><small>{m.body}</small></div><small>{m.read_at?'Read':'New'}</small></div>)}</div></Card><Card title="New secure message"><label className="fb-field">Subject<input value={subject} onChange={e=>setSubject(e.target.value)} placeholder="How can we help?"/></label><label className="fb-field">Message<textarea value={body} onChange={e=>setBody(e.target.value)} rows={5} placeholder="Write your message"/></label><Button primary disabled={!subject||!body} onClick={send}>Send secure message</Button></Card></div>:<div className="fb-grid"><Card title="Support cases" note={`${supportCases.length} cases`}><div className="fb-list">{supportCases.map((c:any)=><div className="fb-list-row" key={c.id}><span className="fb-avatar"><HelpCircle size={16}/></span><div><b>{c.subject}</b><small>{c.case_number} · {c.priority}</small></div><strong>{c.status}</strong></div>)}</div></Card><Card title="Open a support case"><label className="fb-field">Subject<input value={caseSubject} onChange={e=>setCaseSubject(e.target.value)} placeholder="e.g. Transfer review"/></label><Button primary disabled={!caseSubject} onClick={createCase}>Create support case</Button></Card></div>
 return <Shell>{Page({eyebrow:'COMMUNICATION',title:'Notifications & support',description:'Secure messages, account alerts, service cases and help in one workspace.',children:<><div className="fb-tabs">{[['notifications','Notifications'],['messages','Secure mailbox'],['support','Support']].map(([id,label])=><button key={id} className={tab===id?'active':''} onClick={()=>setTab(id)}>{label}{id==='notifications'&&unread?` · ${unread}`:''}</button>)}</div>{content}</>})}</Shell>
}

export function PrivateBankingCenter(){const {profile,account,vaults}=useCustomerData();const savings=vaults.reduce((s:number,v:any)=>s+Number(v.balance),0);return <Shell>{Page({eyebrow:'PRIVATE BANKING',title:'Relationship overview',description:'Consolidated relationship, savings performance and premium service.',children:<><section className="fb-hero"><div><span>TOTAL RELATIONSHIP</span><strong>{money(Number(account?.available_balance||0)+savings)}</strong><p>Checking + savings · USD</p></div><div><span>CLIENT TIER</span><b>{profile?.tier||'Premium User'}</b><small>Priority relationship</small></div></section><div className="fb-grid"><Card title="Wealth summary"><div className="fb-detail"><span>Checking</span><b>{money(Number(account?.available_balance||0))}</b></div><div className="fb-detail"><span>Savings</span><b>{money(savings)}</b></div><div className="fb-detail"><span>Interest earned</span><b>{money(1842.36)}</b></div><div className="fb-detail"><span>APY</span><b>4.50%</b></div></Card><Card title="Priority support"><div className="fb-success"><CreditCard size={20}/><div><b>Relationship service</b><p>Transfer, statement, card and security requests are routed through support.</p></div></div><NavLink className="fb-link-btn" to="/communication">Open support <ArrowRight size={14}/></NavLink></Card></div></>})}</Shell>}
