import { useMemo, useState } from 'react'
import { Activity, ArrowDownLeft, ArrowUpRight, BarChart3, Bell, CheckCircle2, ChevronRight, CreditCard, Eye, EyeOff, LockKeyhole, MoveRight, Plus, Search, ShieldCheck, Wallet } from 'lucide-react'
import { NavLink } from 'react-router-dom'
import { BankingShell } from './BankingShell'
import { useCustomerData } from './CustomerProvider'
import './main-five.css'

const money = (n:number) => `${n < 0 ? '-' : ''}$${Math.abs(n).toLocaleString('en-US',{minimumFractionDigits:2,maximumFractionDigits:2})}`
const signed = (t:any) => Number(t.direction === 'DEBIT' ? -Number(t.amount) : Number(t.amount))
const firstName = (name:string) => (name || 'John').split(' ')[0]

function Frame({kicker,title,description,children}:{kicker:string,title:string,description:string,children:React.ReactNode}) {
  return <BankingShell><div className="fn-page"><div className="fn-title"><div><span>{kicker}</span><h1>{title}</h1><p>{description}</p></div><div className="fn-secure"><ShieldCheck size={15}/> Secure session</div></div>{children}</div></BankingShell>
}
function Panel({title,note,children,action}:{title:string,note?:string,children:React.ReactNode,action?:React.ReactNode}) {
  return <section className="fn-panel"><div className="fn-panel-head"><div><h2>{title}</h2>{note&&<p>{note}</p>}</div>{action}</div>{children}</section>
}
function Tx({t}:{t:any}) { const a=signed(t); return <NavLink to="/transactions" className="fn-tx"><span className={a>=0?'fn-tx-icon in':'fn-tx-icon out'}>{a>=0?<ArrowDownLeft size={16}/>:<ArrowUpRight size={16}/>}</span><span><b>{t.description||t.counterparty||'Account activity'}</b><small>{t.counterparty||t.transaction_type||'Transaction'} · {t.effective_date||t.date}</small></span><strong className={a>=0?'positive':'negative'}>{a>=0?'+':''}{money(a)}</strong><ChevronRight size={16}/></NavLink> }

export function FNCUOverview() {
  const {profile,account,vaults,transactions}=useCustomerData(); const [hidden,setHidden]=useState(false)
  const available=Number(account?.available_balance??0), savings=vaults.reduce((s,v)=>s+Number(v.balance||0),0)
  return <Frame kicker="PERSONAL BANKING / OVERVIEW" title={`Good morning, ${firstName(profile?.full_name||'John Doe')}.`} description="A clear view of your money, activity and financial relationship."><section className="fn-balance"><div><span>AVAILABLE BALANCE</span><button onClick={()=>setHidden(!hidden)} aria-label="Toggle balance visibility">{hidden?<Eye size={17}/>:<EyeOff size={17}/>}</button><strong>{hidden?'••••••••':money(available)}</strong><p>Private Checking · •••• {account?.account_number_last4||'4821'} · USD</p></div><div className="fn-balance-side"><span>TOTAL RELATIONSHIP</span><b>{hidden?'••••••••':money(available+savings)}</b><small>Checking + Savings</small></div></section><div className="fn-quick"><NavLink to="/transfers"><MoveRight/><b>Transfer</b><small>Move money</small></NavLink><NavLink to="/transfers?mode=wire"><ArrowUpRight/><b>Wire</b><small>Send securely</small></NavLink><NavLink to="/transfers?mode=deposit"><ArrowDownLeft/><b>Deposit</b><small>Add funds</small></NavLink><NavLink to="/cards"><CreditCard/><b>Cards</b><small>Manage spending</small></NavLink></div><div className="fn-grid-2"><Panel title="Your accounts" note="Current balances" action={<NavLink className="fn-text-link" to="/accounts">View accounts <ChevronRight size={14}/></NavLink>}><div className="fn-account-row"><span className="fn-round"><Wallet size={18}/></span><div><b>Private Checking</b><small>USD · •••• {account?.account_number_last4||'4821'}</small></div><strong>{money(available)}</strong></div><div className="fn-account-row"><span className="fn-round"><BarChart3 size={18}/></span><div><b>Savings</b><small>{vaults.length} vaults · 4.50% APY</small></div><strong>{money(savings)}</strong></div></Panel><Panel title="Account health" note="Everything is in good standing"><div className="fn-health"><CheckCircle2 size={20}/><div><b>Account active</b><small>No restrictions or alerts</small></div></div><div className="fn-stat"><span>Pending activity</span><b>{money(transactions.filter((t:any)=>String(t.status).toLowerCase()==='pending').reduce((s,t)=>s+Number(t.amount||0),0))}</b></div><div className="fn-stat"><span>Security</span><b>Protected</b></div></Panel></div><Panel title="Recent activity" note="Latest posted and pending transactions" action={<NavLink className="fn-text-link" to="/transactions">All activity <ChevronRight size={14}/></NavLink>}><div>{transactions.slice(0,6).map(t=><Tx key={t.id} t={t}/>)}</div></Panel></Frame>
}

export function FNCUAccounts() { const {account,vaults,transactions}=useCustomerData(); const available=Number(account?.available_balance??0), savings=vaults.reduce((s,v)=>s+Number(v.balance||0),0); return <Frame kicker="PERSONAL BANKING / ACCOUNTS" title="Accounts" description="Your balances, account details and savings relationship."><section className="fn-account-hero"><div><span>PRIMARY CHECKING</span><strong>{money(available)}</strong><p>USD · •••• {account?.account_number_last4||'4821'}</p></div><div><small>STATUS</small><b>Active</b></div></section><div className="fn-grid-2"><Panel title="Private Checking" note="Primary USD deposit account"><div className="fn-stat"><span>Available balance</span><b>{money(available)}</b></div><div className="fn-stat"><span>Posted balance</span><b>{money(Number(account?.posted_balance??available))}</b></div><div className="fn-stat"><span>Account number</span><b>•••• {account?.account_number_last4||'4821'}</b></div><div className="fn-stat"><span>Currency</span><b>United States Dollar</b></div></Panel><Panel title="Savings relationship" note={`${vaults.length} savings vaults`}><div className="fn-savings-total"><span>Total savings</span><strong>{money(savings)}</strong><small>4.50% APY</small></div>{vaults.map(v=><div className="fn-stat" key={v.id}><span>{v.name}</span><b>{money(Number(v.balance))}</b></div>)}</Panel></div><Panel title="Account activity" note="Recent activity on your primary account"><div>{transactions.slice(0,8).map(t=><Tx key={t.id} t={t}/>)}</div></Panel></Frame> }

export function FNCUTransfers() { const [rail,setRail]=useState('Internal'); const [amount,setAmount]=useState(''); const {account}=useCustomerData(); return <Frame kicker="PERSONAL BANKING / MONEY MOVEMENT" title="Transfer & payments" description="Move USD with a deliberate review-first workflow."><div className="fn-transfer-layout"><Panel title="New transfer" note="Choose a destination and enter the amount"><div className="fn-rails">{['Internal','ACH','Wire','Zelle'].map(r=><button key={r} className={rail===r?'active':''} onClick={()=>setRail(r)}>{r}</button>)}</div><label className="fn-field"><span>From</span><div>Private Checking · •••• {account?.account_number_last4||'4821'} <Wallet size={16}/></div></label><label className="fn-field"><span>To</span><div>John Doe — linked USD account <ChevronRight size={16}/></div></label><label className="fn-field"><span>Amount</span><input value={amount} onChange={e=>setAmount(e.target.value.replace(/[^0-9.]/g,''))} inputMode="decimal" placeholder="$0.00"/></label><label className="fn-field"><span>Memo <em>Optional</em></span><input placeholder="What is this transfer for?"/></label><button className="fn-primary" disabled={!amount}>Review transfer <ChevronRight size={17}/></button></Panel><Panel title="Transfer security" note="Before authorization"><div className="fn-security-item"><LockKeyhole size={18}/><div><b>Review before release</b><small>Transfers require explicit authorization.</small></div></div><div className="fn-security-item"><ShieldCheck size={18}/><div><b>Protected session</b><small>Your session is protected by account security controls.</small></div></div><div className="fn-fee"><span>{rail} fee</span><b>{rail==='Wire'?'$15.00':'$0.00'}</b></div></Panel></div></Frame> }

export function FNCUTransactions() { const {transactions}=useCustomerData(); const [q,setQ]=useState(''); const rows=useMemo(()=>transactions.filter((t:any)=>`${t.description||''} ${t.counterparty||''} ${t.reference||''}`.toLowerCase().includes(q.toLowerCase())),[transactions,q]); return <Frame kicker="PERSONAL BANKING / ACTIVITY" title="Transactions" description="Search, review and understand every movement on your account."><Panel title="All activity" note={`${rows.length} matching transactions`} action={<div className="fn-search"><Search size={16}/><input value={q} onChange={e=>setQ(e.target.value)} placeholder="Search activity"/></div>}><div>{rows.length?rows.map(t=><Tx key={t.id} t={t}/>):<div className="fn-empty"><Activity/><b>No matching activity</b><span>Try another search term.</span></div>}</div></Panel></Frame> }

export function FNCUCards() { const [frozen,setFrozen]=useState(false); return <Frame kicker="PERSONAL BANKING / CARDS" title="Cards" description="Manage your FNCU debit card and spending controls."><div className="fn-card-layout"><section className={`fn-card-visual ${frozen?'frozen':''}`}><div className="fn-card-top"><b>FNCU</b><span>DEBIT</span></div><div className="fn-chip"/><div className="fn-card-number">•••• &nbsp; •••• &nbsp; •••• &nbsp; 4821</div><div className="fn-card-bottom"><span>JOHN DOE<small>CARDHOLDER</small></span><span>12/30<small>VALID THRU</small></span></div></section><Panel title="Card controls" note="Changes apply to this card"><button className="fn-control" onClick={()=>setFrozen(!frozen)}><span><LockKeyhole size={17}/><b>{frozen?'Unfreeze card':'Freeze card'}</b><small>{frozen?'Card payments are paused.':'Temporarily pause card payments.'}</small></span><i className={frozen?'on':''}/></button><NavLink className="fn-control" to="/security"><span><ShieldCheck size={17}/><b>Security Center</b><small>Passkeys, MFA and trusted devices.</small></span><ChevronRight size={17}/></NavLink><button className="fn-control"><span><Plus size={17}/><b>Request replacement</b><small>Start a secure service request.</small></span><ChevronRight size={17}/></button></Panel></div></Frame> }
