import { useMemo, useState } from 'react'
import { Bell, CalendarDays, MessageSquare, Search, ShieldCheck, X } from 'lucide-react'
import { BankingShell } from './BankingShell'
import { useCustomerData } from './CustomerProvider'
import CustomerServiceChatPage from './CustomerServiceChatPage'
import { useLocation } from 'react-router-dom'
import './feature-banking.css'

const dateTime=(v:any)=>{if(!v)return '—';const d=new Date(v);return Number.isNaN(d.getTime())?String(v):d.toLocaleString('en-US',{month:'short',day:'numeric',year:'numeric',hour:'numeric',minute:'2-digit'})}
const sortTime=(m:any)=>{const v=m.event_at||m.created_at;const d=v?new Date(v).getTime():0;return Number.isNaN(d)?0:d}
const fmtDate=(v:any)=>{if(!v)return '—';const d=new Date(v);return Number.isNaN(d.getTime())?String(v):d.toLocaleDateString('en-US',{month:'short',day:'numeric',year:'numeric'})}
const fmtTime=(v:any)=>{if(!v)return '—';const d=new Date(v);return Number.isNaN(d.getTime())?String(v):d.toLocaleTimeString('en-US',{hour:'numeric',minute:'2-digit'})}
const money=(n:number)=>`${n<0?'-':''}$${Math.abs(n).toLocaleString('en-US',{minimumFractionDigits:2,maximumFractionDigits:2})}`

export default function MessagesPage(){
 const location=useLocation();if(new URLSearchParams(location.search).get('view')==='customer-service')return <CustomerServiceChatPage/>
 const{messages,transactions}=useCustomerData();const[q,setQ]=useState('');const[open,setOpen]=useState<any|null>(null)
 const txMap=useMemo(()=>new Map(transactions.map(t=>[t.reference,t])),[transactions])
 const rows=useMemo(()=>messages.filter((m:any)=>`${m.subject||''} ${m.body||''} ${m.transaction_reference||''}`.toLowerCase().includes(q.toLowerCase())).sort((a:any,b:any)=>sortTime(b)-sortTime(a)),[messages,q])
 const linked=(m:any)=>m?.transaction_reference?txMap.get(m.transaction_reference):undefined;const openTx=linked(open);const openMeta:any=openTx?.metadata??{}
 return <BankingShell><div className="fb-page"><header className="fb-heading"><span>SECURE COMMUNICATION</span><h1>Messages</h1><p>Transaction alerts are synchronized to the underlying banking event, including its exact date, time and reference.</p></header>
  <div className="fb-card" style={{marginBottom:14}}><label style={{display:'flex',alignItems:'center',gap:8,border:'1px solid #E4E7EC',borderRadius:8,padding:'0 11px',height:38}}><Search size={15}/><input value={q} onChange={e=>setQ(e.target.value)} placeholder="Search messages" style={{border:0,outline:0,width:'100%',fontSize:12}}/></label></div>
  <section className="fb-card"><div className="fb-card-head"><div><h2>Inbox</h2><p>{rows.length} message{rows.length===1?'':'s'} · newest event first · transaction-linked notices use the transaction timestamp</p></div></div>
   <div>{rows.map((m:any)=>{const t=linked(m);const eventAt=t?.postedAt||t?.initiatedAt||m.event_at||m.created_at;return <button key={m.id} type="button" onClick={()=>setOpen(m)} style={{width:'100%',border:0,borderTop:'1px solid #F0F2F5',background:'#fff',padding:'14px 0',display:'grid',gridTemplateColumns:'34px minmax(0,1fr) auto',gap:12,alignItems:'start',textAlign:'left',cursor:'pointer'}}><span style={{width:32,height:32,borderRadius:8,display:'grid',placeItems:'center',background:m.priority==='urgent'?'#FFF1F0':'#EFF4FF',color:m.priority==='urgent'?'#B42318':'#155EEF'}}>{m.message_type==='security'?<ShieldCheck size={15}/>:m.transaction_reference?<Bell size={15}/>:<MessageSquare size={15}/>}</span><span style={{minWidth:0}}><b style={{display:'block',fontSize:12,color:'#101828'}}>{m.subject}</b><strong style={{display:'block',marginTop:4,fontSize:10,lineHeight:1.45,color:'#667085',fontWeight:500,overflow:'hidden',textOverflow:'ellipsis',whiteSpace:'nowrap'}}>{m.body}</strong><small style={{display:'block',marginTop:6,color:'#98A2B3',fontSize:9}}>{t?`${t.description} · ${t.reference}`:m.message_type||'Service message'}</small></span><span style={{fontSize:9,color:'#667085',whiteSpace:'nowrap',textAlign:'right'}}><b style={{display:'block',fontSize:9,fontWeight:600}}>{fmtDate(eventAt)}</b><small style={{display:'block',marginTop:3}}>{fmtTime(eventAt)}{!m.read_at&&<i style={{display:'inline-block',marginLeft:7,width:6,height:6,borderRadius:'50%',background:'#155EEF'}}/>}</small></span></button>})}</div>
  </section>
  {open&&<div className="drawer-backdrop" onClick={()=>setOpen(null)}><aside className="drawer" onClick={e=>e.stopPropagation()} style={{maxWidth:560}}><div className="drawer-head"><div><small>SECURE MESSAGE</small><h2>{open.subject}</h2></div><button className="icon-button" onClick={()=>setOpen(null)}><X size={18}/></button></div><p style={{fontSize:12,lineHeight:1.6,color:'#475467'}}>{open.body}</p>{openTx&&<div className="drawer-details"><div><span>Event timestamp</span><b>{dateTime(openTx.postedAt||openTx.initiatedAt)}</b></div><div><span>Transaction date</span><b>{fmtDate(openTx.date)}</b></div><div><span>Transaction time</span><b>{openTx.time||fmtTime(openTx.postedAt||openTx.initiatedAt)}</b></div><div><span>Transaction</span><b>{openTx.description}</b></div><div><span>Amount</span><b>{openTx.amount>=0?'+':''}{money(Number(openTx.amount||0))}</b></div><div><span>Status</span><b>{openTx.status}</b></div><div><span>Payment rail</span><b>{String(openMeta.payment_rail||'').replace(/_/g,' ')||'—'}</b></div><div><span>Reference</span><b>{openTx.reference||open.transaction_reference}</b></div><div><span>Institution</span><b>{openMeta.institution_name||openTx.institution?.name||'—'}</b></div><div><span>Balance after</span><b>{openTx.availableBalanceAfter!=null?money(Number(openTx.availableBalanceAfter)):'—'}</b></div></div>}<div style={{marginTop:18,paddingTop:14,borderTop:'1px solid #F0F2F5',display:'flex',gap:10,color:'#667085',fontSize:9}}><CalendarDays size={15}/><span>The inbox event is anchored to the same transaction timestamp and reference used by the account activity ledger.</span></div></aside></div>}
 </div></BankingShell>
}
