import { useEffect, useState } from 'react'
import { ArrowLeft, ArrowRight, Check } from 'lucide-react'
import { useNavigate } from 'react-router-dom'
import { BankingShell } from './BankingShell'
import { useCustomerData } from './CustomerProvider'
import { createMoneyMovement, executeMoneyMovement } from './moneyMovementServiceV2'
import './feature-banking.css'

const DRAFT_KEY='fncu:p2p-payment-draft'
const money=(n:number)=>`$${Math.abs(n).toLocaleString('en-US',{minimumFractionDigits:2,maximumFractionDigits:2})}`
type Draft={recipient:string;email:string;amount:number;memo:string;sourceAccountId:string}

export default function P2PPaymentReviewPage(){
 const {account,refresh}=useCustomerData(); const navigate=useNavigate()
 const [draft,setDraft]=useState<Draft|null>(null); const [busy,setBusy]=useState(false); const [error,setError]=useState(''); const [result,setResult]=useState<any>(null)
 useEffect(()=>{try{const raw=sessionStorage.getItem(DRAFT_KEY);if(raw)setDraft(JSON.parse(raw))}catch{setDraft(null)}},[])
 const available=Number(account?.available_balance||0)
 const authorize=async()=>{if(!account?.id||!draft)return;setBusy(true);setError('');try{if(draft.sourceAccountId!==account.id)throw new Error('The payment draft is no longer valid for this account.');if(draft.amount<=0||draft.amount>available)throw new Error('The payment amount is no longer available from this account.');const created=await createMoneyMovement({idempotencyKey:`fncu-p2p-${crypto.randomUUID()}`,rail:'zelle_like',sourceAccountId:account.id,destinationAccountId:null,beneficiaryId:null,amount:draft.amount,currency:'USD',memo:draft.memo,metadata:{counterparty:draft.recipient,recipient_name:draft.recipient,email:draft.email,synthetic_demo:true}});const completed=created.status==='processing'?await executeMoneyMovement(created.movement_id):created;setResult(completed);sessionStorage.removeItem(DRAFT_KEY);await refresh()}catch(e:any){setError(e?.message||'Unable to authorize this P2P payment.')}finally{setBusy(false)}}
 if(result)return <BankingShell><div className="fb-page"><header className="fb-heading"><span>PAY A PERSON</span><h1>Payment submitted</h1><p>The payment record was created through the FNCU money-movement service.</p></header><section className="fb-card"><div className="fb-success"><Check size={22}/><div><b>{result.status==='completed'?'P2P payment completed':'P2P payment accepted for processing'}</b><p>{money(Number(result.amount||draft?.amount||0))} · {result.reference||'Reference pending'}</p></div></div><div className="fb-actions"><button className="fb-btn primary" onClick={()=>navigate('/transfers?mode=p2p')}>Make another P2P payment</button><button className="fb-btn" onClick={()=>navigate('/transactions')}>View activity <ArrowRight size={14}/></button></div></section></div></BankingShell>
 if(!draft)return <BankingShell><div className="fb-page"><header className="fb-heading"><span>PAY A PERSON</span><h1>Payment summary unavailable</h1><p>Your payment draft is missing or has expired.</p></header><section className="fb-card"><div className="fb-actions"><button className="fb-btn primary" onClick={()=>navigate('/transfers?mode=p2p')}>Start a payment <ArrowRight size={14}/></button></div></section></div></BankingShell>
 return <BankingShell><div className="fb-page"><header className="fb-heading"><span>PAY A PERSON · STEP 2 OF 2</span><h1>Payment summary</h1><p>Review the complete payment before you authorize it. No funds have been moved yet.</p></header><section className="fb-card"><div className="fb-detail"><span>From</span><b>{account?.account_name||'Checking'}<small>{account?.account_number||`•••• ${account?.account_number_last4||'----'}`}</small></b></div><div className="fb-detail"><span>To</span><b>{draft.recipient}<small>{draft.email}</small></b></div><div className="fb-detail"><span>Amount</span><b>{money(draft.amount)}</b></div>{draft.memo&&<div className="fb-detail"><span>Memo</span><b>{draft.memo}</b></div>}<div className="fb-total"><span>Available after</span><strong>{money(Math.max(0,available-draft.amount))}</strong></div><div className="fb-actions"><button className="fb-btn" disabled={busy} onClick={()=>navigate('/transfers?mode=p2p')}><ArrowLeft size={14}/> Edit payment</button><button className="fb-btn primary" disabled={busy||draft.amount>available} onClick={()=>void authorize()}>{busy?'Authorizing…':'Authorize payment'} <Check size={15}/></button></div>{draft.amount>available&&<p className="fb-error">The payment amount now exceeds your available balance. Return and enter a different amount.</p>}{error&&<p className="fb-error">{error}</p>}</section></div></BankingShell>
}
