import { useMemo } from 'react'
import { AlertTriangle, ArrowRight, CheckCircle2, Clock3, FileText, Headphones, KeyRound, Mail, MonitorSmartphone, ShieldCheck, Smartphone, WalletCards } from 'lucide-react'
import { NavLink } from 'react-router-dom'
import { supabase } from './supabaseClient'
import { useCustomerData } from './CustomerProvider'
import './security-premium.css'

type SecurityPrefs = { two_fa: boolean; passkey: boolean; alerts: boolean }
const money = (n: number) => `$${n.toLocaleString('en-US', { minimumFractionDigits: 2, maximumFractionDigits: 2 })}`
function Header({ eyebrow, title, description }: { eyebrow: string; title: string; description: string }) { return <div className="sp-header"><div><span>{eyebrow}</span><h1>{title}</h1><p>{description}</p></div></div> }
function Card({ title, note, children }: { title: string; note?: string; children: React.ReactNode }) { return <section className="sp-card"><div className="sp-card-title"><div><h2>{title}</h2>{note && <p>{note}</p>}</div></div>{children}</section> }
function ToggleRow({ icon, title, note, enabled, onToggle }: { icon: React.ReactNode; title: string; note: string; enabled: boolean; onToggle: () => void }) { return <div className="sp-row"><span className="sp-icon">{icon}</span><div className="sp-row-copy"><b>{title}</b><small>{note}</small></div><button className={`sp-toggle ${enabled ? 'on' : ''}`} onClick={onToggle} aria-pressed={enabled}><span /></button></div> }

export function SecurityCenter() {
  const { security, refresh } = useCustomerData()
  const update = async (key: keyof SecurityPrefs) => { const uid = (await supabase.auth.getUser()).data.user?.id; if (!uid) return; await supabase.from('security_preferences').update({ [key]: !security[key], updated_at: new Date().toISOString() }).eq('user_id', uid); await supabase.from('audit_logs').insert({ user_id: uid, action: `security_${key}_${!security[key] ? 'enabled' : 'disabled'}`, resource_type: 'security_preferences', metadata: { preference: key } }); await refresh() }
  const strong = security.two_fa && security.passkey && security.alerts
  return <><Header eyebrow="SECURITY CENTER" title="Protect your banking relationship" description="Manage authentication, devices, alerts and account security from one place."/><div className="sp-grid"><Card title="Security posture" note="Current protection status"><div className="sp-status"><CheckCircle2 size={22}/><div><b>{strong ? 'Strong protection' : 'Protection needs attention'}</b><small>{strong ? 'Recommended controls are active.' : 'Enable the recommended controls below.'}</small></div></div><div className="sp-metrics"><div><span>2FA</span><b>{security.two_fa ? 'Enabled' : 'Disabled'}</b></div><div><span>Passkey</span><b>{security.passkey ? 'Enabled' : 'Disabled'}</b></div><div><span>Alerts</span><b>{security.alerts ? 'Enabled' : 'Disabled'}</b></div></div></Card><Card title="Authentication" note="Control how you authorize access"><ToggleRow icon={<Smartphone/>} title="Two-factor authentication" note="Authenticator app required for sensitive sign-ins." enabled={security.two_fa} onToggle={() => update('two_fa')}/><ToggleRow icon={<KeyRound/>} title="Passkeys" note="Passwordless authentication on enrolled devices." enabled={security.passkey} onToggle={() => update('passkey')}/><ToggleRow icon={<AlertTriangle/>} title="Security alerts" note="Notify you about sign-ins and sensitive activity." enabled={security.alerts} onToggle={() => update('alerts')}/></Card></div><div className="sp-grid"><Card title="Trusted devices" note="Devices currently authorized for this account"><div className="sp-device"><MonitorSmartphone/><div><b>Current browser</b><small>Current session · Trusted</small></div><strong>Current</strong></div><div className="sp-device"><MonitorSmartphone/><div><b>MacBook Pro</b><small>Previously trusted device</small></div><strong>Trusted</strong></div></Card><Card title="Login history" note="Recent access events"><div className="sp-event"><CheckCircle2/><div><b>Successful sign-in</b><small>Current session · Supabase Auth</small></div><strong>Verified</strong></div><div className="sp-event"><CheckCircle2/><div><b>Authentication protected</b><small>Session persistence and refresh enabled.</small></div><strong>Active</strong></div></Card></div><Card title="Suspicious activity" note="Events requiring attention"><div className="sp-alert"><AlertTriangle/><div><b>No unresolved suspicious activity</b><small>Unusual sign-ins, transfer patterns or security changes will appear here.</small></div></div></Card></>
}

export function CommunicationCenter() {
  const { notifications, supportCases, messages } = useCustomerData()
  const unread = useMemo(() => notifications.filter(n => !n.read_at).length, [notifications])
  const markRead = async (id: string) => { await supabase.from('notifications').update({ read_at: new Date().toISOString() }).eq('id', id) }
  return <><Header eyebrow="COMMUNICATION" title="Secure mailbox & support" description="Keep important banking communication, support cases and notifications in one protected workspace."/><div className="sp-grid"><Card title="Secure mailbox" note={`${messages.length} secure messages`} >{messages.slice(0, 5).map(m => <div className="sp-message" key={m.id}><Mail/><div><b>{m.subject}</b><small>{m.body}</small></div><strong>{m.read_at ? 'Read' : 'New'}</strong></div>)}<button className="sp-primary">Open secure mailbox <ArrowRight size={15}/></button></Card><Card title="Support cases" note={`${supportCases.length} service cases`}>{supportCases.map(c => <div className="sp-case" key={c.id}><span>{c.case_number}</span><b>{c.subject}</b><small>{c.status} · {c.priority}</small></div>)}<button className="sp-secondary">View support cases</button></Card></div><div className="sp-grid"><Card title="Notifications" note={`${unread} unread account updates`}>{notifications.slice(0, 5).map(n => <div className="sp-notification" key={n.id}><Clock3/><div><b>{n.title}</b><small>{n.body}</small></div><button onClick={() => markRead(n.id)}>{n.read_at ? 'Read' : 'Mark read'}</button></div>)}</Card><Card title="Help center" note="Guidance when you need it"><div className="sp-help"><Headphones/><div><b>Premium support</b><small>Priority assistance for your banking relationship.</small></div></div><div className="sp-help"><FileText/><div><b>Banking guides</b><small>Transfers, statements, security and account controls.</small></div></div><button className="sp-secondary">Open help center</button></Card></div></>
}

export function PrivateBanking() {
  const { profile, account, vaults } = useCustomerData(); const savings = vaults.reduce((sum, v) => sum + Number(v.balance), 0); const total = Number(account?.available_balance ?? 0) + savings
  return <><Header eyebrow="PRIVATE BANKING" title="Relationship overview" description="A consolidated view of your banking relationship, savings performance and premium service."/><section className="sp-hero"><div><span>TOTAL RELATIONSHIP</span><strong>{money(total)}</strong><p>Private Checking + Savings · USD</p></div><div><span>CLIENT TIER</span><b>{profile?.tier ?? 'Premium User'}</b><small>Premium relationship</small></div></section><div className="sp-grid"><Card title="Wealth summary" note="Current relationship position"><div className="sp-wealth"><div><span>Checking</span><b>{money(Number(account?.available_balance ?? 0))}</b></div><div><span>Savings</span><b>{money(savings)}</b></div><div><span>Interest earned</span><b>{money(1842.36)}</b></div><div><span>APY</span><b>4.50%</b></div></div></Card><Card title="Savings performance" note="Active savings vaults">{vaults.map(v => <div className="sp-performance" key={v.id}><div><span>{v.name}</span><b>{money(Number(v.balance))} / {money(Number(v.target_amount))}</b><small>{Math.round((Number(v.balance) / Number(v.target_amount)) * 100)}% of target</small></div></div>)}</Card></div><div className="sp-grid"><Card title="Larger transfer context" note="Additional review for significant movement of funds"><div className="sp-review"><WalletCards/><div><b>Enhanced transfer review</b><small>Beneficiary context, source of funds, fees and authorization status should be visible before confirmation.</small></div></div><NavLink className="sp-primary" to="/transfers">Review transfer options <ArrowRight size={15}/></NavLink></Card><Card title="Account relationship details" note={`Relationship since ${profile?.customer_since ?? 'March 18, 2021'}`}><div className="sp-detail"><span>Customer</span><b>{profile?.full_name ?? 'John Doe'}</b></div><div className="sp-detail"><span>Primary currency</span><b>{profile?.currency ?? 'USD'}</b></div><div className="sp-detail"><span>Relationship tier</span><b>{profile?.tier ?? 'Premium User'}</b></div><div className="sp-detail"><span>Account status</span><b>{account?.status ?? 'Active'}</b></div></Card></div><Card title="Premium support" note="Priority service for complex banking needs"><div className="sp-support"><Headphones size={22}/><div><b>Dedicated relationship support</b><small>Priority handling for account, transfer, statement and security requests.</small></div><button className="sp-primary">Contact support</button></div></Card></>
}
export function SecurityNavigation() { return null }
