import { useState } from 'react'
import { AlertTriangle, ArrowRight, CheckCircle2, Clock3, FileText, Headphones, KeyRound, LockKeyhole, Mail, MonitorSmartphone, ShieldCheck, Smartphone, UserCheck, WalletCards } from 'lucide-react'
import { NavLink } from 'react-router-dom'
import './security-premium.css'

const money = (n: number) => `$${n.toLocaleString('en-US', { minimumFractionDigits: 2, maximumFractionDigits: 2 })}`

function Header({ eyebrow, title, description }: { eyebrow: string; title: string; description: string }) {
  return <div className="sp-header"><div><span>{eyebrow}</span><h1>{title}</h1><p>{description}</p></div></div>
}

function Card({ title, note, children }: { title: string; note?: string; children: React.ReactNode }) {
  return <section className="sp-card"><div className="sp-card-title"><div><h2>{title}</h2>{note && <p>{note}</p>}</div></div>{children}</section>
}

function ToggleRow({ icon, title, note, enabled, onToggle }: { icon: React.ReactNode; title: string; note: string; enabled: boolean; onToggle: () => void }) {
  return <div className="sp-row"><span className="sp-icon">{icon}</span><div className="sp-row-copy"><b>{title}</b><small>{note}</small></div><button className={`sp-toggle ${enabled ? 'on' : ''}`} onClick={onToggle} aria-pressed={enabled}><span /></button></div>
}

export function SecurityCenter() {
  const [twoFA, setTwoFA] = useState(true)
  const [passkey, setPasskey] = useState(true)
  const [alerts, setAlerts] = useState(true)
  return <><Header eyebrow="SECURITY CENTER" title="Protect your banking relationship" description="Manage authentication, devices, alerts and account security from one place." /><div className="sp-grid"><Card title="Security posture" note="Current protection status"><div className="sp-status"><CheckCircle2 size={22} /><div><b>Strong protection</b><small>2FA, passkey and security alerts are active.</small></div></div><div className="sp-metrics"><div><span>2FA</span><b>Enabled</b></div><div><span>Passkey</span><b>Enabled</b></div><div><span>Trusted devices</span><b>3</b></div></div></Card><Card title="Authentication" note="Control how you authorize access"><ToggleRow icon={<Smartphone />} title="Two-factor authentication" note="Authenticator app required for sensitive sign-ins." enabled={twoFA} onToggle={() => setTwoFA(v => !v)} /><ToggleRow icon={<KeyRound />} title="Passkeys" note="Passwordless authentication on enrolled devices." enabled={passkey} onToggle={() => setPasskey(v => !v)} /><ToggleRow icon={<AlertTriangle />} title="Security alerts" note="Notify you about sign-ins, profile changes and sensitive activity." enabled={alerts} onToggle={() => setAlerts(v => !v)} /></Card></div><div className="sp-grid"><Card title="Trusted devices" note="Devices currently authorized for this account"><div className="sp-device"><MonitorSmartphone /><div><b>Pixel 9 Pro</b><small>Lagos · Current session · Trusted</small></div><strong>Current</strong></div><div className="sp-device"><MonitorSmartphone /><div><b>MacBook Pro</b><small>London · Last active 2 days ago</small></div><button>Remove</button></div><div className="sp-device"><Smartphone /><div><b>iPhone 15 Pro</b><small>New York · Last active 8 days ago</small></div><button>Remove</button></div></Card><Card title="Login history" note="Recent access events"><div className="sp-event"><CheckCircle2 /><div><b>Successful sign-in</b><small>Today · Current device · Lagos</small></div><strong>Verified</strong></div><div className="sp-event"><CheckCircle2 /><div><b>Successful sign-in</b><small>2 days ago · MacBook Pro · London</small></div><strong>Verified</strong></div><div className="sp-event warning"><AlertTriangle /><div><b>New device challenge</b><small>8 days ago · iPhone 15 Pro · New York</small></div><strong>Reviewed</strong></div></Card></div><Card title="Suspicious activity" note="Events requiring attention"><div className="sp-alert"><AlertTriangle /><div><b>No unresolved suspicious activity</b><small>We will surface unusual sign-ins, transfer patterns or security changes here.</small></div></div></Card></>
}

export function CommunicationCenter() {
  return <><Header eyebrow="COMMUNICATION" title="Secure mailbox & support" description="Keep important banking communication, support cases and notifications in one protected workspace." /><div className="sp-grid"><Card title="Secure mailbox" note="Messages from FOXSYCU support and relationship team"><div className="sp-message unread"><Mail /><div><b>Relationship team · Quarterly review</b><small>Your September relationship summary is ready.</small></div><strong>Today</strong></div><div className="sp-message"><Mail /><div><b>Security · Device confirmation</b><small>Your trusted-device list was updated.</small></div><strong>Yesterday</strong></div><button className="sp-primary">Open secure mailbox <ArrowRight size={15} /></button></Card><Card title="Support cases" note="Track requests and service conversations"><div className="sp-case"><span>FX-2026-0184</span><b>Account relationship review</b><small>Open · Priority support</small></div><div className="sp-case"><span>FX-2026-0141</span><b>Statement request</b><small>Resolved · September 2026</small></div><button className="sp-secondary">View support cases</button></Card></div><div className="sp-grid"><Card title="Notifications" note="Account and security updates"><div className="sp-notification"><BellIcon /><div><b>Transfer alert</b><small>A $25,000 savings transfer is pending authorization.</small></div><strong>New</strong></div><div className="sp-notification"><ShieldCheck /><div><b>Security alert</b><small>Two-factor authentication is enabled.</small></div><strong>Read</strong></div></Card><Card title="Help center" note="Guidance when you need it"><div className="sp-help"><Headphones /><div><b>Premium support</b><small>Priority assistance for your banking relationship.</small></div></div><div className="sp-help"><FileText /><div><b>Banking guides</b><small>Transfers, statements, security and account controls.</small></div></div><button className="sp-secondary">Open help center</button></Card></div></>
}

function BellIcon() { return <span className="sp-icon"><Clock3 size={17} /></span> }

export function PrivateBanking() {
  return <><Header eyebrow="PRIVATE BANKING" title="Relationship overview" description="A consolidated view of your $5M+ banking relationship, savings performance and premium service." /><section className="sp-hero"><div><span>TOTAL RELATIONSHIP</span><strong>{money(5625000)}</strong><p>Private Checking + Savings · USD</p></div><div><span>CLIENT TIER</span><b>Private Banking</b><small>Premium relationship</small></div></section><div className="sp-grid"><Card title="Wealth summary" note="Current relationship position"><div className="sp-wealth"><div><span>Checking</span><b>{money(5000000)}</b></div><div><span>Savings</span><b>{money(625000)}</b></div><div><span>Interest earned</span><b>{money(1842.36)}</b></div><div><span>APY</span><b>4.50%</b></div></div></Card><Card title="Savings performance" note="Three active savings vaults"><div className="sp-performance"><div><span>Emergency Reserve</span><b>$250,000 / $300,000</b><small>83% of target</small></div><div><span>Property Reserve</span><b>$250,000 / $500,000</b><small>50% of target</small></div><div><span>Travel & Lifestyle</span><b>$125,000 / $200,000</b><small>63% of target</small></div></div></Card></div><div className="sp-grid"><Card title="Larger transfer context" note="Additional review for significant movement of funds"><div className="sp-review"><WalletCards /><div><b>Enhanced transfer review</b><small>Large transfers can display beneficiary context, source of funds, fees, authorization status and relationship impact before confirmation.</small></div></div><NavLink className="sp-primary" to="/transfers">Review transfer options <ArrowRight size={15} /></NavLink></Card><Card title="Account relationship details" note="Relationship since March 18, 2021"><div className="sp-detail"><span>Customer</span><b>John Doe</b></div><div className="sp-detail"><span>Primary currency</span><b>USD</b></div><div className="sp-detail"><span>Relationship tier</span><b>Private Banking</b></div><div className="sp-detail"><span>Premium support</span><b>Priority</b></div><div className="sp-detail"><span>Account status</span><b>Active</b></div></Card></div><Card title="Premium support" note="Priority service for complex banking needs"><div className="sp-support"><Headphones size={22} /><div><b>Dedicated relationship support</b><small>Priority handling for account, transfer, statement and security requests.</small></div><button className="sp-primary">Contact support</button></div></Card></>
}

export function SecurityNavigation() {
  return <div className="sp-subnav"><NavLink to="/security">Security</NavLink><NavLink to="/communication">Communication</NavLink><NavLink to="/private-banking">Private Banking</NavLink></div>
}
