import { useEffect, useState } from 'react'
import { ArrowLeft, Check } from 'lucide-react'
import { useNavigate, useSearchParams } from 'react-router-dom'
import { BankingShell } from './BankingShell'
import { useCustomerData } from './CustomerProvider'
import { createMoneyMovement, executeMoneyMovement, type MoneyMovementRail } from './moneyMovementServiceV2'
import './feature-banking.css'

type Draft={rail:MoneyMovementRail;sourceAccountId:string;amount:number;memo:string;fee:number;destinationNumber:string;selectedDestination:any;country:'US'|'GB';internationalDestination:any;recipientName:string;externalAccount:string;externalRouting:string;externalAccountType:string;p2pEmail:string}
const KEY='fncu:transfer-review-draft'
const money=(n:number)=>`${n<0?'-':''}$${Math.abs(n).toLocaleString('en-US',{minimumFractionDigits:2,maximumFractionDigits:2})}`
const railLabel=(rail:string)=>rail==='zelle_like'?'P2P':rail.toUpperCase()

export default function TransferReviewPage(){
 const {account,refresh}=useCustomerData(); const navigate=useNavigate(); const [params]=useSearchParams(); const [draft,setDraft]=useState<Draft|null>(null); const [busy,setBusy]=useState(false); const [error,setError]=useState(''); const [result,setResult]=useState<any>(null)
 useEffect(()=>{try{const raw=sessionStorage.getItem(KEY);if(raw)setDraft(JSON.parse(raw))}catch{setDraft(null)}},[])
 const available=Number(account?.available_balance||0)
 const authorize=async()=>{if(!draft||!account?.id)return;setBusy(true);setError('');try{if(draft.sourceAccountId&&draft.sourceAccountId!==account.id)throw new Error('This transfer draft belongs to a different account.');if(draft.rail!=='deposit'&&draft.amount+draft.fee>available)throw new Error('The transfer amount is no longer available from this account.');const metadata=draft.rail==='international'?{counterparty:draft.internationalDestination?.recipient_name||null,directory_destination_id:draft.internationalDestination?.id||null,destination_country:draft.internationalDestination?.country_code||null,destination_currency:draft.internationalDestination?.destination_currency||null,destination_account_identifier:draft.internationalDestination?.account_number||draft.internationalDestination?.iban||null,destination_routing_or_sort:draft.internationalDestination?.routing_number||draft.internationalDestination?.sort_code||null,destination_swift_bic:draft.internationalDestination?.swift_bic||null,destination_institution:draft.internationalDestination?.institution_name||null,synthetic_demo:true}:draft.rail==='internal'?{counterparty:draft.selectedDestination?.account_name||null,destination_account_number:draft.selectedDestination?.account_number||null,destination_account_type:draft.selectedDestination?.account_type||null,directory_destination_id:draft.selectedDestination?.directory_destination_id||null,synthetic_demo:Boolean(draft.selectedDestination?.synthetic_demo)}:draft.rail==='zelle_like'?{counterparty:draft.recipientName.trim(),recipient_name:draft.recipientName.trim(),email:draft.p2pEmail.trim().toLowerCase(),synthetic_demo:true}:draft.rail==='deposit'?{counterparty:null,synthetic_demo:true}:{counterparty:draft.recipientName.trim(),recipient_name:draft.recipientName.trim(),account_number:draft.externalAccount,routing_number:draft.externalRouting,account_type:draft.externalAccountType,synthetic_demo:true};const created=await createMoneyMovement({idempotencyKey:`fncu-transfer-${crypto.randomUUID()}`,rail:draft.rail,sourceAccountId:draft.rail==='deposit'?null:account.id,destinationAccountId:draft.rail==='internal'&&!draft.selectedDestination?.directory_destination_id?draft.selectedDestination?.id:null,beneficiaryId:null,amount:draft.amount,currency:'USD',memo:draft.memo,metadata});const completed=created.status==='processing'?await executeMoneyMovement(created.movement_id):created;setResult(completed);sessionStorage.removeItem(KEY);await refresh()}catch(e:any){setError(e?.message||'Unable to authorize this movement.')}finally{setBusy(false)}}
 if(!draft)return <BankingShell><div className="fb-page"><header className="fb-heading"><span>MOVE MONEY · REVIEW</span><h1>Review unavailable</h1><p>The transfer draft is missing or has expired.</p></header><section className="fb-card"><button className="fb-btn primary" onClick={()=>navigate('/transfers')}>Return to transfer center</button></section></div></BankingShell>
 if(result)return <BankingShell><div className="fb-page"><header className="fb-heading"><span>MOVE MONEY</span><h1>{result.status==='completed'?'Payment completed':'Payment status'}</h1><p>The movement was recorded by the FNCU money-movement service.</p></header><section className="fb-card"><div className="fb-success"><Check size={22}/><div><b>{result.status==='completed'?'Movement posted successfully':'Movement accepted for processing'}</b><p>{money(Number(result.amount||draft.amount))} · {result.reference||'Reference pending'}</p></div></div><div className="fb-actions"><button className="fb-btn primary" onClick={()=>navigate(`/transfers?mode=${params.get('rail')||draft.rail}`)}>Make another</button><button className="fb-btn" onClick={()=>navigate('/transactions')}>View activity</button></div></section></div></BankingShell>
 const destinationName=draft.internationalDestination?.recipient_name||draft.selectedDestination?.account_name||draft.recipientName||'Deposit'
 const destinationIdentifier=draft.internationalDestination?.account_number||draft.internationalDestination?.iban||draft.selectedDestination?.account_number||draft.externalAccount||draft.p2pEmail||'—'
 return <BankingShell><div className="fb-page"><header className="fb-heading"><span>MOVE MONEY · STEP 2 OF 2</span><h1>Payment summary</h1><p>Review the complete transfer before you authorize it. No funds have moved yet.</p></header><section className="fb-card"><div className="fb-detail"><span>Rail</span><b>{railLabel(draft.rail)}</b></div><div className="fb-detail"><span>From</span><b>{account?.account_name||'Checking'}<small>{account?.account_number||`•••• ${account?.account_number_last4||'----'}`}</small></b></div><div className="fb-detail"><span>To</span><b>{destinationName}<small>{destinationIdentifier}</small></b></div><div className="fb-detail"><span>Amount</span><b>{money(draft.amount)}</b></div><div className="fb-detail"><span>Fee</span><b>{money(draft.fee)}</b></div><div className="fb-total"><span>Total</span><strong>{money(draft.amount+draft.fee)}</strong></div><div className="fb-detail"><span>Available after</span><b>{money(Math.max(0,available-draft.amount-draft.fee))}</b></div>{draft.memo&&<div className="fb-detail"><span>Memo</span><b>{draft.memo}</b></div>}<div className="fb-actions"><button className="fb-btn" disabled={busy} onClick={()=>navigate(`/transfers?mode=${params.get('rail')||draft.rail}`)}><ArrowLeft size={14}/> Edit transfer</button><button className="fb-btn primary" disabled={busy||draft.amount+draft.fee>available} onClick={()=>void authorize()}>{busy?'Authorizing…':'Authorize payment'} <Check size={15}/></button></div>{draft.amount+draft.fee>available&&<p className="fb-error">The amount now exceeds your available balance. Return and edit the transfer.</p>}{error&&<p className="fb-error">{error}</p>}</section></div></BankingShell>
}
