create table if not exists public.card_transactions (id uuid primary key default gen_random_uuid(), user_id uuid not null references auth.users(id) on delete cascade, card_control_id uuid references public.card_controls(id) on delete set null, transaction_id uuid references public.transactions(id) on delete set null, merchant_name text not null, merchant_category text, amount numeric(18,2) not null, currency text not null default 'USD', status text not null default 'authorized' check (status in ('authorized','settled','declined','reversed','disputed')), authorized_at timestamptz not null default now(), settled_at timestamptz, metadata jsonb not null default '{}'::jsonb, created_at timestamptz not null default now());
create table if not exists public.card_disputes (id uuid primary key default gen_random_uuid(), user_id uuid not null references auth.users(id) on delete cascade, card_transaction_id uuid references public.card_transactions(id) on delete set null, reason text not null, description text, status text not null default 'opened' check (status in ('opened','under_review','resolved','rejected')), created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create index if not exists card_transactions_user_created_idx on public.card_transactions(user_id, created_at desc);
create index if not exists card_disputes_user_created_idx on public.card_disputes(user_id, created_at desc);
alter table public.card_transactions enable row level security;
alter table public.card_disputes enable row level security;
drop policy if exists card_transactions_select_own on public.card_transactions;
create policy card_transactions_select_own on public.card_transactions for select to authenticated using (user_id = auth.uid());
drop policy if exists card_transactions_insert_own on public.card_transactions;
create policy card_transactions_insert_own on public.card_transactions for insert to authenticated with check (user_id = auth.uid());
drop policy if exists card_disputes_select_own on public.card_disputes;
create policy card_disputes_select_own on public.card_disputes for select to authenticated using (user_id = auth.uid());
drop policy if exists card_disputes_insert_own on public.card_disputes;
create policy card_disputes_insert_own on public.card_disputes for insert to authenticated with check (user_id = auth.uid());
drop policy if exists card_disputes_update_own on public.card_disputes;
create policy card_disputes_update_own on public.card_disputes for update to authenticated using (user_id = auth.uid()) with check (user_id = auth.uid());