create index if not exists card_controls_account_id_idx on public.card_controls(account_id);
create index if not exists card_disputes_card_transaction_id_idx on public.card_disputes(card_transaction_id);
create index if not exists card_service_requests_card_control_id_idx on public.card_service_requests(card_control_id);
create index if not exists card_transactions_card_control_id_idx on public.card_transactions(card_control_id);
create index if not exists card_transactions_transaction_id_idx on public.card_transactions(transaction_id);
create index if not exists customer_documents_account_id_idx on public.customer_documents(account_id);
create index if not exists customer_documents_statement_period_id_idx on public.customer_documents(statement_period_id);
create index if not exists idempotency_keys_journal_id_idx on public.idempotency_keys(journal_id);
create index if not exists money_movement_events_user_id_idx on public.money_movement_events(user_id);
create index if not exists money_movement_requests_beneficiary_id_idx on public.money_movement_requests(beneficiary_id);
create index if not exists money_movement_requests_journal_id_idx on public.money_movement_requests(journal_id);
create index if not exists money_movement_requests_source_account_id_idx on public.money_movement_requests(source_account_id);
create index if not exists statement_periods_account_id_idx on public.statement_periods(account_id);
create index if not exists statements_account_id_idx on public.statements(account_id);
create index if not exists transactions_account_id_idx on public.transactions(account_id);
create index if not exists transfer_schedules_beneficiary_id_idx on public.transfer_schedules(beneficiary_id);
create index if not exists transfer_schedules_destination_account_id_idx on public.transfer_schedules(destination_account_id);
create index if not exists transfer_schedules_source_account_id_idx on public.transfer_schedules(source_account_id);
create index if not exists transfer_schedules_user_id_idx on public.transfer_schedules(user_id);
drop index if exists public.transfer_schedule_due_idx;

drop policy if exists card_controls_select_own on public.card_controls;
drop policy if exists card_controls_update_own on public.card_controls;
drop policy if exists card_controls_self on public.card_controls;
create policy card_controls_self on public.card_controls for all to authenticated using ((select auth.uid()) = user_id) with check ((select auth.uid()) = user_id);

drop policy if exists accounts_self_select on public.accounts;
create policy accounts_self_select on public.accounts for select to authenticated using ((select auth.uid()) = user_id);
drop policy if exists beneficiaries_self_all on public.beneficiaries;
create policy beneficiaries_self_all on public.beneficiaries for all to authenticated using ((select auth.uid()) = user_id) with check ((select auth.uid()) = user_id);
drop policy if exists transactions_self_select on public.transactions;
create policy transactions_self_select on public.transactions for select to authenticated using ((select auth.uid()) = user_id);
drop policy if exists statements_self_select on public.statements;
create policy statements_self_select on public.statements for select to authenticated using ((select auth.uid()) = user_id);
drop policy if exists savings_vaults_self_all on public.savings_vaults;
create policy savings_vaults_self_all on public.savings_vaults for all to authenticated using ((select auth.uid()) = user_id) with check ((select auth.uid()) = user_id);
drop policy if exists notifications_self_all on public.notifications;
create policy notifications_self_all on public.notifications for all to authenticated using ((select auth.uid()) = user_id) with check ((select auth.uid()) = user_id);
drop policy if exists audit_logs_self_select on public.audit_logs;
create policy audit_logs_self_select on public.audit_logs for select to authenticated using ((select auth.uid()) = user_id);
drop policy if exists security_events_select_own on public.security_events;
create policy security_events_select_own on public.security_events for select to authenticated using ((select auth.uid()) = user_id);
drop policy if exists secure_messages_self on public.secure_messages;
create policy secure_messages_self on public.secure_messages for all to authenticated using ((select auth.uid()) = user_id) with check ((select auth.uid()) = user_id);
drop policy if exists security_preferences_self on public.security_preferences;
create policy security_preferences_self on public.security_preferences for all to authenticated using ((select auth.uid()) = user_id) with check ((select auth.uid()) = user_id);
drop policy if exists support_cases_self on public.support_cases;
create policy support_cases_self on public.support_cases for all to authenticated using ((select auth.uid()) = user_id) with check ((select auth.uid()) = user_id);
drop policy if exists money_movement_requests_self on public.money_movement_requests;
create policy money_movement_requests_self on public.money_movement_requests for all to authenticated using ((select auth.uid()) = user_id) with check ((select auth.uid()) = user_id);
drop policy if exists money_movement_events_self on public.money_movement_events;
create policy money_movement_events_self on public.money_movement_events for all to authenticated using ((select auth.uid()) = user_id) with check ((select auth.uid()) = user_id);
drop policy if exists transfer_schedules_self on public.transfer_schedules;
create policy transfer_schedules_self on public.transfer_schedules for all to authenticated using ((select auth.uid()) = user_id) with check ((select auth.uid()) = user_id);
drop policy if exists trusted_devices_select_own on public.trusted_devices;
create policy trusted_devices_select_own on public.trusted_devices for select to authenticated using ((select auth.uid()) = user_id);
drop policy if exists trusted_devices_update_own on public.trusted_devices;
create policy trusted_devices_update_own on public.trusted_devices for update to authenticated using ((select auth.uid()) = user_id) with check ((select auth.uid()) = user_id);
drop policy if exists card_transactions_select_own on public.card_transactions;
create policy card_transactions_select_own on public.card_transactions for select to authenticated using ((select auth.uid()) = user_id);
drop policy if exists card_transactions_insert_own on public.card_transactions;
create policy card_transactions_insert_own on public.card_transactions for insert to authenticated with check ((select auth.uid()) = user_id);
drop policy if exists card_disputes_select_own on public.card_disputes;
create policy card_disputes_select_own on public.card_disputes for select to authenticated using ((select auth.uid()) = user_id);
drop policy if exists card_disputes_insert_own on public.card_disputes;
create policy card_disputes_insert_own on public.card_disputes for insert to authenticated with check ((select auth.uid()) = user_id);
drop policy if exists card_disputes_update_own on public.card_disputes;
create policy card_disputes_update_own on public.card_disputes for update to authenticated using ((select auth.uid()) = user_id) with check ((select auth.uid()) = user_id);
drop policy if exists card_service_requests_select_own on public.card_service_requests;
create policy card_service_requests_select_own on public.card_service_requests for select to authenticated using ((select auth.uid()) = user_id);
drop policy if exists card_service_requests_insert_own on public.card_service_requests;
create policy card_service_requests_insert_own on public.card_service_requests for insert to authenticated with check ((select auth.uid()) = user_id);
drop policy if exists statement_periods_insert_own on public.statement_periods;
create policy statement_periods_insert_own on public.statement_periods for insert to authenticated with check ((select auth.uid()) = user_id);
drop policy if exists documents_insert_own on public.customer_documents;
drop policy if exists customer_documents_insert_own on public.customer_documents;
create policy customer_documents_insert_own on public.customer_documents for insert to authenticated with check ((select auth.uid()) = user_id);
