import "jsr:@supabase/functions-js/edge-runtime.d.ts";
import { createClient } from "npm:@supabase/supabase-js@2";

const cors = { "Access-Control-Allow-Origin": "*", "Access-Control-Allow-Headers": "authorization, x-client-info, apikey, content-type", "Access-Control-Allow-Methods": "POST, OPTIONS" };
const json = (body: unknown, status = 200) => new Response(JSON.stringify(body), { status, headers: { ...cors, "Content-Type": "application/json" } });
function secretKey() { const raw = Deno.env.get("SUPABASE_SECRET_KEYS"); if (raw) return JSON.parse(raw).default; return Deno.env.get("SUPABASE_SERVICE_ROLE_KEY")!; }
const adminClient = () => createClient(Deno.env.get("SUPABASE_URL")!, secretKey(), { auth: { autoRefreshToken: false, persistSession: false } });
async function requireAdmin(req: Request, db: ReturnType<typeof adminClient>) { const header = req.headers.get("Authorization") || ""; const token = header.startsWith("Bearer ") ? header.slice(7) : ""; if (!token) return null; const { data, error } = await db.auth.getUser(token); if (error || !data.user) return null; const { data: role } = await db.from("admin_roles").select("role").eq("user_id", data.user.id).eq("role", "admin").maybeSingle(); return role ? data.user : null; }
Deno.serve(async (req) => { if (req.method === "OPTIONS") return new Response("ok", { headers: cors }); if (req.method !== "POST") return json({ ok: false, message: "Method not allowed" }, 405); const db = adminClient(); const admin = await requireAdmin(req, db); if (!admin) return json({ ok: false, message: "Admin authorization required" }, 403); let body: any; try { body = await req.json(); } catch { return json({ ok: false, message: "Invalid request" }, 400); } const userId = String(body?.user_id || "").trim(); const newPassword = String(body?.new_password || ""); if (!/^[0-9a-f-]{36}$/i.test(userId) || newPassword.length < 10 || newPassword.length > 128) return json({ ok: false, message: "Invalid password rotation details" }, 400); const { data: target, error: lookupError } = await db.auth.admin.getUserById(userId); if (lookupError || !target.user) return json({ ok: false, message: "Customer account not found" }, 404); const { error: passwordError } = await db.auth.admin.updateUserById(userId, { password: newPassword }); if (passwordError) return json({ ok: false, message: "Could not update the customer password" }, 500); await db.from("audit_logs").insert({ user_id: admin.id, action: "admin_customer_password_rotated", resource_type: "customer_auth", resource_id: userId, metadata: { target_user_id: userId, email: target.user.email || null } }); return json({ ok: true, user_id: userId }); });
